### ISSUE TITLE
Menu not in English

### ISSUE THREAD

**Issue by neoOpus** [xcanwin/KeepChatGPT#10]
For some reason the menu doesn't switch to english, I've seen in the script that is supported among other languages but in Edge something doesn't work (I didn't test in other browsers)... please revise the logic or a setting to select the language.

**Comment by xcanwin** [comment]
> For some reason the menu doesn't switch to english, I've seen in the script that is supported among other languages but in Edge something doesn't work (I didn't test in other browsers)... please revise the logic or a setting to select the language.

Open this page and take screenshots of both tables, and I'll help you analyze them.
https://gtranslate.io/detect-browser-language

**Comment by LowSkillDeveloper** [comment]
I confirm. The script contains many languages, but everything remains in Chinese. This applies not only to English, other languages also do not work.

**Comment by xcanwin** [comment]
> I confirm. The script contains many languages, but everything remains in Chinese. This applies not only to English, other languages also do not work.

Open this page and take screenshots of both tables, and I'll help you analyze them.
https://gtranslate.io/detect-browser-language

**Comment by xcanwin** [comment]
> I will do a PR

Hey buddy, it's too coincidental. I just submitted the update, but I'm also looking forward to your coding ideas. If it's good, I'll adopt them.

**Comment by neoOpus** [comment]
> > I will do a PR
> 
> Hey buddy, it's too coincidental. I just submitted the update, but I'm also looking forward to your coding ideas. If it's good, I'll adopt them.

Haha yeah, I did the update yesterday, but I was too tired, so I uploaded it right now, and you were already working on 7.8/7.9   
  
Thank you, it works right now, and I did a PR, so I will work on adding more translations and fixing some other…  
  
(I will do another fix for this ui issue, I am using [Superpower ChatGPT - Chrome Web Store (google.com)](https://chrome.google.com/webstore/detail/superpower-chatgpt/amhmeenmapldpjdedekalnfifgnpfnkc) who is probably the one causing it among some other extensions)  
  
 

![](https://user-images.githubusercontent.com/1388336/232528183-5f3c7a86-ca23-46bf-b02e-8f5bc298c83f.png)
