### ISSUE TITLE
Too many requests in 1 hour. Try again later.

### ISSUE THREAD

**Issue by heman0101** [xcanwin/KeepChatGPT#101]
![image](https://user-images.githubusercontent.com/114585822/233926889-d8714606-efd5-4d98-a0dc-04b785ba4757.png)
`Too many requests in 1 hour. Try again later.`
间隔时间调整为150后还是出现上面这个问题该怎么解决，是因为梯子的原因吗

**Comment by lengsihan** [comment]
同问

**Comment by yuzhang-lab** [comment]
+1

**Comment by yy316793** [comment]
不知道是不是服务器崩了，下午15点前还能用的

**Comment by yy316793** [comment]
现在能进了，应该是服务器炸了
