### ISSUE TITLE
还是经常出现 Something went wrong. If this issue persists please contact us through our help center at help.openai.com.

### ISSUE THREAD

**Issue by freedomspiritJohn** [xcanwin/KeepChatGPT#105]
![image](https://user-images.githubusercontent.com/129288685/233962385-089278c9-814b-469e-a33c-771d84c10f9b.png)

**Comment by superggn** [comment]
感觉可能是因为这两天 openai 加了 cloudflare 的真人验证

**Comment by superggn** [comment]
@xcanwin 老兄得空儿瞅眼， 我刚用最新版代码也有这问题

**Comment by MMMMob** [comment]
我也是，同

**Comment by Grpaehpyx** [comment]
+1

**Comment by LemonWade** [comment]
是的，我感觉最近一直something went wrong，openai应该是出手了

**Comment by guichun68** [comment]
我把间隔调整到30s了，还是会掉线，不过能在调试窗口中能看到真人验证的组件，直接点击验证后页面也不用刷新也能登陆了并继续聊天了，也算比之前好很多了。

**Comment by yzy-1995** [comment]
我调成60S还是会掉线，something went wrong,看上面的老哥，调成30s还是会掉线，看来是openai出手了！

**Comment by yangxijun** [comment]
现在好像已经完全用不了了，直接就sth went wrong

**Comment by a5185330** [comment]
> > 之前没有，之前是服务器出问题了，现在已经修复了。
> 
> 登录问题和这个是断开问题是挂钩的吗？不像啊
你这什么眼睛?看不到下面的内容吗?

**Comment by frosthobbit** [comment]
我这更离谱，每一句都是something went wrong

**Comment by yzy-1995** [comment]
> 我这更离谱，每一句都是something went wrong

不至于吧，我是PLus用户，都没这样
![image](https://user-images.githubusercontent.com/24284910/234460767-ea452bff-7d90-478e-bce1-c9389fb75bf3.png)

**Comment by Hushshen** [comment]
> > 我这更离谱，每一句都是something went wrong
> 
> 不至于吧，我是PLus用户，都没这样 ![image](https://user-images.githubusercontent.com/24284910/234460767-ea452bff-7d90-478e-bce1-c9389fb75bf3.png)

我也是Plus用户，但是每一句都是somthing错误

**Comment by anonymouscnuser** [comment]
> 你这什么眼睛?看不到下面的内容吗?

来github戾气还这么重



> 没有,之前是服务器出问题了,现在已经修复了.

> Increase in error rates for some OpenAI models

显然openai修的是模型失败率，不是登录错误或是CF导致的错误

**Comment by jscmp4** [comment]
有时候🪜数据中心集体🔒IP，换个节点fix我的情况至少

**Comment by superggn** [comment]
> @xcanwin 老兄得空儿瞅眼， 我刚用最新版代码也有这问题，动不动就刷新页面然后 checking your browser

我的gpt好了， 就是IP问题， 我推测是这样：
之前最开始的锁IP是一刀切， 直接分两类， 能访问chatgpt的IP和压根不能访问的IP， 这个时候只要自己的梯子能够通过 openai 的 "access denied" 就能正常访问
从加了 cloudflare 真人验证之后， 对IP进行了细化分类， 单纯能访问 chatgpt 不能再作为正常使用的标准， 最好的IP是像之前一样能够正常使用， 次一级别的IP是能通过 access denied, 但是会经常跳出 cloudflare 的真人验证导致断连， 最差的IP才是想之前那样 gpt 页面访问都访问不了
现在gpt带起来的机场业务暴增， 导致以前很多小众机场的IP现在使用人数暴增， 有的还是直接挂机器人的， 这种异常流量暴增把机场IP污染的情况应该不少， 所以虽然有的机场挂 google 上 youtube 很快很爽， 但是在 openai 那里是通过不了最高级别的判定的。
兄弟们选机场的时候尽量选那种有邀请码， 控制人数的机场， 不然在大家都挂梯子用gpt的情况下，IP太容易被污染了
（我不推机场， 不搞事情）

**Comment by yzy-1995** [comment]
> > @xcanwin 老兄得空儿瞅眼， 我刚用最新版代码也有这问题，动不动就刷新页面然后 checking your browser
> 
> 我的gpt好了， 就是IP问题， 我推测是这样： 之前最开始的锁IP是一刀切， 直接分两类， 能访问chatgpt的IP和压根不能访问的IP， 这个时候只要自己的梯子能够通过 openai 的 "access denied" 就能正常访问 从加了 cloudflare 真人验证之后， 对IP进行了细化分类， 单纯能访问 chatgpt 不能再作为正常使用的标准， 最好的IP是像之前一样能够正常使用， 次一级别的IP是能通过 access denied, 但是会经常跳出 cloudflare 的真人验证导致断连， 最差的IP才是想之前那样 gpt 页面访问都访问不了 现在gpt带起来的机场业务暴增， 导致以前很多小众机场的IP现在使用人数暴增， 有的还是直接挂机器人的， 这种异常流量暴增把机场IP污染的情况应该不少， 所以虽然有的机场挂 google 上 youtube 很快很爽， 但是在 openai 那里是通过不了最高级别的判定的。 兄弟们选机场的时候尽量选那种有邀请码， 控制人数的机场， 不然在大家都挂梯子用gpt的情况下，IP太容易被污染了 （我不推机场， 不搞事情）

you are right！

**Comment by xcanwin** [comment]
> > @xcanwin 老兄得空儿瞅眼， 我刚用最新版代码也有这问题，动不动就刷新页面然后 checking your browser
> 
> 
> 
> 我的gpt好了， 就是IP问题， 我推测是这样：
> 
> 之前最开始的锁IP是一刀切， 直接分两类， 能访问chatgpt的IP和压根不能访问的IP， 这个时候只要自己的梯子能够通过 openai 的 "access denied" 就能正常访问
> 
> 从加了 cloudflare 真人验证之后， 对IP进行了细化分类， 单纯能访问 chatgpt 不能再作为正常使用的标准， 最好的IP是像之前一样能够正常使用， 次一级别的IP是能通过 access denied, 但是会经常跳出 cloudflare 的真人验证导致断连， 最差的IP才是想之前那样 gpt 页面访问都访问不了
> 
> 现在gpt带起来的机场业务暴增， 导致以前很多小众机场的IP现在使用人数暴增， 有的还是直接挂机器人的， 这种异常流量暴增把机场IP污染的情况应该不少， 所以虽然有的机场挂 google 上 youtube 很快很爽， 但是在 openai 那里是通过不了最高级别的判定的。
> 
> 兄弟们选机场的时候尽量选那种有邀请码， 控制人数的机场， 不然在大家都挂梯子用gpt的情况下，IP太容易被污染了
> 
> （我不推机场， 不搞事情）

说的对，一个人的666才是最香的

**Comment by MaxYu2** [comment]
我也是一直something go wrong

**Comment by MaxYu2** [comment]
我是文本达到4000token以后就会一直something go wrong
