### ISSUE TITLE
interval是60秒，期间如果没有开梯子，是不是会用国内网络去连接，这样会不会导致封号

### ISSUE THREAD

**Issue by SpursJiang** [xcanwin/KeepChatGPT#111]
作者好。如果插件的interval是60秒，是定时访问apenai？那如果我的梯子是关闭的，是不是这时就会用国内网络去连接。听说国内的网络容易被封号，那这样是不是会导致封号呢？

**Comment by xcanwin** [comment]
不会，openai是因为尊重中国的政策才不让中国用户访问的，没连节点就去访问只会收到他们友好的提示，他们正在迫不及待地申请中国的代理公司希望获取中国认可。

**Comment by SpursJiang** [comment]
> 

好的，谢谢作者
