### ISSUE TITLE
更新今天的9.7版本后，edge和chrome都出现了界面问题，点击金标后，移动到右边的菜单栏，菜单会消失

### ISSUE THREAD

**Issue by xixixi2000** [xcanwin/KeepChatGPT#112]
打开扩展后，左边的导航栏出现了重影，点击金标后移动到选项就消失，无法点击
![1682387614487](https://user-images.githubusercontent.com/54608209/234155202-7d94df04-65d4-4ec7-ab12-7cceb4e740c8.png)

移动到这里后，菜单还在
![1682387696037](https://user-images.githubusercontent.com/54608209/234155380-8afe085d-a7ef-4f59-bb69-9d283024b2b1.png)

继续右移，菜单消失
![1682387741569](https://user-images.githubusercontent.com/54608209/234155449-feb0416a-5597-440f-b0d0-9021ff518a88.jpg)

**Comment by Ezra-Chan** [comment]
![image](https://user-images.githubusercontent.com/26107204/234156358-ad6c9617-fffd-4984-93ef-64fec1db1965.png)
不开插件的话也有，应该是官网的问题

**Comment by Ezra-Chan** [comment]
更新脚本试下呢

**Comment by xixixi2000** [comment]
bug fixed :)
