### ISSUE TITLE
界面显示错乱，分辨率 1080*1920 竖屏

### ISSUE THREAD

**Issue by yang-xiaodong** [xcanwin/KeepChatGPT#113]
Plus 用户。

![image](https://user-images.githubusercontent.com/8205994/234156474-7a8ab659-460f-4a90-b13d-8616c699b920.png)

**Comment by yang-xiaodong** [comment]
应该是官方的问题，插件禁用后也是一样

**Comment by Ezra-Chan** [comment]
> 应该是官方的问题，插件禁用后也是一样

更新脚本试下呢

**Comment by xcanwin** [comment]
> > 应该是官方的问题，插件禁用后也是一样
> 
> 更新脚本试下呢

👍
