### ISSUE TITLE
开了10分钟整个chrome浏览器会卡顿。但是我没办法定位和提供更多信息

### ISSUE THREAD

**Issue by Giles2000** [xcanwin/KeepChatGPT#116]
就我一个人这样吗？
关掉浏览器重进就又好了，但是还会复发，刷新间隔时间180秒
目前版本是9.2 刚刚更新到9.8还没测试

**Comment by xcanwin** [comment]
谢谢反馈，最新版已经做了不少性能优化，忘记回复你了。
