### ISSUE TITLE
建议展开设置菜单做成点击而不是悬停

### ISSUE THREAD

**Issue by zhongmuxiao** [xcanwin/KeepChatGPT#118]
鼠标移动到上面，甚至扫过都能展开设置菜单，容易误触，建议改成点击展开

**Comment by zktzktzkt** [comment]
我觉得没问题，不用改

**Comment by xcanwin** [comment]
扫过展开有利于提高工作效率。

**Comment by GitYohoo** [comment]
我也觉得容易误触。Keepchatgpt的设置又不需要经常变更，而需要经常点击靠近Keepchatgpt的newchat，所以经常误触，建议修改

**Comment by zhatlas** [comment]
建议再次考虑一下
