### ISSUE TITLE
调整间隔不生效

### ISSUE THREAD

**Issue by goldenapple1** [xcanwin/KeepChatGPT#126]
在按下调整间隔后，会正常弹出询问具体数值的提示，但是按下提示的GO没有反应，关掉之后再开发现间隔还是修改之前的间隔
（想调成300来着）

Chrome版本112.0.5615.138（64 位）
Windows内部版本19045.2846
油猴v4.18.1

**Comment by goldenapple1** [comment]
好家伙这个检查更新怎么说9.5是最新版，我一开greasyfork就看到最新是10.0

**Comment by goldenapple1** [comment]
最新版调整间隔是生效了，但我现在更好奇检查更新是不是正常工作的

**Comment by xcanwin** [comment]
一方面，因为没资金部署服务器，所以使用github或者greasyfork作为新版本判断的话涉及到跨域问题，因为跨域了所以必然有缓存问题，除非自己部署服务器才可以解决跨域问题。
另一方面，今晚新版本修复了版本检验的bug。
我一直在维护着。

**Comment by goldenapple1** [comment]
感谢大佬的回复，也感谢你维护脚本所付出的努力
