### ISSUE TITLE
Add option to change language from UI

### ISSUE THREAD

**Issue by duramato** [xcanwin/KeepChatGPT#127]
Currently the script only shows in Chinese for me, but i'd like to have an option to change to another language

![image](https://user-images.githubusercontent.com/10121067/234306648-eb04bde6-9627-4230-9508-e742dd7b0434.png)

Example from another script: 

![image](https://user-images.githubusercontent.com/10121067/234306749-0f410289-8469-466b-b635-01a1bd82eab8.png)

**Comment by xcanwin** [comment]
你当前是什么版本

**Comment by duramato** [comment]
`Version: 10.0`

**Comment by duramato** [comment]
![image](https://user-images.githubusercontent.com/10121067/234589813-25eab4e6-788a-4cc4-aedc-2a5bab2610ba.png)

![image](https://user-images.githubusercontent.com/10121067/234589865-b2c0a025-c3c5-42ea-b3f7-d28f4ec61102.png)

**Comment by xcanwin** [comment]
fixed in 10.9
