### ISSUE TITLE
好像没效果

### ISSUE THREAD

**Issue by Hushshen** [xcanwin/KeepChatGPT#128]
我不知道为啥 我用起来好想没想过，刚装了试着使用chat gpt还是会跳出somthing的错误，不过其他问题是没有了，主要的还是somthing的错误 ，换了好多节点都不行

**Comment by wmxl** [comment]
我也是没效果。。。

**Comment by JackieLee-cn** [comment]
同样，没效果

**Comment by wmxl** [comment]
貌似现在没有这个问题了， 现在不装任何插件也不会马上就出错
