### ISSUE TITLE
【调整间隔】的功能显示，多次点击不需要多次遮罩页面

### ISSUE THREAD

**Issue by damon7609** [xcanwin/KeepChatGPT#129]
一个小Bug，多次点击点击【调整间隔】后，屏幕置灰，需要多次点击【×】，才能恢复
第一次点击效果：
![image](https://user-images.githubusercontent.com/34952213/234505764-f55943d9-2147-4207-90c7-c98076bafde5.png)
多次点击后：
![image](https://user-images.githubusercontent.com/34952213/234505945-865d39c4-248f-44fb-9e4d-c31c72da0c10.png)

**Comment by damon7609** [comment]
逻辑没问题，但大可不必😀感谢大佬为爱发电！

**Comment by Ezra-Chan** [comment]
有道理👍
