### ISSUE TITLE
/api/auth/session Status 429 Too Many Requests

### ISSUE THREAD

**Issue by JJQuiet** [xcanwin/KeepChatGPT#13]
历史记录和会话框加载不出来

**Comment by xcanwin** [comment]
这个场景暂时没遇到，你可以提供一下网页截图和控制台截图，我帮你分析一下。

**Comment by JJQuiet** [comment]
@xcanwin 
![image](https://user-images.githubusercontent.com/60891137/232312545-7653ead3-a130-4fbb-bb62-94a091150b9c.png)

**Comment by xcanwin** [comment]
看起来你浏览器还安装了好几个插件，你实验一下：
（1）把KeepChatGPT关掉+其他所有chatgpt插件关掉
（2）把KeepChatGPT开着+其他所有chatgpt插件关掉
（3）把KeepChatGPT关掉+其他所有chatgpt插件开着
看看3种情况的chatgpt会不会出现429 too many requests

**Comment by JJQuiet** [comment]
还是没有用

**Comment by xcanwin** [comment]
这对我这个项目算是一个课外题的回答了，虽然你没给我star，不过提供几个答案你需要抛砖引玉自行分析：
1、你和别人共享一个账号或者API密钥，他们请求得比你频繁。
2、你曾经运行了一些自动化的chatgpt软件在不停地与chatgpt进行问答，只是你还不知情。
3、你openai账号里免费的18美元额度已经被你使用完了。

**Comment by JJQuiet** [comment]
1、我的账号是最近几天注册的，没有免费的额度，开通了API密钥，但我不是付费用户
![image](https://user-images.githubusercontent.com/60891137/232320300-8c546a8e-970a-4020-bad4-24d0fe0e9059.png)
2.我的vscode安装了chatgpt插件，但是由于没有API使用次数，所以应该也没有不停地与chatgpt进行问答

**Comment by xcanwin** [comment]
对，需要换个接码号码重新注册

**Comment by zimplexing** [comment]
这个问题我也碰到了，是真人验证之后，插件一直在发请求，导致一直返回 429，短时间被发送太多请求，导致账号是不是被openai 限制了，我已经过了一天了，请求还是 429

**Comment by leconio** [comment]
你这个应该是cf warp过了？没ip资源，ipv6 是个选择

**Comment by eggachecat** [comment]
+1 429一天了（没到24小时 现在估计16个小时）还是没有解封（plus）
很奇怪 openai最近加大限制了？而且看着像openai的后端的限制（cf过了

**Comment by meesii** [comment]
![image](https://user-images.githubusercontent.com/1815046/233400222-760970c5-6756-4a55-a43e-b98678a9288d.png)

我最早也是刷session这个接口，后面出现频繁就换这个首页了。
作者30秒刷一次，还是很容易触发频繁检测的。

**Comment by leconio** [comment]
cf过基本都会出现这个问题，不要cf，不要cf。一个ip好几百人用，不429才怪

**Comment by eggachecat** [comment]
请问啥叫不要cf，这里的cf啥意思？我一直以为指的是cloudflare。。。？
我更新下我的状态：过了~24小时解封了；我这边30s甚至不够，，，（不到30s就踢了
我还额外做了一些random。。。但还是会触发，现在只能感恩刷新使用了。。。
```javascript
function keepChat() {
    var randomSeconds = 10 + 10 * (Math.random() - 0.5);
    console.log('wait', randomSeconds, 'seconds...')
    setTimeout(() => fetch("/api/auth/session").then((response) => {
        response.text().then((data) => {
            try {
                var contentType = response.headers.get('Content-Type');
                if (contentType.indexOf("application/json") > -1 && response.status !== 403 && data.indexOf(`"expires":"`) > -1) {
                    console.log(data)
                    keepChat()
                } else {
                    alert(`KeepChatGPT: FETCH`);
                }
            } catch (e) {
                alert(`KeepChatGPT: FETCH: ERROR: ${e},\nERROR RESPONSE:\n${data}`);
            }
        })
    }), randomSeconds * 1000)
}
keepChat()
```

**Comment by leconio** [comment]
@eggachecat 抱歉我可能没说明白，就是你说的那个意思cloudflare。

**Comment by delicacyyy** [comment]
意思是用了warp的机器容易触发429是吗

**Comment by xcanwin** [comment]
已新增自定义频率功能，降低频率或者跟换梯子机房可解决。

**Comment by leconio** [comment]
> 意思是用了warp的机器容易触发429是吗

yes
