### ISSUE TITLE
取消审计似乎失效

### ISSUE THREAD

**Issue by GoldenSheep402** [xcanwin/KeepChatGPT#134]
![Snipaste_2023-04-26_17-52-56](https://user-images.githubusercontent.com/67376942/234540075-21b5cde9-b37a-4a87-a46b-0528305e947f.jpg)

**Comment by a5185330** [comment]
这功能是取消红标,不被审查到.你这个是chatgpt不让输入的词汇.中间加个-就行了.像是nig-ger

**Comment by qysaber** [comment]
> 

哈哈哈，笑死我了

**Comment by GoldenSheep402** [comment]
绷，给它发了篇气候变化的文章，搞不明白什么词能触发这玩意
