### ISSUE TITLE
悬浮时间太短

### ISSUE THREAD

**Issue by Cx330-502** [xcanwin/KeepChatGPT#136]
最新版本的脚本
悬浮时间太短，鼠标还没移动到菜单上就消失了

**Comment by Ezra-Chan** [comment]
麻烦提供下菜单显示的截图

**Comment by Cx330-502** [comment]
![image](https://user-images.githubusercontent.com/105686930/234773823-0e3dc8d7-8ad7-4410-8627-71e07ffa0e2d.png)
当我把鼠标从金色标志向菜单移动时，菜单会快速消失，鼠标来不及放到菜单上

**Comment by xcanwin** [comment]
你屏幕分辨率多少，感觉是你分辨率太高了

**Comment by Cx330-502** [comment]
笔记本默认的1920*1080啊，缩放是125%

**Comment by xcanwin** [comment]
已更新UI
