### ISSUE TITLE
关于 取消审计 功能 能介绍下原理咩?

### ISSUE THREAD

**Issue by lllomh** [xcanwin/KeepChatGPT#137]
关于 取消审计 功能 能介绍下原理咩?  要加什么巧妙的提示词? 最大程度地免受影响呢?

**Comment by xcanwin** [comment]
https://github.com/xcanwin/KeepChatGPT/issues/40

**Comment by lllomh** [comment]
这是来自QQ邮箱的自动回复邮件。你好，由于邮件较多，三天内会尽快给你回复。

**Comment by lllomh** [comment]
这是来自QQ邮箱的自动回复邮件。你好，由于邮件较多，三天内会尽快给你回复。
