### ISSUE TITLE
大家遇到过语言问题了吗？

### ISSUE THREAD

**Issue by echorenyuan** [xcanwin/KeepChatGPT#139]
我是chrome浏览器，安装完了模式人日语
```
navigator.languages
(8) ['zh-CN', 'zh', 'en', 'zh-TW', 'fr', 'da', 'uz', 'ja']
```
mac电脑，浏览器和系统都默认中文

**Comment by xcanwin** [comment]
通过你提供的信息，插件会优先显示zh-CN的语言包。
你遇到了什么问题，截图看看。

**Comment by echorenyuan** [comment]
<img width="353" alt="image" src="https://user-images.githubusercontent.com/11420318/234784260-0b9aec95-80b8-4736-a9fa-14c98212a05e.png">
我这里不是优先显示的，也觉得很奇怪

**Comment by echorenyuan** [comment]
> 通过你提供的信息，插件会优先显示zh-CN的语言包。 你遇到了什么问题，截图看看。

大佬，你看我截图，默认安装后就这个

**Comment by echorenyuan** [comment]
> navigator.languages

你在控制面板里面输入下`navigator.languages`看什么情况

**Comment by xcanwin** [comment]
我知道了，稍等，正在修复

**Comment by Zarah636** [comment]
> 我是chrome浏览器，安装完成了模型人日语
> 
> ```
> navigator.languages
> (8) ['zh-CN', 'zh', 'en', 'zh-TW', 'fr', 'da', 'uz', 'ja']
> ```
> 
> mac电脑，浏览器和系统都默认中文



> 通过你提供的信息，插件会先显示zh-CN的语言包。 你遇到了什么问题，截图看一看。

![image](https://user-images.githubusercontent.com/66152392/234795939-432e0c78-dfb0-4c33-b111-0029dcdcb1e8.png)
更新10.5后语言变成俄语了。

**Comment by xcanwin** [comment]
@Zarah636 @echorenyuan @jx453331958 已在10.6中修复，谢谢反馈

**Comment by Ezra-Chan** [comment]
> @Zarah636 @echorenyuan @jx453331958 已在10.6中修复，谢谢反馈

https://github.com/xcanwin/KeepChatGPT/commit/f870dfa466560cdcd8b8c01b26bd53e35408c6fa#r110796060，这样还是只显示中文

**Comment by xcanwin** [comment]
> > @Zarah636 @echorenyuan @jx453331958 已在10.6中修复，谢谢反馈
> 
> [f870dfa#r110796060](https://github.com/xcanwin/KeepChatGPT/commit/f870dfa466560cdcd8b8c01b26bd53e35408c6fa#r110796060) 这样还是只显示中文

👍🏻已修正

**Comment by Zarah636** [comment]
> @Zarah636 @echorenyuan @jx453331958 已在10.6中修复，谢谢反馈

![image](https://user-images.githubusercontent.com/66152392/234816641-12ec7be5-075e-49f6-8e78-4c5023239c19.png)
显示为繁体中文

**Comment by Ezra-Chan** [comment]
> ![image](https://user-images.githubusercontent.com/66152392/234816641-12ec7be5-075e-49f6-8e78-4c5023239c19.png) 显示为繁体中文
哪个版本啊

**Comment by Zarah636** [comment]
> > ![image](https://user-images.githubusercontent.com/66152392/234816641-12ec7be5-075e-49f6-8e78-4c5023239c19.png) 显示为繁体中文
> > 哪个版本啊

10.7和10.8都显示繁体中文

**Comment by Zarah636** [comment]
> 控制台执行：navigator.languages 复制一下结果给我 我模拟你的场景看看什么情况

(5) ['zh', 'zh-TW', 'en', 'zh-CN', 'ru']

**Comment by Ezra-Chan** [comment]
> (5) ['zh', 'zh-TW', 'en', 'zh-CN', 'ru']
zh没匹配到，匹配了zh-TW

**Comment by Zarah636** [comment]
> > > 控制台执行：navigator.languages 复制一下结果给我 我模拟你的场景看看什么情况
> > 
> > 
> > (5) ['zh', 'zh-TW', 'en', 'zh-CN', 'ru']
> 
> 在10.9中已修复，已提高兼容性

好了，感谢

**Comment by Ezra-Chan** [comment]
> 在10.9中已修复，已提高兼容性

https://github.com/xcanwin/KeepChatGPT/commit/4eb4a33c4245bb9822d192cf5b529da2f97161ec#r110956437
按下面这样改可以吗
https://github.com/Ezra-Chan/KeepChatGPT/commit/92b0309208bb9a6c6395989b9628cc0b03073de0

**Comment by Masterxiechengxun** [comment]
更新为最新版，修改一下浏览器设置的默认语言就好了
