### ISSUE TITLE
有用但不多

### ISSUE THREAD

**Issue by TankingCao** [xcanwin/KeepChatGPT#143]
还是会出现类似的问题，但好像确实是变少了，还是有点用的
![CopyQ OWQxiJ](https://user-images.githubusercontent.com/102155030/234826419-4ab26942-1ff3-4761-8161-56c6235dc4fb.png)

**Comment by qysaber** [comment]
昨天之前配合网络比较好的梯子，效果很可以，今天开始不太行了，毕竟这种手段openai想扼杀迟早的，哎
