### ISSUE TITLE
克隆对话是干啥的？

### ISSUE THREAD

**Issue by learner-xcs** [xcanwin/KeepChatGPT#144]
克隆对话是干啥的？

**Comment by xcanwin** [comment]
勾选以后，当你点击聊天页面里的用户头像时，就会自动把对话内容直接拷贝到聊天框里，方便你快速编辑之前的对话，同时还能保留之前的对话。
我个人的再次编辑的频率非常高。因为提示工程不是一句话就能完成的，需要不断地在原来的语句上修改词汇。

区别于原生的这个：
<img width="114" alt="图片" src="https://user-images.githubusercontent.com/14187349/234854851-1cc6d5a1-b7bc-44f6-a3e6-5e692aa24df3.png">

**Comment by xcanwin** [comment]
readme已添加详细的说明：https://github.com/xcanwin/KeepChatGPT/blob/main/README_CN.md#%E5%85%B3%E4%BA%8E-%E5%85%8B%E9%9A%86%E5%AF%B9%E8%AF%9D-%E5%8A%9F%E8%83%BD

**Comment by learner-xcs** [comment]
了解，多谢您！
