### ISSUE TITLE
没有出现金标怎么回事啊

### ISSUE THREAD

**Issue by GitBiData** [xcanwin/KeepChatGPT#145]
油猴上显示启动成功了，重新卸载了安装也不行，f12控制台没报错信息，也把其他gpt插件卸载了也还是不行

**Comment by GitBiData** [comment]
F12控制台过段时间报这个错，跟这个报错有关系嘛
checked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

**Comment by bikabiu1** [comment]
我的是Script error in [Greasemonkey 脚本 https://github.com/xcanwin/KeepChatGPT//KeepChatGPT；版本 11.0]:
ReferenceError: GM_getValue is not defined [KeepChatGPT:706:19](user-script:https%3A//github.com/xcanwin/KeepChatGPT//KeepChatGPT)
    <anonymous> user-script:https://github.com/xcanwin/KeepChatGPT//KeepChatGPT:706
