### ISSUE TITLE
克隆对话建议加一个快捷键小功能

### ISSUE THREAD

**Issue by 111-dep** [xcanwin/KeepChatGPT#148]
如果我的对话太长了，当前页面是找不到自己的头像的，能否设置一个快捷键或者自定义快捷键，可以让用户更方便复制prompt，十分感谢

**Comment by xcanwin** [comment]
意思是在每个对话右下角加一个克隆对话按钮？我听听你的想法

**Comment by 111-dep** [comment]
对话的右下角加一个克隆对话按钮，这个想法很不错。如果我的对话太长，我还需要用滚轮向上滑动，如果右下角有个克隆对话按钮，就非常的方便。我还有一个想法，比如自定义一个快捷键，例如：ALT+1，这样的话，我甚至不需要动鼠标，就可以克隆对话，十分的方便。

**Comment by xcanwin** [comment]
快捷键这个想法不错只不过一般对话有很多，有时候超过20个。

**Comment by xcanwin** [comment]
不过我想到一个更好玩的玩法了，等我实现出来。

**Comment by 111-dep** [comment]
好的好的，加油！其实快捷键只支持克隆上一次问答，就已经很方便了。很期待你的新玩法

**Comment by cosmopolitan033** [comment]
我想问一下这个克隆对话是做什么的 没搞懂

**Comment by RuoyuLee** [comment]
> 我想问一下这个克隆对话是做什么的 没搞懂

就是点击下你某次对话的头像，就会把这次对话直接粘贴到文本框内
