### ISSUE TITLE
Two minor issues on README_EN.md  => README_EN.md上的两个小问题

### ISSUE THREAD

**Issue by yanCode** [xcanwin/KeepChatGPT#151]
1. The link to one of the "Installation repositories" is not properly set, now is un-clickable. It should take you to the "Install" section when clicked.
2. The link to GreasyFork points to a Chinese version of the KeepChatGPT page. Instead, it should go to the English version.

========I am going to reiterate this bug in Chinese ============

README_EN.md 上有两个小问题。
“Installation repositories” 中的一个链接没有正确设置，无法点击。点击时应该跳转到“Install”部分。
GreasyFork 的链接指向 KeepChatGPT 在GreasyFork上的详细页面的中文版本。它应该链接到英文版本。

我马上为之提交一个pull request.

**Comment by xcanwin** [comment]
谢谢反馈和提交PR
