### ISSUE TITLE
建议添加功能：固定提示词

### ISSUE THREAD

**Issue by yuantao313** [xcanwin/KeepChatGPT#156]
如题，有时候告诉ChatGPT一些规则以便询问较多问题时，ChatGPT会在几次对话后“忘掉”较久的提示语，可以设置固定提示词，每次询问时都进行拼接发送

**Comment by xcanwin** [comment]
分享一下你的具体场景和常常做的事，以及希望插件做的事（固定哪些提示词），具体一点才好理解你描述的情况

**Comment by zktzktzkt** [comment]
比如我要每次问话的时候，因为gpt的回答经常胡诌，所以我经常会在我的提问末尾追加“一步一步慢慢想”或者“请准确回答”之类的prompt。
想问下能不能实现每次我提问问题的时候，比如keepChatGPT上有个输入框，我在其中输入字符串，然后我每次提问问题的时候，会在我自动追加我设置的字符串

 @xcanwin

**Comment by zktzktzkt** [comment]
比如我要每次问话的时候，因为gpt的回答经常胡诌，所以我经常会在我的提问末尾追加“一步一步慢慢想”或者“请准确回答”之类的prompt。
想问下能不能实现每次我提问问题的时候，比如keepChatGPT上有个输入框，我在其中输入字符串，然后我每次提问问题的时候，会自动追加我在keepChatGPT上设置的字符串

@xcanwin
