### ISSUE TITLE
打开新对话插件一切正常 切换到之前的对话插件消失

### ISSUE THREAD

**Issue by gsunlun** [xcanwin/KeepChatGPT#157]
打开新对话插件一切正常 切换到之前的对话插件消失

**Comment by xcanwin** [comment]
谢谢反馈，已在版本11.2中修复

**Comment by CurtisWong458** [comment]
在历史对话里面重新点击会出现Something went wrong, please try reloading the conversation.

**Comment by gsunlun** [comment]
兄弟经济有限 但我必须支持你5块钱！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月03日 04:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xcanwin/KeepChatGPT] 打开新对话插件一切正常 切换到之前的对话插件消失 (Issue #157) |

谢谢反馈，已在版本11.2中修复

**Comment by xcanwin** [comment]
> 在历史对话里面重新点击会出现Something went wrong, please try reloading the conversation.

升级到最新版即可

**Comment by xcanwin** [comment]
> 兄弟经济有限 但我必须支持你5块钱！
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年05月03日 04:04 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [xcanwin/KeepChatGPT] 打开新对话插件一切正常 切换到之前的对话插件消失 (Issue #157) | 谢谢反馈，已在版本11.2中修复 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

哥们给力，谢谢支持！
