### ISSUE TITLE
By Far The Best ChatGPT Plugin Ever Seen from The Market

### ISSUE THREAD

**Issue by hao-lh** [xcanwin/KeepChatGPT#158]
This ChatGPT plugin is undoubtedly the best available in the market. To further enhance its functionality, I have a few suggestions for additional features that could make the user experience even more seamless:

1. Allow users to set GPT-4 as the default model instead of the current GPT-3.5.
Some scripts in the market already enable this, so it would be great to integrate such functionality into one centralized location.
https://greasyfork.org/en/scripts/464284-chatgpt-is-gpt4-by-default-plus-only-available/code

2. Incorporate timestamps for each conversation session.
The current ChatGPT lacks detailed timestamps on the right panel, making it difficult to track when specific conversations took place. Adding a long-format timestamp, like MON, 05-01-2023 11:11:11 AM, beneath each conversation block beside the general date ranges (e.g., yesterday or previous 7/30 days) on the left panel would be helpful.

3. Provide an option for users to receive responses all at once instead of word by word.
While some users might enjoy the current word-by-word output style, others may find it bothersome. Offering an alternative to receive the entire response instantly could cater to different user preferences.

Once again, this is the best ChatGPT plugin I have encountered in the market, and I truly appreciate your hard work.
If possible please consider suggestions above that could make the user experience even more seamless.
Thanks.

**Comment by xcanwin** [comment]
Thank you for your recognition. Your ideas are good and I will slowly figure out a way to implement them. 
However, for the first point, I don't have a Plus account, so my homepage purification function is implemented by searching for relevant Plus user screenshots to imitate. 
As for the third point, I think the current method is good. Outputting one character at a time is helpful for timely loss prevention. I often terminate the output of ChatGPT in advance when it outputs two lines, which improves learning efficiency.

**Comment by hao-lh** [comment]
Thanks for the prompt response.
If need any test assistance during development, feel free to let me know.

**Comment by neoOpus** [comment]
if there are no conflict with Superpower ChatGPT (extension) I would've recommanded it as it solve some of your suggested additions and add some more feature but right now the layout is broken when you have both active at the same time 

![image](https://user-images.githubusercontent.com/1388336/236358058-b36aa0e0-1d34-40bf-ae71-e8cad2e9f3e2.png)

**Comment by neoOpus** [comment]
https://github.com/xcanwin/KeepChatGPT/issues/153#issuecomment-1543225636

**Comment by xcanwin** [comment]
> if there are no conflict with Superpower ChatGPT (extension) I would've recommanded it as it solve some of your suggested additions and add some more feature but right now the layout is broken when you have both active at the same time
> 
> ![image](https://user-images.githubusercontent.com/1388336/236358058-b36aa0e0-1d34-40bf-ae71-e8cad2e9f3e2.png)

这个bug在前面几个版本已被我修复，忘记提醒你了。
