### ISSUE TITLE
Sorry, you have been blocked 出现这个是什么意思

### ISSUE THREAD

**Issue by CatZui** [xcanwin/KeepChatGPT#159]
![image](https://user-images.githubusercontent.com/106656694/235862824-08f1141f-2ec3-4d5a-8081-aa355d6c99e0.png)

**Comment by ydrk12** [comment]
你的IP泄漏或者被识别成机器人了, 试试清楚所有的有关OpenAI的cookies和缓存, 然后重新登录, 或者换一个浏览器. 但是我这里即使重新登录了, 也无法相应.

**Comment by qyshiki** [comment]
你是否还用了其他可能盗取你浏览器token 、cookie的插件？比如webchatgpt？用这类插件之后，即使你卸载，你也会发现你发送消息会一直提示 请求频繁，直到。。。

**Comment by CatZui** [comment]
> 

我有用过webchatgpt，那我该怎么办

**Comment by Shi-Ming-Shuai** [comment]
我刚才也出现了这个情况 ，我尝试了很久 ，可能是ip地址的问题   你多换几个ip试一试，我换到美国登录进来了。
进来以后还有一个问题就是 chatgpt不回答问题，一直在那闪
![image](https://user-images.githubusercontent.com/62270889/235934005-8b23b2c8-20e5-46b0-9ca3-a1a820317e3a.png)

**Comment by qyshiki** [comment]
这种只要没明确提示被block，就有救，清除缓存，注销，等八小时左右，就解封了。遇上高负载就会更久

**Comment by CatZui** [comment]
> 这种只要没明确提示被block，就有救，清除缓存，注销，等八小时左右，就解封了。遇上高负载就会更久

嗯嗯好 谢谢 我试一下

**Comment by CatZui** [comment]
> 我刚才也出现了这个情况 ，我尝试了很久 ，可能是ip地址的问题 你多换几个ip试一试，我换到美国登录进来了。 进来以后还有一个问题就是 chatgpt不回答问题，一直在那闪 ![image](https://user-images.githubusercontent.com/62270889/235934005-8b23b2c8-20e5-46b0-9ca3-a1a820317e3a.png)

谢谢 我换节点试试看 我以为是我的号被封了

**Comment by Sostay** [comment]
我也遇到了……

**Comment by fi5** [comment]
我也是。貌似是机场ip被封了

**Comment by wanglefeifei** [comment]
有解决办法吗

**Comment by ydrk12** [comment]
@wanglefeifei 清除cookies和缓存, 然后更换没有被封的节点, 然后重新登录一遍, 我这里换了节点以后还等了一天才正常的.

**Comment by zxfhit** [comment]
> 

有推荐的节点吗

**Comment by 01GitHub10** [comment]
为什么我用的国外服务器搭建的个人节点ip也这样

**Comment by 01GitHub10** [comment]
> 

有什么不用换IP的方法吗，换过服务器了每次都不行

**Comment by garychian** [comment]
> 我也是这个问题，我自己搭建的VPS也是碰到这个问题

**Comment by MAOGE2018** [comment]
一样的问题，试过很多方案，但是还是不管用！！！
Sorry, you have been blocked

If you believe this was a mistake, please contact us through our [help center](https://help.openai.com/en/) [Ray ID:7cf4d306f8f80fef]

**Comment by ydrk12** [comment]
我觉得你们搭建服务器以前, 最好试试IP信誉测试...要是有一个数据库把你记录在不信任的IP里面, 搭建了也会被block
