### ISSUE TITLE
使用最新版本的脚本，ChatGPT网页变得非常卡顿

### ISSUE THREAD

**Issue by GuoXianSen** [xcanwin/KeepChatGPT#162]
卡顿体现在，我鼠标滚轮上下滑动的时候，非常卡顿，我测试了Chrome浏览器和Edge浏览器，在关闭脚本和打开脚本前后的对比，有非常明显的区别，我不知道是个例还是都这样。

**Comment by xcanwin** [comment]
具体现象有哪些？
最好附上界面截图和控制台截图。
截图看看勾选了哪些功能

**Comment by xcanwin** [comment]
谢谢反馈，已在最新版11.9中优化性能，修复了bug
