### ISSUE TITLE
使用KeepchatGPT无法进入Google Scholar

### ISSUE THREAD

**Issue by RudyKriss** [xcanwin/KeepChatGPT#164]
使用插件后，无法进入Google Scholar，提示显示有异常流量，如下：
“我们的系统检测到您的计算机网络中存在异常流量。请稍后重新发送请求。”
没有关闭插件的功能，无法验证是否是插件的问题，但是是使用插件后出现的问题

**Comment by xcanwin** [comment]
要不要这么夸张，我写了这么久代码，就没在代码里写过google几个字，功能里也没有和谷歌有关东西，兄弟，你感觉检查一下和卸载其他拓展吧，最近偷openai token的插件和拓展特别多，居然还有虎视眈眈你谷歌信息的。

**Comment by xcanwin** [comment]
本插件作用的域名只有openai.com，你可以阅读第47行代码那个match值
