### ISSUE TITLE
可否加入gpt4消息限制的计数和计时功能

### ISSUE THREAD

**Issue by spicyoil** [xcanwin/KeepChatGPT#169]
gpt4现在限制3小时25个消息真c
人工去计算3小时内消息数太不方便了，如果插件能自动计算和显示就好了 谢谢！

**Comment by xcanwin** [comment]
我前几天在其他地方道听途说了plus用户有这个限制以后，也有这个想法。
不过我没有plus用户，目前的净化首页我是根据谷歌搜索到的plus用户首页手写代码模仿的，还不确定plus用户是不是和普通用户一样。

**Comment by xcanwin** [comment]
你的plus账号勾选净化首页并点击New chat后，也是这样的吗？
![首页](https://github.com/xcanwin/KeepChatGPT/raw/main/assets/index_light.png)

**Comment by Go0p** [comment]
![image](https://user-images.githubusercontent.com/38928800/236425574-7ffacff8-3791-41b7-a98a-84fb32fd9090.png)

**Comment by spicyoil** [comment]
![image](https://user-images.githubusercontent.com/22583570/236601774-af94b289-801e-41ed-87fb-271026d524fa.png)
![image](https://user-images.githubusercontent.com/22583570/236601794-e6922bbf-a761-465f-a68e-fd68a16240b4.png)

是这样的 上面可以选择是gpt3还是gpt4 默认是gpt3

**Comment by yige-yigeren** [comment]
> 你的plus账号勾选净化首页并点击New chat后，也是这样的吗？ ![首页](https://github.com/xcanwin/KeepChatGPT/raw/main/assets/index_light.png)

最近有一次UI更新
![image](https://github.com/xcanwin/KeepChatGPT/assets/53390868/fed2e888-7b3b-4151-9a14-c05e08d6df0a)
我这有一份直接另存为的网页文件，希望能有帮助（我删除了我能找到的个人信息部分）
[Downloads.zip](https://github.com/xcanwin/KeepChatGPT/files/11500609/Downloads.zip)

**Comment by xcanwin** [comment]
> > 你的plus账号勾选净化首页并点击New chat后，也是这样的吗？ ![首页](https://github.com/xcanwin/KeepChatGPT/raw/main/assets/index_light.png)
> 
> 最近有一次UI更新 ![image](https://user-images.githubusercontent.com/53390868/239016381-fed2e888-7b3b-4151-9a14-c05e08d6df0a.png) 我这有一份直接另存为的网页文件，希望能有帮助（我删除了我能找到的个人信息部分） [Downloads.zip](https://github.com/xcanwin/KeepChatGPT/files/11500609/Downloads.zip)

可惜保存的js是失效的，没有记录到。

**Comment by yige-yigeren** [comment]
> > > 你的plus账号勾选净化首页并点击New chat后，也是这样的吗？ ![首页](https://github.com/xcanwin/KeepChatGPT/raw/main/assets/index_light.png)
> > 
> > 
> > 最近有一次UI更新 ![image](https://user-images.githubusercontent.com/53390868/239016381-fed2e888-7b3b-4151-9a14-c05e08d6df0a.png) 我这有一份直接另存为的网页文件，希望能有帮助（我删除了我能找到的个人信息部分） [Downloads.zip](https://github.com/xcanwin/KeepChatGPT/files/11500609/Downloads.zip)
> 
> 可惜保存的js是失效的，没有记录到。

需要哪一个js？我去下载

**Comment by xcanwin** [comment]
> > > > 你的plus账号勾选净化首页并点击New chat后，也是这样的吗？ ![首页](https://github.com/xcanwin/KeepChatGPT/raw/main/assets/index_light.png)
> 
> > > 
> 
> > > 
> 
> > > 最近有一次UI更新 ![image](https://user-images.githubusercontent.com/53390868/239016381-fed2e888-7b3b-4151-9a14-c05e08d6df0a.png) 我这有一份直接另存为的网页文件，希望能有帮助（我删除了我能找到的个人信息部分） [Downloads.zip](https://github.com/xcanwin/KeepChatGPT/files/11500609/Downloads.zip)
> 
> > 
> 
> > 可惜保存的js是失效的，没有记录到。
> 
> 
> 
> 需要哪一个js？我去下载

js文件有，但是另存为的网页的缺陷，它只记录了另存为那一瞬间的样子，类似于截图，你可以点击你保存的网页的左下角的用户名，是不是不像官网那样弹出设置菜单

**Comment by yige-yigeren** [comment]
> > > > > 你的plus账号勾选净化首页并点击New chat后，也是这样的吗？ ![首页](https://github.com/xcanwin/KeepChatGPT/raw/main/assets/index_light.png)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 最近有一次UI更新 ![image](https://user-images.githubusercontent.com/53390868/239016381-fed2e888-7b3b-4151-9a14-c05e08d6df0a.png) 我这有一份直接另存为的网页文件，希望能有帮助（我删除了我能找到的个人信息部分） [Downloads.zip](https://github.com/xcanwin/KeepChatGPT/files/11500609/Downloads.zip)
> > 
> > 
> > > 
> > 
> > 
> > > 可惜保存的js是失效的，没有记录到。
> > 
> > 
> > 需要哪一个js？我去下载
> 
> js文件有，但是另存为的网页的缺陷，它只记录了另存为那一瞬间的样子，类似于截图，你可以点击你保存的网页的左下角的用户名，是不是不像官网那样弹出设置菜单

作者是没有plus对吧，我可以借一下账户
能留个邮箱吗？
