### ISSUE TITLE
建议提供关闭“专属金标”或者关闭动画的选项

### ISSUE THREAD

**Issue by Kaiyiwing** [xcanwin/KeepChatGPT#17]

**Comment by tckwgd** [comment]
确实，看着很碍眼，还是动态的

**Comment by 14790897** [comment]
将loadmenu函数的调用注释掉即可

**Comment by 14790897** [comment]
> 

这样做会有一些问题，大家不要使用这个方法

**Comment by enerai** [comment]
我倒是觉得金标挺好的。。至少知道脚本是否成功加载了。。

**Comment by hhelibeb** [comment]
> 将loadmenu函数的调用注释掉即可

注释下面的样式比较安全，
@keyframes shine {
    from {
        transform: translateX(-50%) translateY(-50%) rotate(-45deg);
    }
    to {
        transform: translateX(150%) translateY(150%) rotate(-45deg);
    }
}

**Comment by xhxgit** [comment]
动画影响感觉挺大的，容易分散注意力

**Comment by Linkegee** [comment]
> 

亲测有效！感谢！！！

**Comment by Linkegee** [comment]
> > 将loadmenu函数的调用注释掉即可
> 
> 注释下面的样式比较安全，
> 
> ```
> @keyframes shine {
>     from {
>         transform: translateX(-50%) translateY(-50%) rotate(-45deg);
>     }
>     to {
>         transform: translateX(150%) translateY(150%) rotate(-45deg);
>     }
> }
> ```

亲测有效！！感谢！！

**Comment by Soarse** [comment]
> 

测试有效，不再闪烁了，非常感谢。

**Comment by xixiaxixi** [comment]
没。我觉的金标很帅。本来黑色的，加个金标很漂亮（顺便的，我开了PLUS）

**Comment by wanzhiyu** [comment]
能不能提供关闭动画的选项，静态的没啥

**Comment by xcanwin** [comment]
谢谢反馈，最新版已添加取消动画功能
