### ISSUE TITLE
没有开净化，为啥要强制隐藏底部的说明呢？

### ISSUE THREAD

**Issue by Sostay** [xcanwin/KeepChatGPT#170]
![image](https://user-images.githubusercontent.com/6897274/236472391-cfc1b99d-1bb9-4db3-85a2-d68de155255e.png)
下面那行字有版本信息，希望只在净化模式下隐藏。不需要净化功能的还是希望不要修改原版的体验~，感谢大佬！

**Comment by Captpricelsy** [comment]
+1，本来我是通过看底下ChatGPT XXX Version来检查有没有更新，现在消失了有些影响体验

**Comment by CurtisWong458** [comment]
的确太垃圾了，还不如关了这份脚本。本来就是为了解决报错问题的，居然还去掉原有的！！！

**Comment by Sostay** [comment]
> 的确太垃圾了，还不如关了这份脚本。本来就是为了解决报错问题的，居然还去掉原有的！！！

也不能这么说😂，反馈一下就好，看看作者有没有空搞一下~

**Comment by Ezra-Chan** [comment]
可以先注掉脚本的第716行：mainBottom.remove();

**Comment by Ezra-Chan** [comment]
> 也不能这么说😂，反馈一下就好，看看作者有没有空搞一下~

从11.13开始，不开启“净化页面”功能时，底部信息会保留
