### ISSUE TITLE
Move kcg button to nav footer

### ISSUE THREAD

**Issue by neoOpus** [xcanwin/KeepChatGPT#171]
Hi,

I am trying to make the button get added to footer of the nav but I wasn't able to figure out how to do it... if you can help me that would be great as I am trying to see if this would fix the conflict with some other extensions....

**Comment by xcanwin** [comment]
Hello, I prefer the top left corner, like the macbook apple

**Comment by xcanwin** [comment]
我对这类行为感到不喜欢，其他插件的问题请让其他插件解决

**Comment by neoOpus** [comment]
我明白，你是对的！

**Comment by xcanwin** [comment]
我已经看到很多chatgpt侧边栏插件作者都在抗议某拓展的霸道行为。
为此我贡献一点微薄的力量，解决了这个共存的问题。
请大家升级到keepchatgpt最新版，我已经实现了让99%以上的插件都可以友好共存的功能。
