### ISSUE TITLE
Hope to be tiny and beautiful

### ISSUE THREAD

**Issue by anonymouscnuser** [xcanwin/KeepChatGPT#173]
首先感谢作者大大提供了这样一款插件
我也深知项目不发展早晚会死的道理

这只是个人抱怨罢了，可以说我很自私，喷就喷吧，认了，但我喜欢发泄

当初是为了寻求一款保持session的插件罢了，仅仅如此

**Comment by xcanwin** [comment]
发展需要精力、技术、时间和开源社区的支持。
项目是永存的，每一个项目站起来就是为了传递开源的意志，让伸手党总有一天成为创造党造福大家。
曾经的我也是伸手党，曾经的我也和你一样发发牢骚。不过我相信看到这个消息的你或者其他人，在以后的某个时间里会创造好东西共享给大家的。
