### ISSUE TITLE
菜单悬浮异常

### ISSUE THREAD

**Issue by xbq-richard** [xcanwin/KeepChatGPT#175]
[鼠标放置在金标处能够弹出菜单，但是当我鼠标想要移至菜单时，菜单就会突然消失]

**Comment by Cx330-502** [comment]
same issue #136

**Comment by xbq-richard** [comment]
This is an automatic reply email from QQ mailbox.I have received your email, I will reply it as soon as possible.Best wishes ：）

**Comment by Cx330-502** [comment]
> same issue #136 

my solution is to just press key F12，and then  the problem can be served for i will have enough time to click the button i need

**Comment by xcanwin** [comment]
1、F12，在控制台执行命令```$(".kmenu").style.display = 'block' ```
![图片](https://github.com/xcanwin/KeepChatGPT/assets/14187349/d507de5e-e917-496d-b565-cb2289ce921d)
2、然后，你会看到菜单栏被召唤出来
3、然后，在查看器里搜索```div.kmenu```，把鼠标移动到下面那个```::before```那里，然后截图发给我看看：
![图片](https://github.com/xcanwin/KeepChatGPT/assets/14187349/e09fccec-9645-4e7a-9de4-5f0c3904a0eb)

**Comment by WindustH** [comment]
有同样的问题 鼠标一挪开菜单就消失

**Comment by xcanwin** [comment]
> 有同样的问题 鼠标一挪开菜单就消失

按照上面的步骤截图给我

**Comment by xcanwin** [comment]
看起来没问题的，你鼠标移到左上角的logo上，出现菜单以后，慢慢向右移动到菜单上面就好了。

**Comment by WindustH** [comment]
https://github.com/xcanwin/KeepChatGPT/assets/49442360/1eac9cda-810f-48c0-9e1b-dd05379c0e2d

**Comment by xcanwin** [comment]
> 
> 
> https://github.com/xcanwin/KeepChatGPT/assets/49442360/1eac9cda-810f-48c0-9e1b-dd05379c0e2d
> 
> 
> 
> 

我刚升级了一版，调整了维持悬停的像素，你试试

**Comment by WindustH** [comment]
并不行 但F12开发者工具打开后就不会莫名消失了
很怪 浏览器是最新版的edge

**Comment by xcanwin** [comment]
> 并不行 但F12开发者工具打开后就不会莫名消失了
> 
> 很怪 浏览器是最新版的edge

提供更多信息给我，浏览器具体版本截图，浏览器当前放大比例是不是正常比例（100%）？屏幕分辨率多少x多少？windows系统？

**Comment by Speike-SHL** [comment]
我也是这样，按了F12就不会消失，不按的话不管浏览器放大比例是多少都会消失，电脑系统Win11，分辨率2560x1440，Microsoft Edge 版本 120.0.2210.77 (正式版本) (64 位)

**Comment by xbq-richard** [comment]
This is an automatic reply email from QQ mailbox.I have received your email, I will reply it as soon as possible.Best wishes ：）

**Comment by Zeus3024** [comment]
![image](https://github.com/xcanwin/KeepChatGPT/assets/134196593/861451e6-8f2e-495c-a581-93d670e0c4b9)
浏览器为谷歌121版本，比例为100%，屏幕分辨率2560*1600，win10 22H2
![image](https://github.com/xcanwin/KeepChatGPT/assets/134196593/c1b25e40-7169-4ada-97f5-459e5cecca36)

**Comment by xbq-richard** [comment]
This is an automatic reply email from QQ mailbox.I have received your email, I will reply it as soon as possible.Best wishes ：）

**Comment by xcanwin** [comment]
已更新UI

**Comment by xbq-richard** [comment]
This is an automatic reply email from QQ mailbox.I have received your email, I will reply it as soon as possible.Best wishes ：）
