### ISSUE TITLE
与superpower-chatgpt插件冲突，覆盖左侧会话历史

### ISSUE THREAD

**Issue by wanzhiyu** [xcanwin/KeepChatGPT#178]
我正在使用https://github.com/saeedezzati/superpower-chatgpt 管理我的会话历史，但是我发现KeepChatGPT同时使用时，左侧会话历史会完全消失。请问是否可以调整代码避开这种冲突。
单独使用superpower-chatgpt：
![image](https://github.com/xcanwin/KeepChatGPT/assets/18503895/bf596fc8-2da7-4dc7-b0d0-6cdf94213ad7)

两插件同时使用后：
![image](https://github.com/xcanwin/KeepChatGPT/assets/18503895/c1cf2c08-fe9b-41db-9dba-83a87759b040)

**Comment by wanzhiyu** [comment]
请问是否可以允许用户把KeepChatGPT的按钮放在其他位置，例如左侧栏的右下方的一个小按钮，但是不要放在左侧栏内

**Comment by COPELONG** [comment]
我也遇到了这种情况，请问怎么修改代码，才能移动keepgpt位置，或者加一个功能：用户可以自己选择位置，谢谢作者。

**Comment by wanzhiyu** [comment]
> 中肯的说： 我是基于定位追加的按钮，我与其他插件是共存的。 他是重写侧边栏，其他插件无法参与被重写的侧边栏。

那能否允许用户不放在侧边栏，比如放在右上角或者左上角某个角落的浮动窗口，允许用户不依赖于侧边栏定位，不用的时候就不显示

**Comment by xcanwin** [comment]
> > 中肯的说： 我是基于定位追加的按钮，我与其他插件是共存的。 他是重写侧边栏，其他插件无法参与被重写的侧边栏。
> 
> 
> 
> 那能否允许用户不放在侧边栏，比如放在右上角或者左上角某个角落的浮动窗口，允许用户不依赖于侧边栏定位，不用的时候就不显示

不认同个别插件破坏侧边栏让所有插件无容身之所的行为。这导致你这样的意见需要向每一个gpt插件issue提交。

**Comment by wanzhiyu** [comment]
> > > 中肯的说： 我是基于定位追加的按钮，我与其他插件是共存的。 他是重写侧边栏，其他插件无法参与被重写的侧边栏。
> > 
> > 
> > 那能否允许用户不放在侧边栏，比如放在右上角或者左上角某个角落的浮动窗口，允许用户不依赖于侧边栏定位，不用的时候就不显示
> 
> 不认同个别插件破坏侧边栏让所有插件无容身之所的行为。这导致你这样的意见需要向每一个gpt插件issue提交。

这种改写侧边栏的插件不会很多的，要想实现它这种文件夹的功能，可能改写侧边栏也是不得已的行为，或者您有没有推荐的其他可以实现chat folder功能的插件哈，我可以改用其他插件

**Comment by xcanwin** [comment]
> > > > 中肯的说： 我是基于定位追加的按钮，我与其他插件是共存的。 他是重写侧边栏，其他插件无法参与被重写的侧边栏。
> 
> > > 
> 
> > > 
> 
> > > 那能否允许用户不放在侧边栏，比如放在右上角或者左上角某个角落的浮动窗口，允许用户不依赖于侧边栏定位，不用的时候就不显示
> 
> > 
> 
> > 不认同个别插件破坏侧边栏让所有插件无容身之所的行为。这导致你这样的意见需要向每一个gpt插件issue提交。
> 
> 
> 
> 这种改写侧边栏的插件不会很多的，要想实现它这种文件夹的功能，可能改写侧边栏也是不得已的行为，或者您有没有推荐的其他可以实现chat folder功能的插件哈，我可以改用其他插件

中肯的说，我希望你建议那个开发者，可以新建一个小窗口做这个聊天拖拉的功能的，用户拖拉完点击保存，结果展示在侧边栏，这样不会影响其他插件。它当前的做法是为了直接"拖拉"而重写了侧边栏，我觉得可以间接"拖拉"。
改写侧边栏的插件非常多，大概80%以上。

**Comment by xcanwin** [comment]
最小化的改动界面，才能保证用户可以同时选择多种插件。

**Comment by neoOpus** [comment]
https://github.com/xcanwin/KeepChatGPT/issues/153#issuecomment-1543225636

**Comment by wanzhiyu** [comment]
> 我已经看到很多chatgpt侧边栏插件作者都在抗议某拓展的霸道行为。 为此我贡献一点微薄的力量，解决了这个共存的问题。 请大家升级到keepchatgpt最新版，我已经实现了让99%以上的插件都可以友好共存的功能。

可能是我误会了您的意思，目前似乎还是和 [superpower-chatgpt](https://github.com/saeedezzati/superpower-chatgpt) 不兼容，侧边栏无法共存。

**Comment by xcanwin** [comment]
你更新keepchatgpt到版本12.9后会发现greasyfork上所有chatgpt插件终于能和你提到的拓展都相互共存了。

**Comment by wanzhiyu** [comment]
> 你更新keepchatgpt到版本12.9后会发现greasyfork上所有chatgpt插件终于能和你提到的拓展都相互共存了。

我启用更新发现最新版本是12.8，没有到12.9，还是不能共存，是因为Greasyfork有延迟吗？

**Comment by wanzhiyu** [comment]
> 你更新keepchatgpt到版本12.9后会发现greasyfork上所有chatgpt插件终于能和你提到的拓展都相互共存了。

我好像明白了，侧边栏会强行启用openai的原始样式，[superpower-chatgpt](https://github.com/saeedezzati/superpower-chatgpt)的自定义侧边栏会不显示，请问这是预期的现象吗？

**Comment by wanzhiyu** [comment]
> 用词不对，是你提到的拓展破坏了原始样式，使得所有chatgpt侧边栏插件都无法正常显示和使用。我的修复方案是：恢复侧边栏openai的原始样式，保障大部分插件都能相互友好共存，这是预期的现象。

好的，我会继续向开发者反馈，路人如果看到这一点，可以去[superpower-chatgpt](https://github.com/saeedezzati/superpower-chatgpt)扩展的discord反馈（https://discord.com/channels/1083455984489476220/1106222933447299133）。我理解您作为开发者付出的心血，感谢您的贡献！
