### ISSUE TITLE
 GET https://chat.openai.com/api/auth/session 429 请问我改如何解决这个问题？

### ISSUE THREAD

**Issue by qinfeng0214** [xcanwin/KeepChatGPT#180]
我尝试过清除缓存、更换节点，我的免费额度并没有使用完。
![QQ图片20230511005301](https://github.com/xcanwin/KeepChatGPT/assets/51642121/976f9c65-5416-4518-88af-95dbca5a7811)

**Comment by xcanwin** [comment]
运气不好两个节点都被风控，继续换节点
