### ISSUE TITLE
使用了插件网络错误更加频繁

### ISSUE THREAD

**Issue by wwjj999** [xcanwin/KeepChatGPT#183]
最近的几个版本插件使用后发现GPT报网络错误更加频繁，无论怎么调整间隔都无效。同样浏览器，同样的网络环境下，浏览器隐身模式将不再调用任何插件，此时GPT反而不再经常报网络错误。再次说明，完全一样的环境下，只要开浏览器隐身模式，一切安稳。所以问题会是在哪里？非常困惑，望指导。

**Comment by xcanwin** [comment]
隐私模式把一些cf存储的备注信息和cookie都重置了，有时候cf存储的那些信息反而是过时的，通过清空openai.com所有的信息刚好清理了那些过时的信息。
报错信息具体情况具体分析，大部分的报错我都科普在了readme。

**Comment by wwjj999** [comment]
所以该如何解决？



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月13日 01:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xcanwin/KeepChatGPT] 使用了插件网络错误更加频繁 (Issue #183) |

隐私模式把一些cf存储的备注信息和cookie都重置了，有时候cf存储的那些信息反而是过时的，通过清空openai.com所有的信息刚好清理了那些过时的信息。
报错信息具体情况具体分析，大部分的报错我都科普在了readme。

**Comment by xcanwin** [comment]
增间隔，换节点

**Comment by wwjj999** [comment]
都做个，毫无作用啊



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月13日 15:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xcanwin/KeepChatGPT] 使用了插件网络错误更加频繁 (Issue #183) |

增间隔，换节点

**Comment by xcanwin** [comment]
看看报错截图
