### ISSUE TITLE
和插件“superpower for chatGPT”冲突

### ISSUE THREAD

**Issue by gemini4545** [xcanwin/KeepChatGPT#185]
浏览器：firefox （the latest version）
系统环境：ubuntu 20.04 
问题：
在安装了superpower-chatGPT（来自firefox插件商城）后，左侧历史对话栏里的内容消失，记录是在的但无法显示。停用tampermokey后，恢复正常，启用后又如此。但有时候又可以显示，不过头部几行明显有被遮挡的迹象，感觉像是哪里有冲突。

附上另一个插件项目：[saeedezzati ](https://github.com/saeedezzati)/
[superpower-chatgpt](https://github.com/saeedezzati/superpower-chatgpt)

**Comment by longxiaotian799** [comment]
我也是这样的

**Comment by neoOpus** [comment]
https://github.com/xcanwin/KeepChatGPT/issues/153#issuecomment-1543225636

**Comment by 576272658** [comment]
windows 11
chrome和edge浏览器都有同样的问题，目前只能两个插件选一个开启，同时开启就会有bug

**Comment by gemini4545** [comment]
> 

那看来不是浏览器的问题，这两个插件或其依赖可能哪里有冲突。superpower那边不让提issue，没办法反应

**Comment by chenyunxuan001** [comment]
我也遇到了这个情况.
![image](https://github.com/xcanwin/KeepChatGPT/assets/132529357/7f05c7ec-cf03-4ca5-822a-8ba98ba383df)

**Comment by gemini4545** [comment]
> 我也遇到了这个情况. ![image](https://user-images.githubusercontent.com/132529357/238256516-7f05c7ec-cf03-4ca5-822a-8ba98ba383df.png)

对，就是这种情况，要么停用tampermokey插件，刷新后左侧栏能显示出superpower的分类文件列表；要么停用superpower插件，刷新后左侧恢复正常。

不知如何解决冲突。目前我只能二选一

**Comment by xcanwin** [comment]
我已经看到很多chatgpt侧边栏插件作者都在抗议某拓展的霸道行为。
为此我贡献一点微薄的力量，解决了这个共存的问题。
请大家升级到keepchatgpt最新版，我已经实现了让99%以上的插件都可以友好共存的功能。

**Comment by gemini4545** [comment]
> 我已经看到很多chatgpt侧边栏插件作者都在抗议某拓展的霸道行为。 为此我贡献一点微薄的力量，解决了这个共存的问题。 请大家升级到keepchatgpt最新版，我已经实现了让99%以上的插件都可以友好共存的功能。

原来是某插件的行为所知，怪不得那边不让提issue。
感谢作者！目前能用了！

**Comment by yzy-1995** [comment]
> > 
> 
> 那看来不是浏览器的问题，这两个插件或其依赖可能哪里有冲突。superpower那边不让提issue，没办法反应

老外开发的插件，这么蛮横不讲理啊！

**Comment by 576272658** [comment]
非常感谢，更新到最新12.9版本以后显示已经正常了。就是还有一个小小的问题，开启以后superpower的My Prompt History功能和Community Prompts功能会消失。

> 我已经看到很多chatgpt侧边栏插件作者都在抗议某拓展的霸道行为。 为此我贡献一点微薄的力量，解决了这个共存的问题。 请大家升级到keepchatgpt最新版，我已经实现了让99%以上的插件都可以友好共存的功能。

**Comment by gemini4545** [comment]
刚更新完好了，现在好像又不行了，左侧栏内容又消失了。我现在都停用superpower了，本来觉得它是个好东西，但这么霸道的做法，有点让人抵触，不符合开源精神~~


> 非常感谢，更新到最新12.9版本以后显示已经正常了。就是还有一个小小的问题，开启以后superpower的My Prompt History功能和Community Prompts功能会消失。
> 
> > 我已经看到很多chatgpt侧边栏插件作者都在抗议某拓展的霸道行为。 为此我贡献一点微薄的力量，解决了这个共存的问题。 请大家升级到keepchatgpt最新版，我已经实现了让99%以上的插件都可以友好共存的功能。

**Comment by 576272658** [comment]
> 刚更新完好了，现在好像又不行了，左侧栏内容又消失了。我现在都停用superpower了，本来觉得它是个好东西，但这么霸道的做法，有点让人抵触，不符合开源精神~~
> 
> > 非常感谢，更新到最新12.9版本以后显示已经正常了。就是还有一个小小的问题，开启以后superpower的My Prompt History功能和Community Prompts功能会消失。
> > > 我已经看到很多chatgpt侧边栏插件作者都在抗议某拓展的霸道行为。 为此我贡献一点微薄的力量，解决了这个共存的问题。 请大家升级到keepchatgpt最新版，我已经实现了让99%以上的插件都可以友好共存的功能。

太讨厌了，我也打算停用了，不给评论还那么霸道，也不是什么非用不可的功能

**Comment by wanzhiyu** [comment]
它没有github反馈，但是有discord。https://discord.gg/fADPRFsgTk

**Comment by neoOpus** [comment]
I've made a sort of fix and a PR, wait for it after [xcanwin](https://github.com/xcanwin) reviews and merge it.

**Comment by xcanwin** [comment]
> I've made a sort of fix and a PR, wait for it after [xcanwin](https://github.com/xcanwin) reviews and merge it.

这是因为superpower改动侧边栏太多地方导致大部分的chatgpt侧边栏插件无法正常运行，这是superpower的bug，我知道他是能解决的，这对他来说太简单了。你应该向superpower提议让他改动少点，而不是让其他插件配合它的bug。明明是它存在bug，你却提议让其他插件不启动或者晚一点启动，这样很过分，以后所有插件的作者每天都要先看superpower的changlog再开发自己的代码。
