### ISSUE TITLE
有没有可能解决节点不稳的问题，绕过对ip污染的限制

### ISSUE THREAD

**Issue by NsLearning** [xcanwin/KeepChatGPT#19]
节点不稳，老出现这个，有点烦。大佬能不能想想办法！
Access denied
You do not have access to chat.openai.com.

The site owner may have set restrictions that prevent you from accessing the site.

**Comment by xcanwin** [comment]
不是ip问题。可能是同一个手机号重复测试，或者是发送过比较多次违规内容。

**Comment by NsLearning** [comment]
> 不是ip问题。可能是同一个手机号重复测试，或者是发送过比较多次违规内容。

不是啊 国外很多这种问题 就个人号没问几次，确实是ip问题

**Comment by 14790897** [comment]
> > 不是ip问题。可能是同一个手机号重复测试，或者是发送过比较多次违规内容。
> 
> 不是啊 国外很多这种问题 就个人号没问几次，确实是ip问题

如果改变自己ip，那么对方会把信息发给错误的ip，所以想解决这个问题还是得换节点
