### ISSUE TITLE
能解决“一个时间只能问一个问题”的问题吗

### ISSUE THREAD

**Issue by cyrilyoung** [xcanwin/KeepChatGPT#190]
如题，谢谢大佬

**Comment by DmLeaves** [comment]
原则上来说不行的吧，这是向后端请求数据时遇到的错误返回的结果。

**Comment by xcanwin** [comment]
我觉得，在算力紧张，相同资源的情况下，一个人同时问两个问题可以让一个人满意，而两个人各问一个问题可以让两个人满意，openai倾向于后者。

**Comment by cyrilyoung** [comment]
同一个账号有两个人同时在用，有可能会同时发出问题，就会出现报错
