### ISSUE TITLE
屏蔽数据监管失效了！！！

### ISSUE THREAD

**Issue by BanLuSAMA** [xcanwin/KeepChatGPT#192]
5月16日开始的，通过屏蔽本地的那个/moderations的办法失效了

**Comment by Voids0713** [comment]
给作者提供一点线索，这是因为conversion的request body里多了一项supports_modapi = true，只要在send request之前把body里的这一项改成false即可。

**Comment by aaaadj** [comment]
楼上的线索我用了,我改了下脚本,确实可以屏蔽数据监管,但是整体上来说没有意义了,据我的观察整个模型都换了,3.5的道德准则啥的提到了和4一个级别甚至更高,屏蔽监管了你聊两句也是直接中断对话.包括api都一样,所以我能肯定的说是模型大调整了.
只能说道德委员会搞事情,以后这样根本不想用gpt了.

**Comment by Voids0713** [comment]
> 楼上的线索我用了,我改了下脚本,确实可以屏蔽数据监管,但是整体上来说没有意义了,据我的观察整个模型都换了,3.5的道德准则啥的提到了和4一个级别甚至更高,屏蔽监管了你聊两句也是直接中断对话.包括api都一样,所以我能肯定的说是模型大调整了. 只能说道德委员会搞事情,以后这样根本不想用gpt了.

我对tamper monkey不是很熟，能分享一下改的脚本不？

**Comment by xcanwin** [comment]
取消审计功能已修复，总觉得你们在飙车而我又没有证据。少飙车，对身体和账号都好。

**Comment by BanLuSAMA** [comment]
今天屏蔽本地的/moderations的办法又可以用了，不知道为什么
