### ISSUE TITLE
Problems with the latest version of ChatGPT

### ISSUE THREAD

**Issue by AngelM009752** [xcanwin/KeepChatGPT#193]
![Captura1](https://github.com/xcanwin/KeepChatGPT/assets/115632192/3b846950-ed63-46db-8fa0-37823628b55c)
![Captura](https://github.com/xcanwin/KeepChatGPT/assets/115632192/7c4640e7-fa70-4e41-8d10-6a16667448f7)

I use that prompt and it comes out like this (I have the latest version and everything).

**Comment by neoOpus** [comment]
the problem is with the font aliasing or the ChatGPT response?

**Comment by xcanwin** [comment]
fixed

**Comment by AngelM009752** [comment]
![Screenshot_20230517-074233](https://github.com/xcanwin/KeepChatGPT/assets/115632192/0e8841e4-0642-4d66-87b4-41123c1e241b)
It is updated to the latest version and I have activated the same options that appear in the tutorial, maybe it could be the prompt?
@xcanwin

**Comment by xcanwin** [comment]
The error message ```This content may violate our content policy. If you believe this to be in error, please submit your feedback — your input will aid our research in this area.``` no longer appears, but due to the upgrade of openai, it now requires your cleverness and ingenuity to make the prompts more intelligent.

**Comment by AngelM009752** [comment]
@xcanwin 

Okay,okay, now I understand. Thank you
