### ISSUE TITLE
界面可以优化下吗？大屏可以自己设置宽度吗？目前太宽了看起来不舒服，谢谢

### ISSUE THREAD

**Issue by Fmaem** [xcanwin/KeepChatGPT#197]
默认的宽度和页面不太像是聊天，麻烦作者把左侧栏和问答界面调整的居中一点，宽度到两端看着很不舒服啊，十分感谢。

**Comment by xcanwin** [comment]
我还想再靠左一点，越宽越好，这样chatgpt在回答代码的时候我就要求不用左右移动代码框了，而且可以减少上下滚动。
刚刚我看了一下微信聊天，我觉得微信好友在聊天的时候他的头像比目前的展示大屏的头像还靠左边，微信好友列表的头像也很靠近左侧。

**Comment by Fmaem** [comment]
我已经看到您的回复，大家的喜好各不相同，建议左右边界可以自己设置
