### ISSUE TITLE
感谢作者，能稍微加个export吗

### ISSUE THREAD

**Issue by aofowe** [xcanwin/KeepChatGPT#198]
俺码力有限。。有参考https://github.com/ryanschiang/chatgpt-export 这位大大输出md
但是，好像和 "言无不尽" 功能冲突了。 勾选了“言无不尽”  会漏部分回复 自己也看不懂细节debug不了 哭哭
方便的话加下。。不方便先暂时不用言无不尽了。。。
感谢作者辛勤付出

**Comment by xcanwin** [comment]
😂大家想要的太多，看到大家提出了很多提升自己效率的需求，代码写不完，作者会慢慢迭代

**Comment by aofowe** [comment]
> 😂大家想要的太多，看到大家提出了很多提升自己效率的需求，代码写不完，作者会慢慢迭代

嗯嗯， 加油～ 先前就是不想当白嫖党才想自己解决 捂脸
有时间开发您觉得重要的叭
有很多第三方插件 看不到源代码都不敢用 不是账号被封就是资料被白嫖去第三方
