### ISSUE TITLE
这个插件能不能用到第三方网站上啊！

### ISSUE THREAD

**Issue by 17860839167** [xcanwin/KeepChatGPT#201]
我的普通版的被block了，说是换坤点才行，但是我的666只有三个，换了一个别的666也不行。所以只能用第三方的玩，但是这个插件好像只会在打开官网的才启动，第三方的没反应，所以有没有大佬能改一下这个啊😭😭纯纯文科生一点都看不明白

**Comment by Ezra-Chan** [comment]
第三方也是同样的样式吗，是的话把第47行代码改下
`// @match             https://chat.openai.com/*`
把域名换成第三方的就行

**Comment by Ezra-Chan** [comment]
那可能结构被改掉了

**Comment by yige-yigeren** [comment]
> 我的普通版的被block了，说是换坤点才行，但是我的666只有三个，换了一个别的666也不行。所以只能用第三方的玩，但是这个插件好像只会在打开官网的才启动，第三方的没反应，所以有没有大佬能改一下这个啊😭😭纯纯文科生一点都看不明白

这里推荐使用[warp+](https://cloudflarewarp.com/)，如果warp+访问缓慢就套两层梯子，warp+不可能被封节点的（couldflare家的）

无限流量密钥：8T2GHy03-571R9blE-ab436y9U

**Comment by yige-yigeren** [comment]
> 我的普通版的被block了，说是换坤点才行，但是我的666只有三个，换了一个别的666也不行。所以只能用第三方的玩，但是这个插件好像只会在打开官网的才启动，第三方的没反应，所以有没有大佬能改一下这个啊😭😭纯纯文科生一点都看不明白

userjs是改网页的，第三方不可能和原版网页一样，多半不匹配，所以大概率改啥都不好使，不如走别的路
