### ISSUE TITLE
日新月异存在bug

### ISSUE THREAD

**Issue by donkeyyu** [xcanwin/KeepChatGPT#202]
Chrome浏览器最新版本，打开日新月异后，滑动左侧历史记录到底部触发更多记录的加载后，回滚到顶部时会触发undefined问题

![image](https://github.com/xcanwin/KeepChatGPT/assets/67222864/be6e998d-aac5-4819-9890-bf05d7603ff6)

**Comment by xcanwin** [comment]
你的历史聊天是不是有几十个

**Comment by lingmingyu** [comment]
我也遇到这个问题了，请作者快速修复

**Comment by jonnyzhang02** [comment]
我也遇到这个问题了，看来是个不小的问题

**Comment by badseal** [comment]
我也遇到了相同的问题。

**Comment by badseal** [comment]
![image](https://github.com/xcanwin/KeepChatGPT/assets/5166292/7d35d611-e523-4bd5-a179-989778800c21)

**Comment by donkeyyu** [comment]
> 你的历史聊天是不是有几十个

是的，历史记录有几十个，因为工作中有测试ChatGPT能力的需求，所以保留了很多长对话

**Comment by xcanwin** [comment]
我大概知道什么问题了。
大家数一下自己的历史对话有多少个，告诉我，我把自己的账号制造一样的情况来调试bug。

**Comment by badseal** [comment]
> 我大概知道什么问题了。 大家数一下自己的历史对话有多少个，告诉我，我把自己的账号制造一样的情况来调试bug。

我有13个历史对话。

**Comment by xcanwin** [comment]
已修复
