### ISSUE TITLE
日新月异功能有点鸡肋，作者大大不如加入文件夹功能，可以管理对话那种

### ISSUE THREAD

**Issue by Niuanan** [xcanwin/KeepChatGPT#206]
辛苦大佬

**Comment by KyleZZF** [comment]
![image](https://github.com/xcanwin/KeepChatGPT/assets/130675836/034e05dc-4248-4f6e-8699-0912bbcfb90d)
日新月异有UIbug，体验很差噢，辛苦大佬看看

**Comment by xcanwin** [comment]
这个ui异常的bug我大概定位出问题了，等我收集了用户反馈的信息以后修复。

**Comment by xcanwin** [comment]
我追求的是最少的页面改动，这样可以保证与其他插件的共存。一步一个脚印，在共存的情况下，一点一点迭代，增加你说的页面改动。

**Comment by yige-yigeren** [comment]
> 我追求的是最少的页面改动，这样可以保证与其他插件的共存。一步一个脚印，在共存的情况下，一点一点迭代，增加你说的页面改动。

我觉得这个问题应该可以通过自定义修改左侧栏宽度来解决，给个滑动条自己设置
同理全屏那个也比较鸡肋，点起来比较麻烦
不如试试加个可以将左边那个栏收起和打开的按钮

**Comment by wanzhiyu** [comment]
楼主说的这个需求确实很重要，文件夹管理要比显示日期更有实际价值，会大大提高会话管理的效率。如果不得不改动侧边栏，我觉得也是可以接受的。
