### ISSUE TITLE
请教下如何使用，没看明白怎么使用

### ISSUE THREAD

**Issue by 692568516** [xcanwin/KeepChatGPT#209]
1、如果访问chat.openai.com才可以，是否需要梯子才行
2、项目原理是反代官方的web页面来使用的么？还是说需要在哪里填写自己的key
3、{"detail":"Too many requests in 1 hour. Try again later."}问题

**Comment by xcanwin** [comment]
1、对，需要魔法
2、本项目完全使用openai官方服务，不会收集数据给作者，不需要key，原理是iframe代替人工刷新
3、清理浏览器缓存+等待一个小时+更换魔法
