### ISSUE TITLE
建议增加 GPT-4 3 小时内会话次数计数功能

### ISSUE THREAD

**Issue by cyrus-cai** [xcanwin/KeepChatGPT#214]
GPT-4 现在仍然有次数限制，但是官方并未提供计数功能，这就导致在高频使用时，无法估计自己使用的条数以及什么时候会触发上限，没办法很好地规划自己的提问。

如果能采纳的话，提两个产品上的小建议：
1.由于 openai 似乎在放开对话条数（有用户收到过 1 小时 30 条 GPT-4，以及曾经也有限额变化的例子），所以次数和间隔时长建议支持用户自定义
2.呈现方式上，由于考虑到时间和提问次数均为动态更新，展现原始数据可能反而让人摸不着头脑，故建议展示的字段定义为“此时此刻，我不耗时间地立即提问完，剩余的额度是几条”

一点小小的建议，若能采纳，不胜感激

**Comment by xii-kii** [comment]
另：当前 UI 并行展示的条目有点多了，是否考虑根据功能类别（或者用户可能更改的频次）进行适当的分组？如果设置条目继续增加，可能让这个产品**显得**（虽然不是事实上的）臃肿。

**Comment by ishikisiko** [comment]
对对对，希望能采纳

**Comment by xcanwin** [comment]
还没体验过plus，所以不了解很多情况。
已经存在的聊天页面可以随时切换GPT4或者3吗？
还是说首次创建聊天（New Chat页面）时才可以选择GPT4或者3吗？
你们怎么分别当前的聊天页面是GPT4或者3？

**Comment by ishikisiko** [comment]
只有在新建聊天的时候能选择。在点进去对话后的最上面会有显示模型。GPT-4模型具体分为默认，网页浏览，插件三个版本




&nbsp;


Schr?dinger
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月23日(星期二) 下午4:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xcanwin/KeepChatGPT] 建议增加 GPT-4 3 小时内会话次数计数功能 (Issue #214)





 
还没体验过plus，所以不了解很多情况。
 已经存在的聊天页面可以随时切换GPT4或者3吗？
 还是说首次创建聊天（New Chat页面）时才可以选择GPT4或者3吗？
 你们怎么分别当前的聊天页面是GPT4或者3？

**Comment by Soul-Player-Liu** [comment]
震惊，作者竟然还没体验过PLUS

**Comment by cmradix** [comment]
> 还没体验过plus，所以不了解很多情况。 已经存在的聊天页面可以随时切换GPT4或者3吗？ 还是说首次创建聊天（New Chat页面）时才可以选择GPT4或者3吗？ 你们怎么分别当前的聊天页面是GPT4或者3？
在聊天界面的顶端会有个条显示model:gpt3.5turbo或者model:gpt-4，GPT-4次数满后会有一个提示“You've reached the current usage cap for GPT-4. You can continue with the default model now, or try again after 具体时间，切换到GPT-3.5按钮”，这个具体时间应当是从第一个提示发出开始算的，比如我在1点发出第一个提示在2:30分发出最后一个提示消耗完所有次数，此时距离限制重置则还剩30分钟。另外有一个有趣的地方在于，虽然官方没有提供在解除限制从3.5切回4的按钮，但是用户可以通过控制台重新回到GPT-4下，具体操作方法为复制最后一次发送的conversation为fetch，然后修改其中中的"model\":\"text-davinci-002-render-sha\"部分改为"model\":\"gpt-4\"，将整个代码块复制在chrome系浏览器的控制台中粘贴并回车发送，稍等片刻后刷新页面即可。（firefox的操作流程不一样，不能照搬）
