### ISSUE TITLE
如何关闭和卸载插件

### ISSUE THREAD

**Issue by LuyuZhang00** [xcanwin/KeepChatGPT#216]
没有找到卸载的入口，只有重新安装？
![image](https://github.com/xcanwin/KeepChatGPT/assets/67768263/6b4e85ae-d713-461d-bbd7-6a25b8991850)

**Comment by Ezra-Chan** [comment]
油猴的管理面板操作列中有删除按钮

**Comment by xcanwin** [comment]
标题可以改改：如何教会一个ai行业的it人员在假装chatgpt和百度没有答案的情况下发起issue。

**Comment by xcanwin** [comment]
不要发起这种消极又低级又不符合你技术能力的issue
