### ISSUE TITLE
建议开设一个“功能投票”网页，统计大家最迫切的需求

### ISSUE THREAD

**Issue by wanzhiyu** [xcanwin/KeepChatGPT#217]

**Comment by PreWisdom** [comment]
如果你付费的话倒是可以考虑，白嫖还嫖成贵宾我是头一次见

**Comment by wanzhiyu** [comment]
> 如果你付费的话倒是可以考虑，白嫖还嫖成贵宾我是头一次见

兄弟说话大可不必这么冲，这建议也是方便开发者和路人看看大家的想法，不想做这些功能我也完全可以理解，谁的时间都是时间，这个道理我懂，开发者付出的心血大家也都感激，如果没时间开发大不了就一直搁着呗，但是新功能的想法也可以激发下路人的灵感，倒是不用有压力。
