### ISSUE TITLE
Google Chrome运行最新版脚本每问一次会报错，具体原因是日新月异

### ISSUE THREAD

**Issue by Joshua-Guo** [xcanwin/KeepChatGPT#222]
<img width="519" alt="image" src="https://github.com/xcanwin/KeepChatGPT/assets/65481538/d8b27f31-145c-4d36-8d17-b4ee6e5fc963">

我遍历了所有情况，关闭日新月异后情况消失

**Comment by 2ndMessiah** [comment]
same

**Comment by xcanwin** [comment]
已修复

**Comment by xcanwin** [comment]
又是一个chrome与firefox标准不一致导致的bug，两个大厂没有公开/对比这种不一致的标准，只能发现一个修一个。
