### ISSUE TITLE
建议作者拯救世界,有没有办法绕过封IP,解决Block的问题!

### ISSUE THREAD

**Issue by lulu-sk** [xcanwin/KeepChatGPT#227]
如题!

**Comment by xcanwin** [comment]
魔法拯救一切。
另外有很多收集/窃取用户token的插件或者gpt网站也能缓解或者拯救，但是有风险。作者不想通过这种方式盈利，所以本项目一直没有经济来源。

**Comment by AjianYo** [comment]
属实离谱的请求，直接看呆了......
