### ISSUE TITLE
希望增加收费功能，促进作者大大的良性循环

### ISSUE THREAD

**Issue by hellodabin** [xcanwin/KeepChatGPT#229]
是否可以自动化执行输入的指令，第一条输完，自动执行第二条，以此类推，适合长文本的内容，比如写小说、做商业计划书、做内容摘录这种。

**Comment by xcanwin** [comment]
谢谢提议，收费确实会提高开发效率，相当于大家支付我用休息时间来持续开发，不过我还是会坚持免费。

**Comment by xcanwin** [comment]
你的想法再具体一点，比如这样的格式。

【想输入的内容】：
Xxxxxxxxxxxxx超大文本xxxxxx

【实际上你发出去的内容和chatgpt回复的效果】：
手动造几个对话的截图

**Comment by hellodabin** [comment]
**给ChatGPT的指令：**
（这里是一条完整的指令，不做拆分，直接输入ChatGPT文本框）帮我用英雄之旅十二阶段模型写一个故事，并列出具体的提纲。并根据提纲具体展开写内容，每部分内容不少于500字。

**ChatGPT回复：**
当然，我可以帮你写一个故事，基于英雄之旅的十二阶段模型。以下是一个基本的提纲，你可以根据它来展开写内容：

平凡生活：介绍主人公的日常生活，描述他们的普通世界和平凡的生活状态。
呼唤冒险：主人公收到了一个神秘的呼唤或者遭遇到突如其来的危机，打破了平凡的生活状态。
拒绝冒险：主人公一开始对冒险抱有犹豫和拒绝的态度，担心风险和未知。
遇到导师：主人公遇到一位具有智慧和经验的导师，导师鼓励主人公并提供指导。
跨越门槛：主人公下定决心，跨越进入冒险之中的门槛，离开他们的普通世界。
实战挑战：主人公面临一系列的实战挑战，他们学习并适应新环境，战胜障碍。
盟友与敌人：主人公遇到了一些盟友，他们共同面对困难和敌人，建立起互助关系。
逐渐失去：主人公在冒险中逐渐失去一些重要的东西，面临困惑和挫折。
黑暗之路：主人公走上一条艰难的黑暗之路，面对内心的恐惧和考验。
转变与觉醒：主人公经历一次重要的转变或觉醒，找到内心的力量和智慧。
战胜敌人：主人公利用他们的新力量和智慧，最终战胜敌人或解决冒险中的问题。
回归世界：主人公带着获得的智慧和经验回归到他们的普通世界，并将其应用于改变自己和周围的人。
现在让我们一步一步展开写内容，每部分不少于500字。

平凡生活：
主人公杰克生活在一个小镇上，过着平凡的生活。他是一名普通的上班族，每天按部就班地工作，生活规律而平淡。他住在一个小房子里，有一只可爱的宠物狗作为他唯一的伴侣。每天晚上，他都会独自坐在沙发上观看电视，渴望着一些刺激和冒险。

呼唤冒险：
一天，杰克收到一封神秘的信件，信中描述着一个古老宝藏的存在。这封信是从他已故的父亲那里寄来的，父亲曾是一名冒险家。这个消息打破了杰克的平凡生活，唤起了他心中沉睡已久的冒险激情。

拒绝冒险：
然而，杰克一开始对冒险抱有犹豫和拒绝的态度。他担心冒险带来的风险和未知，害怕离开他熟悉的生活。他想起父亲生前冒险的故事，觉得那是一个危险且不可预测的世界。

遇到导师：
正当杰克陷入犹豫不决的时候，他遇到了一位神秘的老人，名叫亚瑟。亚瑟是一位经历过许多冒险的导师，他看出了杰克内心的挣扎，并决定帮助他。亚瑟告诉杰克，只有跨出舒适区才能发现自己的真正潜力。

跨越门槛：
在亚瑟的鼓励下，杰克终于下定决心，决定迈出冒险的第一步。他放下了对未知的恐惧，离开了他的小镇，踏上了冒险之旅。他进入了一个神秘的森林，这是他离开普通世界的门槛。

（以下部分请继续发问，以便我为您提供更多内容）


**我理解存中在的问题（优化点）：** 
如果是跟上面一样，一次性的指令给ChatGPT，它会输出一个完整的答案，但是这个答案是被压缩过的。如果是一个指令一个指令的去输，得到的结果会更完善。比如把上面的指令拆分为以下几部分：
1.帮我用英雄之旅十二阶段模型写一个故事，并列出具体的提纲。
2.根据提纲之“平凡生活：介绍主人公的日常生活，描述他们的普通世界和平凡的生活状态。
”，内容不少于500字。
3.根据提纲之“呼唤冒险：主人公收到了一个神秘的呼唤或者遭遇到突如其来的危机，打破了平凡的生活状态。
”，内容不少于500字。
4. ········


**第二条指令的输出结果是：**
在一个安宁而宁静的小镇上，杰克过着平凡而简单的生活。每天早晨，他准时起床，沐浴并穿上整洁的工作服。他工作在一家小型办公室，坐在一个简陋的办公桌前，处理着琐碎的文件和报告。尽管工作平淡乏味，但杰克总是尽职尽责地完成自己的任务。

下班后，杰克回到他的小房子。那是一座舒适而温馨的居所，布置简约而温暖。他的宠物狗，一只名叫巴克的黄金猎犬，总是在门口迎接他的归来。杰克喜欢带着巴克散步，沿着小镇的街道漫步，欣赏周围美丽的风景。

晚上，杰克通常一个人坐在沙发上观看电视节目。他喜欢看各种各样的节目，从纪录片到喜剧片，一切都能引起他的兴趣。电视成了他疏解疲惫和压力的方式，让他暂时忘记平凡的生活。

然而，尽管过着平凡的生活，杰克内心深处总有一种不安和渴望。他经常幻想着冒险与刺激，渴望追寻未知的世界和发现自己真正的潜力。他曾听父亲讲述过关于冒险的故事，这些故事激发了他的好奇心和冒险的渴望。

杰克的朋友们常常不理解他的这种不安和渴望。他们认为平凡的生活已经足够幸福和安全，为什么要冒险去追求未知呢？然而，杰克的内心深处有一种强烈的渴望，他知道他不能一辈子被束缚在平凡的生活中。

然而，平凡的生活也给杰克带来一种稳定和安全感。他有亲密的朋友圈子，他们互相扶持和关心彼此。他们一起度过假期，参加派对和聚餐，给予彼此情感上的支持。这个小镇是一个紧密团结的社区，人们习惯于彼此帮助和照顾。

尽管杰克对平凡的生活感到满足，但他深知内心的渴望不会消失。每当他看到冒险的故事或听到有人讲述他们的奇遇，他心中的火焰再次被点燃。杰克明白，他需要追寻自己的梦想，勇敢地跨出舒适区，寻找真正属于他的冒险之旅。

**这样输出的内容就很丰富，而不是被压缩过的内容，但是缺点就是需要人工等待上一条执行完，才能手动输入执行下一条指令。**

**我的建议/对策：**

可不可以直接在对话框内一次性输入完整的分解指令，或者输入KeepChatGPT的插件文本框内，让插件一条条的执行指令，把指令输入到对话框，自动判断是否输出完结，如果输出完结，自动执行下一条指令，直到所有指令执行完毕。

这样的话就省事非常多，只需要在所有内容输出完后，自行手动对不完善的部分进行微调一下就可以了，绝对的生产力。
