### ISSUE TITLE
控制台报错如下，表现是需要刷新

### ISSUE THREAD

**Issue by renzhenqi** [xcanwin/KeepChatGPT#23]
KeepChatGPT: FETCH: Expire date: 2023/5/18 21:10:45
userscript.html?name=KeepChatGPT.user.js&id=d6a0eaaf-d166-4707-83ec-e0927ffb52bb:127 KeepChatGPT: FETCH: Expire date: 2023/5/18 21:10:45
_app-44807f2f4dc5abc4.js:7 TypeError: a.json is not a function
    at 264-c39b8ca802785b8a.js:1:2771
    at main-149b337e061b4d04.js:1:101106
    at Object.next (main-149b337e061b4d04.js:1:101211)
    at r (_app-44807f2f4dc5abc4.js:23:1497)
    at a (_app-44807f2f4dc5abc4.js:23:1694)
(

**Comment by xcanwin** [comment]
谢谢反馈，已在最新版本中修复。
