### ISSUE TITLE
言无不尽功能，有BUG，有时候会重头输出一次

### ISSUE THREAD

**Issue by AIgsc** [xcanwin/KeepChatGPT#230]
言无不尽功能，有BUG，有时候会重头输出一次

**Comment by AIgsc** [comment]
确实没有点击，继续输出了，有时候会出来一串英文，然后又重头开始输出了

**Comment by xcanwin** [comment]
提供一下截图，画剪头→编辑出自动继续的那些位置。
我的实现原理并没有改变网络请求，原理是自动点击chatgpt原生的继续按钮。所以大概率很可能是chatgpt原生的bug。

**Comment by AIgsc** [comment]
仔细测试了一圈，gpt本身的逻辑是超时就显示Continue generating按钮，但并不是点击按钮就一定继续生产之前的内容，大概率会重头开始。另外一个场景是当内容没有输出完，就停下来了，然后可以在输入框手动打 继续，或者是代码的时候，就打 断开处继续。都能让GPT继续之前的内容。

所以这个言无不尽功能，想要真正的有用，正确的逻辑，应该是在GPT快要超时的时候，停下来，然后帮用户自动打入继续/断开处继续。才能真正的节省操作步骤。

但我看了，，，好像GPT到底哪里停下来，没有规律、有时候跟内容的字数有关，有时候跟思考的时间有关。好像没有什么规律。

**Comment by xcanwin** [comment]
谢谢反馈，我也觉得有可以提升的地方，等我发现识别方法

**Comment by yige-yigeren** [comment]
> 提供一下截图，画剪头→编辑出自动继续的那些位置。 我的实现原理并没有改变网络请求，原理是自动点击chatgpt原生的继续按钮。所以大概率很可能是chatgpt原生的bug。

所以言无不尽可能使4.0的次数多次使用？看来我得多注意下次数了
