### ISSUE TITLE
号被ban了，有人跟我一样吗

### ISSUE THREAD

**Issue by XuZhaoTong** [xcanwin/KeepChatGPT#233]
![20230528210645](https://github.com/xcanwin/KeepChatGPT/assets/32711995/42f27e02-b79a-4a7c-a34d-34ec3c5d3d4b)
查了一下说是违法用户规则🥲

**Comment by xcanwin** [comment]
本插件很稳很安全，不过我分享几个我正在用的永远不会被封号的操作，你参考一下哪些和我不一样：
1、安全的魔法：这个不在这里推荐，选择方式就是太便宜的不要，因为太多网上邻居会影响你的账号使用。
2、安全地注册：百度注册chatgpt，自己用gmail邮箱+接短信码平台，动手去注册。
3、安全地使用：不要发太多敏感地政治地被禁止地言语给chatgpt+不要使用乱七八糟地不开源地插件和拓展+审计插件代码有没有窃取你的token+不要使用那些需要你填写token的gpt网站或者桌面软件。

**Comment by XuZhaoTong** [comment]
> 本插件很稳很安全，不过我分享几个我正在用的永远不会被封号的操作，你参考一下哪些和我不一样： 1、安全的魔法：这个不在这里推荐，选择方式就是太便宜的不要，因为太多网上邻居会影响你的账号使用。 2、安全地注册：百度注册chatgpt，自己用gmail邮箱+接短信码平台，动手去注册。 3、安全地使用：不要发太多敏感地政治地被禁止地言语给chatgpt+不要使用乱七八糟地不开源地插件和拓展+审计插件代码有没有窃取你的token+不要使用那些需要你填写token的gpt网站或者桌面软件。

代理500来块一年的，也是自己用gmail注册的，只安装了这一个油猴脚本，没有别的插件了...那可能是因为我和gpt讨论过政治？😱

**Comment by Professor-Chen** [comment]
> 最近大面积封号 只封禁plus用户 ![image](https://user-images.githubusercontent.com/24284910/241686022-ab3805f5-2df9-43ef-ab60-efd3b41206de.png) 当然我的号也被封了，目前还不知道是什么原因！

目前看到是虚拟信用卡付款的PLUS用户会被封禁，因为有很多人用这个虚拟卡进行了太多的退款白嫖操作，所以这个号段的几乎所有的PLUS用户都被封禁了，尤其是使用depay虚拟卡的PLUS用户们，这可能和5.12depay系统维护导致大部分用户没办法向卡里充钱，导致大量的PLUS用户扣款失败有关系。

**Comment by vnsnclo** [comment]
这个不是封禁，是节点问题，换个节点就好了

**Comment by yzy-1995** [comment]
> 这个不是封禁，是节点问题，换个节点就好了

这个就是封禁，openai还会发邮件退钱给你的。

**Comment by vnsnclo** [comment]
> > 这个不是封禁，是节点问题，换个节点就好了
> 
> 这个就是封禁，openai还会发邮件退钱给你的。
那为什么我也出现过，然后换了一个节点又可以用了

**Comment by vnsnclo** [comment]
> > 这个不是封禁，是节点问题，换个节点就好了
> 
> 这个就是封禁，openai还会发邮件退钱给你的。

但为什么我也出现过，然后换了一个节点又可以用了

**Comment by yzy-1995** [comment]
> > > 这个不是封禁，是节点问题，换个节点就好了
> > 
> > 
> > 这个就是封禁，openai还会发邮件退钱给你的。
> 
> 但为什么我也出现过，然后换了一个节点又可以用了

![image](https://github.com/xcanwin/KeepChatGPT/assets/24284910/d0b82399-2b60-46cc-b263-eb1311bbd15e)
你出现的是这个，而不是题主的那个

**Comment by vnsnclo** [comment]
> > > > 这个不是封禁，是节点问题，换个节点就好了
> > > 
> > > 
> > > 这个就是封禁，openai还会发邮件退钱给你的。
> > 
> > 
> > 但为什么我也出现过，然后换了一个节点又可以用了
> 
> ![image](https://user-images.githubusercontent.com/24284910/243099123-d0b82399-2b60-46cc-b263-eb1311bbd15e.png) 你出现的是这个，而不是题主的那个

不，我知道这个，但是我也出现过题主的Oops错误，很奇怪换节点之后我还能用

**Comment by yy316793** [comment]
我在淘宝找代充就是用的虚拟卡，号被封了。现在弄了个美区Apple ID找朋友的iPhone帮我代开，这种方法应该比较安全
