### ISSUE TITLE
mac端 开启大屏以后，无法关闭，插件都找不到了

### ISSUE THREAD

**Issue by daruo** [xcanwin/KeepChatGPT#235]
<img width="1308" alt="image" src="https://github.com/xcanwin/KeepChatGPT/assets/19379885/8761973d-dacb-48e5-bf50-30cbf500a883">

**Comment by yige-yigeren** [comment]
大屏无法关闭的话重新点击安装链接试试

**Comment by xcanwin** [comment]
本插件的```展示全屏```功能会在对话框上方增加一个叫```KEEP```的退出全屏按钮
