### ISSUE TITLE
打开KEEPCHATGPT后，无法使用油猴插件“ChatGPT开启不限次数的GPT4-Mobile”

### ISSUE THREAD

**Issue by MILKMILKKING** [xcanwin/KeepChatGPT#236]
最近油猴有一个ChatGPT开启不限次数的GPT4-Mobile插件，但是打开打开KEEPCHATGPT后会将那个插件出现的“GPT4-Mobile”给隐藏了。因此两个插件无法同时使用。望解决。

**Comment by xcanwin** [comment]
那个插件很强，但是它的原理影响的是服务端，类似外挂，封号可能性很大。可能下下一波封号潮就是那。但是它可能很强喜欢它的可以继续用。
这里暂时不兼容了，免得到时候用户封号跑到这里指责本插件，问了又回答只安装本插件一个，忽略自己曾经用了外挂。

**Comment by xcanwin** [comment]
已兼容

**Comment by MILKMILKKING** [comment]
> 已兼容

你好，想请问使用这个GPT4-Mobile 不会导致被封号吧？

**Comment by xcanwin** [comment]
> > 已兼容
> 
> 你好，想请问使用这个GPT4-Mobile 不会导致被封号吧？

最近有很多这个特殊功能的插件，你可以请教他们。
