### ISSUE TITLE
Please open a telegram channel and group

### ISSUE THREAD

**Issue by xenstar** [xcanwin/KeepChatGPT#237]
Since many people are using this product, I think you should open a telegram channel and group where users can share any issues quickly, and other users can learn from it. Also,, create a channel, and publish updates, once there is a significant update and we need to change some settings. 

My ChatGPT PLus account was banned 14 days ago, and I didn't get it back after the appeal. So I think once you change something, and it can significantly affect the users, you should notify them through telegram channels, as we are not checking GitHub page description often, to see what's new.

**Comment by 2ndMessiah** [comment]
2/3 of the above are imperative sentences.

PPL these days aren't familiar with "may" or "shall we" at all...

just rekt

**Comment by yzy-1995** [comment]
> Since many people are using this product, I think you should open a telegram channel and group where users can share any issues quickly, and other users can learn from it. Also,, create a channel, and publish updates, once there is a significant update and we need to change some settings.
> 
> My ChatGPT PLus account was banned 14 days ago, and I didn't get it back after the appeal. So I think once you change something, and it can significantly affect the users, you should notify them through telegram channels, as we are not checking GitHub page description often, to see what's new.

I find this unlikely, the telegram is rarely used, at least in China

**Comment by xenstar** [comment]
> I find this unlikely, the telegram is rarely used, at least in China

Most people who use proxy, they all use telegram. Without proxy, you can't use chatgpt aswell. So most technically skill people use telegram. Discord is fine too.

**Comment by yige-yigeren** [comment]
This script is not a hot update type, your tampermonkey should prompt you that there is an update, remember to check the update content when there is an update.
But we can indeed add tampermonkey to show the update brief when updating?

**Comment by xcanwin** [comment]
> Since many people are using this product, I think you should open a telegram channel and group where users can share any issues quickly, and other users can learn from it. Also,, create a channel, and publish updates, once there is a significant update and we need to change some settings.
> 
> My ChatGPT PLus account was banned 14 days ago, and I didn't get it back after the appeal. So I think once you change something, and it can significantly affect the users, you should notify them through telegram channels, as we are not checking GitHub page description often, to see what's new.

我一直很重视用户的数据安全和账户安全，所有的新功能我都是深思熟虑的，并且如果对于危险的功能我是完全不考虑新增的，所以本项目不会造成你的封号的问题，如果你被封号了，请思考是不是你发送太多违规内容、或者你的vpn风控等级比较高、或者是有人盗用你的token进行滥用、或者是你用了那种网页版chatgpt无限制使用mobile-gpt4的插件等等。
不过谢谢你的提议。
