### ISSUE TITLE
突然gpt不回答了，我以为网络问题但并不是，然后卸载插件我的页面也没有回到最初的样子毫无反应

### ISSUE THREAD

**Issue by gaziwang** [xcanwin/KeepChatGPT#238]

**Comment by ybkim1996** [comment]
我现在跟你一个问题，我也发了issue求助，尝试了电脑edge和chrome浏览器都不行，删除cookie 卸载插件 重启电脑等，手机版和浏览器隐私模式可以正常用gpt，也是今天刚想试试这个插件装完就直接空白，以为是插件需要更新卸载了发现还是啥也没有，gpt也不回答哎，头都大了
