### ISSUE TITLE
[Feature Request] 聊天菜单增加标识, 提示使用的是何种模型(3.5 / 4)

### ISSUE THREAD

**Issue by TonyYanOnFire** [xcanwin/KeepChatGPT#239]
![1685593265560](https://github.com/xcanwin/KeepChatGPT/assets/55646026/a6f459b8-3bf9-44ae-a988-b6f289a8a6b3)

**Comment by xcanwin** [comment]
已经更新了日新月异功能，你可以更新一下。
对着GPT4模型的对话发一个新消息，菜单栏就会高亮GPT-4对话。
