### ISSUE TITLE
添加对Chat.OpenAI.com按钮的中文本地化功能

### ISSUE THREAD

**Issue by pthmz** [xcanwin/KeepChatGPT#240]
你好，我是一个使用KeepChatGPT脚本的用户，同时也是中文用户。首先，非常感谢你为我们提供了修改chat.openai.com网页样式的TamperMonkey脚本，使我们在使用ChatGPT时能够更加舒适和方便。

我想提出一个建议，希望你能在脚本中添加一个功能，即将Chat.OpenAI.com网页上的按钮进行中文本地化。因为我们在日常使用ChatGPT时都是使用中文进行对话，所以将按钮也本地化为中文，可以给用户带来更好的使用体验。

具体来说，我希望像"Regenerate Response"按钮、"New Chat"按钮等等能够显示为中文，例如"重新生成回复"按钮、"新对话"按钮。这样，当我们使用ChatGPT时，界面上的按钮将与我们的对话语言保持一致，更加符合我们的使用习惯。

我相信，通过添加中文本地化功能，用户能够更快地找到所需的功能，无需额外的翻译工作，从而提高整体的使用效率和舒适度。

非常希望你能考虑这个建议，并将中文本地化功能添加到KeepChatGPT脚本中。如果需要任何帮助或反馈，请随时告知。再次感谢你的时间和努力！

最好的祝愿，
pthmz

**Comment by xcanwin** [comment]
确实是不错的想法。
不过有些插件会根据字符串Regenerate Response和字符串New Chat来定位拓展功能的按钮的，这会导致你无法使用他们的插件，当然了对本插件并不会影响，因为我不是这样定位的。

**Comment by AIgsc** [comment]
AI的味道，哈哈哈，一看就是AI写的

**Comment by yige-yigeren** [comment]
> AI的味道，哈哈哈，一看就是AI写的

不一定，有点英翻中的味道，不过英文应该是很正式的（按理来说这里不用特别正式就行），总之就是很奇怪（）

**Comment by xcanwin** [comment]
人家是非常友好的提issue方式哈哈哈
