### ISSUE TITLE
希望增加tone和style选项

### ISSUE THREAD

**Issue by EdwinWang0508** [xcanwin/KeepChatGPT#241]
可以选择输出的语气和文字风格，参考 https://github.com/saeedezzati/superpower-chatgpt

**Comment by yige-yigeren** [comment]
> 他家的插件实在不好用 谢谢作者大大！

还好吧，谢谢推荐
不过语言的问题我去dc提了愿意协助本地化

**Comment by EdwinWang0508** [comment]
来函敬悉，谢谢！祝径情直遂，安常履顺。Your letter has been received, thank you. Have a nice day!
