### ISSUE TITLE
隐藏侧边栏

### ISSUE THREAD

**Issue by vnsnclo** [xcanwin/KeepChatGPT#243]
官方出了隐藏侧边栏功能，展示全屏这个功能可以去掉

**Comment by xcanwin** [comment]
官方的隐藏侧边栏功能不好看，它在左上角增加了一个退出全屏按钮，会给本插件的```展示大屏```功能造成遮挡，影响截图。
而本插件的```展示全屏```功能会在对话框上方增加一个叫```KEEP```的退出全屏按钮，对截图非常友好。
