### ISSUE TITLE
兼容 gpt4-mobile

### ISSUE THREAD

**Issue by MichaelToLearn** [xcanwin/KeepChatGPT#244]
装上这个插件后，下面这个可以使用不限制次数的 gpt4-mobile 模型的插件就失效了：
https://greasyfork.org/zh-CN/scripts/467317-chatgpt%E5%BC%80%E5%90%AF%E4%B8%8D%E9%99%90%E6%AC%A1%E6%95%B0%E7%9A%84gpt4-mobile

原因是因为两个项目都劫持了 fetch，我们这个项目的劫持，导致了上面这个项目失效了。

希望可以同时兼容两种。

**Comment by lulu-sk** [comment]
@xcanwin +1

**Comment by xcanwin** [comment]
已兼容

**Comment by wweggplant** [comment]
可以功能考虑加一下吗？

**Comment by xcanwin** [comment]
> 可以功能考虑加一下吗？

本插件没有加那个功能，听说那个功能失效了。
