### ISSUE TITLE
克隆对话的问题

### ISSUE THREAD

**Issue by pure-maple** [xcanwin/KeepChatGPT#247]
当问题被编辑数次后，点击头像克隆对话，会将对话中的相应序号也复制到对话框中，如"2/2"，建议将其去除。
<img width="683" alt="Snipaste_2023-06-05_13-55-33" src="https://github.com/xcanwin/KeepChatGPT/assets/54388301/4aed7920-d356-437a-bddc-b660715abdbb">

**Comment by xcanwin** [comment]
谢谢反馈，已修复bug，请更新到最新版
