### ISSUE TITLE
提个意见，不同意见可直接关闭

### ISSUE THREAD

**Issue by leconio** [xcanwin/KeepChatGPT#25]
左上角的Logo，一闪一闪的亮瞎眼，没法沉浸式使用了。。。

**Comment by Lete114** [comment]
看看这个？自己写的
https://github.com/Lete114/my-tampermonkey-scripts/blob/main/openai/chat/auto-reload.user.js

**Comment by ZinYY** [comment]
把脚本中的这行删除即可：
`animation: shine 2.8s linear infinite;`

**Comment by xcanwin** [comment]
谢谢反馈，最新版已添加取消动画功能

**Comment by laoma666-github** [comment]
最好不要用这个插件 我用完之后 有人登录我后台 没删记录 被我发现了 说明我们的GPT账号密码已经加被扒了

**Comment by ChengGuang-Li** [comment]
卧槽了 这个插件怎么卸载啊，流氓插件。我的mac 打开gpt 用不了，我看网络 走了这个请求
