### ISSUE TITLE
使用插件前正常，开启插件后 Too many requests in 1 hour. Try again later.

### ISSUE THREAD

**Issue by Bian-Sh** [xcanwin/KeepChatGPT#252]
RT
我开启的功能是这几个：（取消审计，厌恶不尽，拦截跟踪，取消动画）
![image](https://github.com/xcanwin/KeepChatGPT/assets/24520547/602d6b6e-9844-44d3-bdd9-ecaf28f5518b)
效果真的很显著，开启前还能说话，开启后立马 “Too many requests in 1 hour. Try again later.”
运行环境：
Chrome 
Windows10

**Comment by zebrawow** [comment]
我也出现了这个问题

**Comment by Bian-Sh** [comment]
> 调整间隔为900秒

刚才改了试了下还是问题依旧，也不知道是不是今天已经被标记了，我明天再试试

**Comment by sumingcheng** [comment]
我也遇到了这个问题

**Comment by Bian-Sh** [comment]
> 调整间隔为900秒
时间已经调为了 900. 从上次给到反馈后
就刚才重新打开了 chat.openai.com 就发了个 嘿 就提示 too many 。。。。。
所以应该是只要开启插件就会导致这个问题，会不会是某些请求被拦截后导致的一个必现的问题

**Comment by xcanwin** [comment]
> > 调整间隔为900秒
> 
> 时间已经调为了 900. 从上次给到反馈后
> 
> 就刚才重新打开了 chat.openai.com 就发了个 嘿 就提示 too many 。。。。。
> 
> 所以应该是只要开启插件就会导致这个问题，会不会是某些请求被拦截后导致的一个必现的问题

用隐私模式试试，隐私模式可以的话就清理openai所有cookie和缓存，因为cf偶尔抽风把你判定为高风险用户然后保存字段在cookie或缓存里。

**Comment by Bian-Sh** [comment]
不知道会是什么问题，公司这边的就不行，回到宿舍的就行，然后，我觉得应该是跟网络有点关系，如果魔法规则遗漏，或者网络卡，可能导致程序短时间多次发送请求。
大家可以确认下这几个问题：
1. 魔法规则
2. 是否其他插件冲突
3. 各个用到 gpt web session 的插件及时更新
4. 网络别太差

以上是我的猜想，这个 issue结束
