### ISSUE TITLE
希望添加一些新功能

### ISSUE THREAD

**Issue by monkey-sking** [xcanwin/KeepChatGPT#254]
1.当前对话使用的是什么模型的，对话多了，都忘记使用的是什么模型、什么插件了。每次想知道还得返回到最顶部

2.快速返回到对话最顶部，目标官方有返回到最下面，没有回到最顶部的功能。

**Comment by xcanwin** [comment]
这个提议不错

**Comment by xcanwin** [comment]
> > 这个提议不错
> 
> 
> 
> 发现隔壁那个插件好像能在一半切换模型，官方只有4.0用完后可以切换到3.5，能加入切换响应模型的功能吗？

也是考虑的点之一

**Comment by xcanwin** [comment]
> 1.当前对话使用的是什么模型的，对话多了，都忘记使用的是什么模型、什么插件了。每次想知道还得返回到最顶部
> 
> 2.快速返回到对话最顶部，目标官方有返回到最下面，没有回到最顶部的功能。

已经更新了日新月异功能，你可以更新一下。
对着GPT4模型的对话发一个新消息，菜单栏就会高亮GPT-4对话。
