### ISSUE TITLE
希望解决chatgpt回答字数限制的问题（与“言无不尽”不同）

### ISSUE THREAD

**Issue by techblicash** [xcanwin/KeepChatGPT#256]
chatgpt的回答有字数等限制（或是其他原因），导致经常在回答很长一段话或代码时突然结束，也没有continue response的按钮。我告诉它没有回答完之后，它会说“某些原因使我的回答没有显示完”，然后从头又回答一遍，最后又没回答完就结束了，循环往复。
希望keepchatgpt可以解决这个问题~谢谢~

**Comment by xcanwin** [comment]
你有大概记录一下```在回答很长一段话或代码时```的时长吗？我记录过```言无不尽```功能最长可以延长回答足足5分30秒，字数我倒是没有记录。我当时超过5分30秒以后确实如你所说会```突然结束```，但是比起原本的60秒已经有很大的改善。
你开启```言无不尽```，然后大概记录一下你遇到的```突然结束```的时长，同时提供一下整个聊天过程的截图，有图有数据我好分析。
