### ISSUE TITLE
建议：鼠标划过(hover)左侧的每一条会话记录时能显示删除按钮

### ISSUE THREAD

**Issue by Kukuair** [xcanwin/KeepChatGPT#257]
鼠标划过(hover)左侧的每一条会话记录时能显示删除按钮，目前的情况是如果想要删除某一个对话记录需要先点击进入该会话后才能删除，希望可以在鼠标鼠标划过某条会话记录时能展示一下删除按钮，然后调一下删除的接口，不知道可不可行，如果该建议优先级较低可先搁置

**Comment by xcanwin** [comment]
我建议，看清楚再删。
有多少爱可以重来。

**Comment by yige-yigeren** [comment]
> 我建议，看清楚再删。 有多少爱可以重来。

你们都拿chatgpt干什么阿（恼）

猫娘不是不能玩了吗？

**Comment by threerog** [comment]
正准备提这个建议的，真的有必要呀
目前删除会话记录，需要先点击加载这个会话，如果网络不给力会浪费很多时间
而我只想无脑删除或者全部清空

**Comment by threerog** [comment]
> 我建议，看清楚再删。 有多少爱可以重来。

希望能直接鼠标放上去就能直接删除而不需要加载整个会话
并且支持一键清空记录
加个提示框让用户确认该操作的不可逆

**Comment by 6uu1** [comment]
> 我建议，看清楚再删。 有多少爱可以重来。

同意
