### ISSUE TITLE
my plan选项消失

### ISSUE THREAD

**Issue by voidwolf001** [xcanwin/KeepChatGPT#258]
开启了插件之后，my plan的选项会消失, 浏览器：edge Version 114.0.1823.43 (Official build) (x86_64)
![image](https://github.com/xcanwin/KeepChatGPT/assets/122082004/89a58bb6-0bff-4068-b9e1-9f631ae0f2d9)

**Comment by xcanwin** [comment]
临时取消净化页面

**Comment by voidwolf001** [comment]
感谢大佬
