### ISSUE TITLE
Too many requests in 1 hour. Try again later

### ISSUE THREAD

**Issue by farmer00317558** [xcanwin/KeepChatGPT#26]
session 接口的调用是有频率限制的

**Comment by xcanwin** [comment]
本插件经过大部分coder的测试，挺顺利的。

可以分享几个可能的情况，你自行排查：
1、因为本插件使得你聊天顺畅了，与chatgpt聊天的次数太多，导致官方对聊天频率限制了，而不是cf限制。
2、你的openai账号的web接口或者api接口可能被盗用。建议检查账号购买来源，或者审计一下你浏览器当前其他拓展的源代码，安不安全。他们可能存在收集api key盈利的情况。
3、你的浏览器安装了其他chatgpt拓展或者插件，是他们在频繁请求。

**Comment by farmer00317558** [comment]
- 并没有安装任何其他插件
- 聊天次数并不多
- 我账号没有创建任何 API KEY

😅
