### ISSUE TITLE
语言识别问题

### ISSUE THREAD

**Issue by Zarah636** [xcanwin/KeepChatGPT#261]
15.1-15.6版本又出现了之前的语言问题，默认语言简中，窗口显示为繁中。
![image](https://github.com/xcanwin/KeepChatGPT/assets/66152392/5f796533-c50d-40c4-afde-3c1f883b83ac)

**Comment by xcanwin** [comment]
之前你也遇到了，https://github.com/xcanwin/KeepChatGPT/issues/139，按道理不会有bug的。
你在控制台执行navigator.languages，把文字结果发给我看看。

**Comment by Zarah636** [comment]
![image](https://github.com/xcanwin/KeepChatGPT/assets/66152392/e3f2174c-5191-4281-a6fb-fa1508dfbb41)

**Comment by Zarah636** [comment]
现在好了，我的浏览器默认语言置顶不知道为啥成了繁体
