### ISSUE TITLE
[新功能建议] 显示GPT-4 当前剩余使用次数

### ISSUE THREAD

**Issue by TaylorChyi** [xcanwin/KeepChatGPT#264]
作者你好！ 非常感谢你完成的这个插件，对于我使用chatgpt的体验有了很大的提升。

对于使用GPT-4的时候，官方并没有提供显示当前剩余使用次数，在我办公的时候经常因为自己对于编辑promote的不上心或业务量较密集而短期内使用了过多的提问次数。

如果有实现这个需求，我想在提问的时候我可以更方便的去控制提问的频率，promote的措辞修改，以及让提问时间分散而尽可能的去规避使用次数用完后进度被搁置的情况发生。

希望作者可以予以考虑显示当前时间内剩余使用次数这个需求。

感谢。

**Comment by Fury76** [comment]
我刚想提这个，就发现有人提了。确实迫切需要这个。希望作者能加一个这个功能，万分感谢
