### ISSUE TITLE
Sorry, you have been blocked

### ISSUE THREAD

**Issue by 181670198** [xcanwin/KeepChatGPT#266]
安装插件后，依旧显示Sorry, you have been blocked

**Comment by TeamFan** [comment]
Sorry, you have been blocked 应该是节点问题

Oops!
You do not have an account because it has been deleted or deactivated. If you believe this was an error, please contact us through our help center at help.openai.com.
应该是账号挂了，如果之前是plus用户，建议自查有没有使用depay的记录，不是plus可以考虑一下，是否在ios端直连或者存在其他节点问题

**Comment by ptw-cwl** [comment]
> 

我也是报的这个错，然后我清除缓存关闭浏览器，然后重新安装这个脚本，好了一阵子，然后又报这个错了，在重复上面的操作，好了一下然后又报这个错了，不知道什么原因
![image](https://github.com/xcanwin/KeepChatGPT/assets/79617221/ac7ca888-f78e-45c8-bb95-ba4b74989515)
