### ISSUE TITLE
拦截跟踪可能会出现 unusual activities 提示

### ISSUE THREAD

**Issue by LancerComet** [xcanwin/KeepChatGPT#268]
开启了拦截跟踪之后，GPT 会在发送消息后提示 Our system has detected unusual activities on your account, please try again later（准确的文字记不清了但就这么个提示），关闭后刷新页面就好了；倒不觉得是本插件问题，只是觉得此问题风险看起来很高，发个 issue 希望能为其他人做个提示

**Comment by xcanwin** [comment]
多看几个issue，多看readme，研究深入点，你的回答与答案完全相反。
现在用完本插件还报错的，基本上99%都是魔法问题。拦截跟踪这个功能是在保护你，减少被收集信息，减少封号的大数据。

**Comment by xcanwin** [comment]
软件商（官方）一般会优先处理数据上报多的且违规的用户，不会优先处理甚至不处理数据上报少的用户，理由是现在的广告拦截拓展太强太多了，规则几万条，连软件商自己日常生活也随时开启着广告拦截工具，所以他们如果自己对自己动刀那是违背了自己的日常生活意愿。

**Comment by LancerComet** [comment]
你在说什么，我没说是插件逻辑问题，因为关闭数据埋点后用户还有大量活动这个行为完全能够分析的出来，反而这个功能就是有风险，然后我如果说我不需要使用魔法怎么办啊。

**Comment by xcanwin** [comment]
所以我讲半天你半天没听，还拿这种不听讲的案例来说明。
你在其他网站不也是安装广告拦截插件然后却还有大量活动？那些网站不也没有封你号。讲半天你是真的一点都不听还来乱科普。好心可以，但是不听讲解又乱科普就是不行。
你一个国内北京用户在这里乱举例说你不用魔法。好心可以，但是不听讲解又乱讲就是不行。

**Comment by xcanwin** [comment]
不要在issue发表不听讲解的东西
