### ISSUE TITLE
与superpower Chatgpt同时用时，页面显示不全

### ISSUE THREAD

**Issue by Kobe987** [xcanwin/KeepChatGPT#269]
当同时使用keepchatgpt和superpower Chatgpt插件时，在13寸笔记本和21寸显示器上会出现左侧导航窗口的会话历史全部消失。
![image](https://github.com/xcanwin/KeepChatGPT/assets/31915726/910b0d2b-ed94-4dd2-a982-3c73e1c557a7)

**Comment by xcanwin** [comment]
之前一直都是稳定共存的

**Comment by Kobe987** [comment]
> 之前一直都是稳定共存的

感谢回复，在edge里面目前是有冲突的，我换了chrome试了下确实可以共存。
![image](https://github.com/xcanwin/KeepChatGPT/assets/31915726/8c4428ff-03ab-4b22-8fb5-344eaea91199)

**Comment by Etleventt** [comment]
![image](https://github.com/xcanwin/KeepChatGPT/assets/56229241/0e62d754-32ec-433e-8651-a2b0e44bb239)
还是有些冲突的，想要使用superpower 的这个文件夹功能，
但是keep用了以后UI上有些冲突了
![image](https://github.com/xcanwin/KeepChatGPT/assets/56229241/27db102b-a7b5-4561-b35d-1aeb3c49c3a4)
😂
