### ISSUE TITLE
编辑ai输出内容

### ISSUE THREAD

**Issue by lijie97** [xcanwin/KeepChatGPT#272]
希望可以添加一个功能可以编辑ai输出内容, 让ai接下来的输入更符合prompt的引导

**Comment by xcanwin** [comment]
这可能是prompt做的事情，你可以：
"请问xxxxx，我希望你接下来回答的内容含有关键词yyy"等等

**Comment by lijie97** [comment]
> 这可能是prompt做的事情，你可以： "请问xxxxx，我希望你接下来回答的内容含有关键词yyy"等等

不是, 
相当于
```python
    messages = [
        SystemMessage(content=instruct),
        HumanMessage(content=guide_line_input_sample),
        AIMessage(content=guide_line_response),
        HumanMessage(content=actual_input),        
    ]
```
把期望ai输出写到AIMessage(content=guide_line_response)作为一个guideline, 更好地指引ai后续的输出

**Comment by fbfb2023** [comment]
之前有个大佬发的chatsydney可以修改newbing的回复，比如本身newbing回复的是12345，我可以手动把newbing的回复修改成比如qwert之类的，这样newbing就以为它回复我的内容就是qwert而不是它本身回复我的12345。但是大佬的网址都404了。我找到一个在404之前用他的方法搭建出来的网址：https://nekointelligence.cyou:65432/  楼主在贴吧的帖子：https://tieba.baidu.com/p/8422121526     如果大佬有时间的话可以参考一下，我不知道是什么原理，但感觉如果gpt4能实现就真的神了。
