### ISSUE TITLE
你好，用完这个插件我的对话框和左下角用户设置都消失了，该怎么修复呢

### ISSUE THREAD

**Issue by ybkim1996** [xcanwin/KeepChatGPT#274]
删掉插件也没用，mobile版正常的。
![image](https://github.com/xcanwin/KeepChatGPT/assets/99322414/31ee5bc9-da48-4590-8bf9-712ec9f41c1e)

**Comment by ybkim1996** [comment]
![IMG_4631](https://github.com/xcanwin/KeepChatGPT/assets/99322414/a354321d-5985-4ebe-9742-2ddb3d04f534)

**Comment by ybkim1996** [comment]
用浏览器隐私模式就可以显示

**Comment by Ezra-Chan** [comment]
有没有可能是其他插件引起的，因为你没有设置隐私模式也能使用该插件，所以不影响你的隐私模式

**Comment by ybkim1996** [comment]
> 有没有可能是其他插件引起的，因为你没有设置隐私模式也能使用该插件，所以不影响你的隐私模式

没有啊，gpt插件我昨天第一次下，我因为gpt4被限制了看看有没有插件能帮忙就下载了，然后刷新页面就空白了，然后我就把插件删了还是不恢复，别的插件全部卸载，chrome强删卸载，用别的浏览器，用别的电脑都不行了，我人麻了

**Comment by xcanwin** [comment]
本插件用户量非常大，如果是因为本插件导致的，你会在这几天看到至少一百多个用户同时反馈。
如果没有，说明是你的特殊情况导致的。多回忆回忆。
还有你的页面与别人不一样你多思考思考为啥，你聊天框的chatgpt颜色是橙色的，你发送消息的按钮是一个绿色的圆形机器人。我体验得少，没见过这样的。
