### ISSUE TITLE
When chat history is off, the "Clear Chat" button in the top left corner is covered by the KeepChatGPT banner.

### ISSUE THREAD

**Issue by i-Mark-Wu** [xcanwin/KeepChatGPT#277]
When chat history is off, there's a "clear chat" button in the top left corner, but it's covered by the KeepChatGPT banner. I have to refresh the web page to clear the chat. 
![Untitled](https://github.com/xcanwin/KeepChatGPT/assets/34133485/87332d02-9859-474f-bb03-21967fa1e04f)

**Comment by xcanwin** [comment]
调试这个需要我清理我的历史。
你完整复制一下侧边栏的html代码给我看看

**Comment by i-Mark-Wu** [comment]
``` 
<nav class="flex h-full w-full flex-col p-2" aria-label="Chat history">
   <div class="mb-1 flex flex-row gap-2">
      <a class="flex p-3 items-center gap-3 transition-colors duration-200 text-white cursor-pointer text-sm rounded-md border border-white/20 hover:bg-gray-500/10 h-11 flex-shrink-0 flex-grow">
         <svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
            <polyline points="23 4 23 10 17 10"></polyline>
            <polyline points="1 20 1 14 7 14"></polyline>
            <path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"></path>
         </svg>
         Clear chat
      </a>
      <span class="" data-state="closed">
         <a class="flex p-3 gap-3 transition-colors duration-200 text-white cursor-pointer text-sm rounded-md border border-white/20 hover:bg-gray-500/10 h-11 w-11 flex-shrink-0 items-center justify-center">
            <svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
               <rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect>
               <line x1="9" y1="3" x2="9" y2="21"></line>
            </svg>
            <span style="position: absolute; border: 0px; width: 1px; height: 1px; padding: 0px; margin: -1px; overflow: hidden; clip: rect(0px, 0px, 0px, 0px); white-space: nowrap; overflow-wrap: normal;">Close sidebar</span>
         </a>
      </span>
   </div>
   <div class="absolute left-0 top-14 z-20 overflow-hidden transition-all duration-500 visible max-h-72">
      <div class="bg-gray-900 px-4 py-3">
         <div class="p-1 text-sm text-gray-100">Chat History is off for this browser.</div>
         <div class="p-1 text-xs text-gray-500">When history is turned off, new chats on this browser won't appear in your history on any of your devices, be used to train our models, or stored for longer than 30 days. <strong>This setting does not sync across browsers or devices.</strong> <a href="https://help.openai.com/en/articles/7730893" target="_blank" class="underline" rel="noreferrer">Learn more</a></div>
         <button class="btn relative btn-primary mt-4 w-full">
            <div class="flex w-full gap-2 items-center justify-center">
               <svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
                  <path d="M18.36 6.64a9 9 0 1 1-12.73 0"></path>
                  <line x1="12" y1="2" x2="12" y2="12"></line>
               </svg>
               Enable chat history
            </div>
         </button>
      </div>
      <div class="h-24 bg-gradient-to-t from-gray-900/0 to-gray-900"></div>
   </div>
   <div class="flex-col flex-1 transition-opacity duration-500 overflow-y-hidden opacity-20 pointer-events-none">
      <div class="flex flex-col gap-2 pb-2 text-gray-100 text-sm">
         <div>
            <span>
               <div class="relative" data-projection-id="1" style="height: auto; opacity: 1;">
                  <ol></ol>
               </div>
            </span>
            <span></span><span></span>
         </div>
      </div>
   </div>
   <div class="border-t border-white/20 pt-2 empty:hidden">
      <div class="group relative" data-headlessui-state="">
         <button class="flex w-full items-center gap-2.5 rounded-md px-3 py-3 text-sm transition-colors duration-200 hover:bg-gray-800 group-ui-open:bg-gray-800" type="button" aria-haspopup="true" aria-expanded="false" data-state="open" id="headlessui-menu-button-:r9:" data-headlessui-state="">
            <div class="flex-shrink-0">
               <div class="relative flex"><img alt="User" loading="lazy" width="28" height="28" decoding="async" data-nimg="1" class="rounded-sm" srcset="" src="" style="color: transparent;"></div>
            </div>
            <div class="grow overflow-hidden text-ellipsis whitespace-nowrap text-left text-white">email@email.com</div>
            <svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4 flex-shrink-0 text-gray-500" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
               <circle cx="12" cy="12" r="1"></circle>
               <circle cx="19" cy="12" r="1"></circle>
               <circle cx="5" cy="12" r="1"></circle>
            </svg>
         </button>
      </div>
   </div>
</nav>

**Comment by xcanwin** [comment]
你复制的代码位置很正确。
只不过你顺手美化了html格式，导致破坏了我调试解析。
请不美化html直接复制原生的html。

**Comment by xcanwin** [comment]
谢谢反馈，经过分析发现这居然是openai官方的bug，我已经在最新版v16.4帮openai修复了这个问题

**Comment by QuantumRoseinAmethystVase** [comment]
没有看到清除历史的按钮，v16.4

**Comment by xcanwin** [comment]
> 没有看到清除历史的按钮，v16.4

你参考题主发的html源码，也发一下你账号的侧边栏html，我调试一下。

**Comment by xcanwin** [comment]
> > 没有看到清除历史的按钮，v16.4
> 
> 你参考题主发的html源码，也发一下你账号的侧边栏html，我调试一下。

隔壁有成功反馈：https://github.com/xcanwin/KeepChatGPT/issues/287
你的账号应该有不一样的地方

**Comment by QuantumRoseinAmethystVase** [comment]
> > 没有看到清除历史的按钮，v16.4
> 
> 你参考题主发的html源码，也发一下你账号的侧边栏html，我调试一下。

<nav class="flex h-full w-full flex-col p-2 knav" aria-label="Chat history"><div id="kcg" class="kgold flex py-3 px-3 items-center gap-3 rounded-md text-sm mb-1 flex-shrink-0 border border-white/20" style="background: rgb(44, 62, 80); animation: 0s; color: rgb(255, 255, 255); margin-right: inherit;"><img src="data:image/svg+xml;utf8,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; height=&quot;24&quot; width=&quot;24&quot; stroke-width=&quot;2&quot; fill=&quot;none&quot; stroke=&quot;currentColor&quot;><path d=&quot;M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22&quot;></path></svg>">KeepChatGPT by xcanwin</div><div class="mb-1 flex flex-row gap-2" data-immersive-translate-effect="1" data-immersive_translate_walked="d4f3334f-2265-4c77-b2c2-43f2afd2f150"><a class="flex p-3 items-center gap-3 transition-colors duration-200 text-white cursor-pointer text-sm rounded-md border border-white/20 hover:bg-gray-500/10 h-11 flex-shrink-0 flex-grow" data-immersive-translate-effect="1" data-immersive_translate_walked="d4f3334f-2265-4c77-b2c2-43f2afd2f150"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg" data-immersive-translate-effect="1" data-immersive_translate_walked="d4f3334f-2265-4c77-b2c2-43f2afd2f150"><line x1="12" y1="5" x2="12" y2="19" data-immersive-translate-effect="1" data-immersive_translate_walked="d4f3334f-2265-4c77-b2c2-43f2afd2f150"></line><line x1="5" y1="12" x2="19" y2="12" data-immersive-translate-effect="1" data-immersive_translate_walked="d4f3334f-2265-4c77-b2c2-43f2afd2f150"></line></svg><font class="notranslate immersive-translate-target-wrapper immersive-translate-state-dual" lang="zh-CN" data-immersive-translate-translation-element-mark="1"><font class="notranslate immersive-translate-target-dual" data-immersive-translate-translation-element-mark="1" data-immersive-translate-effect="1" data-immersive-translate-class-bak="notranslate immersive-translate-target-translation-theme-blockquote immersive-translate-target-translation-inline-wrapper-theme-blockquote immersive-translate-target-translation-inline-wrapper"><font class="notranslate immersive-translate-target-dual" data-immersive-translate-translation-element-mark="1" data-immersive-translate-effect="1" data-immersive-translate-class-bak="notranslate immersive-translate-target-inner immersive-translate-target-translation-theme-blockquote-inner">新聊天</font></font></font></a><span class="" data-state="closed" data-immersive-translate-effect="1" data-immersive_translate_walked="d4f3334f-2265-4c77-b2c2-43f2afd2f150"><a class="flex p-3 gap-3 transition-colors duration-200 text-white cursor-pointer text-sm rounded-md border border-white/20 hover:bg-gray-500/10 h-11 w-11 flex-shrink-0 items-center justify-center" data-immersive-translate-effect="1" data-immersive_translate_walked="d4f3334f-2265-4c77-b2c2-43f2afd2f150"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg" data-immersive-translate-effect="1" data-immersive_translate_walked="d4f3334f-2265-4c77-b2c2-43f2afd2f150"><rect x="3" y="3" width="18" height="18" rx="2" ry="2" data-immersive-translate-effect="1" data-immersive_translate_walked="d4f3334f-2265-4c77-b2c2-43f2afd2f150"></rect><line x1="9" y1="3" x2="9" y2="21" data-immersive-translate-effect="1" data-immersive_translate_walked="d4f3334f-2265-4c77-b2c2-43f2afd2f150"></line></svg><span style="position: absolute; border: 0px; width: 1px; height: 1px; padding: 0px; margin: -1px; overflow: hidden; clip: rect(0px, 0px, 0px, 0px); white-space: nowrap; overflow-wrap: normal;">Close sidebar</span></a></span></div><div class="absolute left-0 top-14 z-20 overflow-hidden transition-all duration-500 invisible max-h-0"><div class="bg-gray-900 px-4 py-3"><div class="p-1 text-sm text-gray-100">Chat History is off for this browser.</div><div class="p-1 text-xs text-gray-500">When history is turned off, new chats on this browser won't appear in your history on any of your devices, be used to train our models, or stored for longer than 30 days. <strong>This setting does not sync across browsers or devices.</strong> <a href="https://help.openai.com/en/articles/7730893" target="_blank" class="underline" rel="noreferrer">Learn more</a></div><button class="btn relative btn-primary mt-4 w-full"><div class="flex w-full gap-2 items-center justify-center"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M18.36 6.64a9 9 0 1 1-12.73 0"></path><line x1="12" y1="2" x2="12" y2="12"></line></svg>Enable chat history</div></button></div><div class="h-24 bg-gradient-to-t from-gray-900/0 to-gray-900"></div></div><div class="flex-col flex-1 transition-opacity duration-500 overflow-y-auto"><div class="flex flex-col gap-2 pb-2 text-gray-100 text-sm"><div><span><div class="relative" style="height: auto; opacity: 1; transform: none; transform-origin: 50% 50%;" data-projection-id="17"><div class="sticky top-0 z-[16]" data-projection-id="18" style="transform: none; transform-origin: 50% 50%; opacity: 1;"><h3 class="h-9 pb-2 pt-3 px-3 text-xs text-gray-500 font-medium text-ellipsis overflow-hidden break-all bg-gray-900">Today</h3></div><ol><li class="relative z-[15]" style="opacity: 1; height: auto; transform: none; transform-origin: 50% 50%;" data-projection-id="19"><a class="flex py-3 px-3 items-center gap-3 relative rounded-md hover:bg-[#2A2B32] cursor-pointer break-all )} )} hover:pr-4 bg-gray-900 group"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path></svg><div class="flex-1 text-ellipsis overflow-hidden break-all relative">
<div style="max-height: unset; max-width: 70%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; position: absolute;" class="navtitle">New chat</div>
<div style="right: 0;position: absolute;color: grey;font-size: 0.71rem;" class="navdate">21:45</div>
<br>
<div style="max-height: unset; max-width: 95%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: gray; font-size: 0.75rem;" class="navlast">内网DNS解锁是指在一个局域网内（内网）使用特定的DNS设置或技术，使得用户可以绕过地区限制或访问受限制的网站和服务。通常，某些网站或服务可能因为地理位置、政策法规或版权问题而被限制在特定的地区访问。</div>
</div><div class="flex-1 text-ellipsis max-h-5 overflow-hidden break-all relative" style="display: none;">New chat<div class="absolute inset-y-0 right-0 w-8 z-10 bg-gradient-to-l from-gray-900 group-hover:from-[#2A2B32]"></div></div></a></li><li class="relative" style="opacity: 1; height: auto; transform: none; transform-origin: 50% 50%;" data-projection-id="20"><a class="flex py-3 px-3 items-center gap-3 relative rounded-md hover:bg-[#2A2B32] cursor-pointer break-all )} )} hover:pr-4 bg-gray-900 group"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path></svg><div class="flex-1 text-ellipsis overflow-hidden break-all relative">
<div style="max-height: unset; max-width: 70%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; position: absolute;" class="navtitle">GPT-3.5 Turbo Updates</div>
<div style="right: 0;position: absolute;color: grey;font-size: 0.71rem;" class="navdate">21:30</div>
<br>
<div style="max-height: unset; max-width: 95%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: gray; font-size: 0.75rem;" class="navlast"></div>
</div><div class="flex-1 text-ellipsis max-h-5 overflow-hidden break-all relative" style="display: none;">GPT-3.5 Turbo Updates<div class="absolute inset-y-0 right-0 w-8 z-10 bg-gradient-to-l from-gray-900 group-hover:from-[#2A2B32]"></div></div></a></li><li class="relative" style="opacity: 1; height: auto; transform: none; transform-origin: 50% 50%;" data-projection-id="21"><a class="flex py-3 px-3 items-center gap-3 relative rounded-md hover:bg-[#2A2B32] cursor-pointer break-all )} )} hover:pr-4 bg-gray-900 group"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path></svg><div class="flex-1 text-ellipsis overflow-hidden break-all relative">
<div style="max-height: unset; max-width: 70%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; position: absolute;" class="navtitle">New chat</div>
<div style="right: 0;position: absolute;color: grey;font-size: 0.71rem;" class="navdate" data-immersive-translate-effect="1" data-immersive_translate_walked="d4f3334f-2265-4c77-b2c2-43f2afd2f150">15:52</div>
<br>
<div style="max-height: unset; max-width: 95%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: gray; font-size: 0.75rem;" class="navlast"></div>
</div><div class="flex-1 text-ellipsis max-h-5 overflow-hidden break-all relative" style="display: none;">New chat<div class="absolute inset-y-0 right-0 w-8 z-10 bg-gradient-to-l from-gray-900 group-hover:from-[#2A2B32]"></div></div></a></li><li class="relative" style="opacity: 1; height: auto; transform: none; transform-origin: 50% 50%;" data-projection-id="22"><a class="flex py-3 px-3 items-center gap-3 relative rounded-md hover:bg-[#2A2B32] cursor-pointer break-all )} )} hover:pr-4 bg-gray-900 group"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path></svg><div class="flex-1 text-ellipsis overflow-hidden break-all relative">
<div style="max-height: unset; max-width: 70%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; position: absolute;" class="navtitle">New chat</div>
<div style="right: 0;position: absolute;color: grey;font-size: 0.71rem;" class="navdate">08:43</div>
<br>
<div style="max-height: unset; max-width: 95%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: gray; font-size: 0.75rem;" class="navlast"></div>
</div><div class="flex-1 text-ellipsis max-h-5 overflow-hidden break-all relative" style="display: none;">New chat<div class="absolute inset-y-0 right-0 w-8 z-10 bg-gradient-to-l from-gray-900 group-hover:from-[#2A2B32]"></div></div></a></li></ol></div></span><span></span><span></span></div></div></div><div class="border-t border-white/20 pt-2 empty:hidden"><div class="group relative" data-headlessui-state=""><button class="flex w-full items-center gap-2.5 rounded-md px-3 py-3 text-sm transition-colors duration-200 hover:bg-gray-800 group-ui-open:bg-gray-800" type="button" aria-haspopup="true" aria-expanded="false" data-state="closed" id="headlessui-menu-button-:r20:" data-headlessui-state=""><div class="flex-shrink-0"><div class="relative flex"><img alt="User" loading="lazy" width="28" height="28" decoding="async" data-nimg="1" class="rounded-sm" style="color: transparent;" srcset="/_next/image?url=https%3A%2F%2Fs.gravatar.com%2Favatar%2Ff7f089af5d0ec2ab811f0dfdd5a1a934%3Fs%3D480%26r%3Dpg%26d%3Dhttps%253A%252F%252Fcdn.auth0.com%252Favatars%252Fri.png&amp;w=32&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fs.gravatar.com%2Favatar%2Ff7f089af5d0ec2ab811f0dfdd5a1a934%3Fs%3D480%26r%3Dpg%26d%3Dhttps%253A%252F%252Fcdn.auth0.com%252Favatars%252Fri.png&amp;w=64&amp;q=75 2x" src="/_next/image?url=https%3A%2F%2Fs.gravatar.com%2Favatar%2Ff7f089af5d0ec2ab811f0dfdd5a1a934%3Fs%3D480%26r%3Dpg%26d%3Dhttps%253A%252F%252Fcdn.auth0.com%252Favatars%252Fri.png&amp;w=64&amp;q=75"></div></div><div class="grow overflow-hidden text-ellipsis whitespace-nowrap text-left text-white">ripereesufga@mail.com</div><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4 flex-shrink-0 text-gray-500" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><circle cx="12" cy="12" r="1"></circle><circle cx="19" cy="12" r="1"></circle><circle cx="5" cy="12" r="1"></circle></svg></button></div></div></nav>

**Comment by QuantumRoseinAmethystVase** [comment]
> > 没有看到清除历史的按钮，v16.4
> 
> 你参考题主发的html源码，也发一下你账号的侧边栏html，我调试一下。

<nav class="flex h-full w-full flex-col p-2 knav" aria-label="Chat history"><div id="kcg" class="kgold flex py-3 px-3 items-center gap-3 rounded-md text-sm mb-1 flex-shrink-0 border border-white/20" style="background: rgb(44, 62, 80); animation: 0s; color: rgb(255, 255, 255); margin-right: inherit;"><img src="data:image/svg+xml;utf8,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; height=&quot;24&quot; width=&quot;24&quot; stroke-width=&quot;2&quot; fill=&quot;none&quot; stroke=&quot;currentColor&quot;><path d=&quot;M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22&quot;></path></svg>">KeepChatGPT by xcanwin</div><div class="mb-1 flex flex-row gap-2"><a class="flex p-3 items-center gap-3 transition-colors duration-200 text-white cursor-pointer text-sm rounded-md border border-white/20 hover:bg-gray-500/10 h-11 flex-shrink-0 flex-grow"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>New chat</a><span class="" data-state="closed"><a class="flex p-3 gap-3 transition-colors duration-200 text-white cursor-pointer text-sm rounded-md border border-white/20 hover:bg-gray-500/10 h-11 w-11 flex-shrink-0 items-center justify-center"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="9" y1="3" x2="9" y2="21"></line></svg><span style="position: absolute; border: 0px; width: 1px; height: 1px; padding: 0px; margin: -1px; overflow: hidden; clip: rect(0px, 0px, 0px, 0px); white-space: nowrap; overflow-wrap: normal;">Close sidebar</span></a></span></div><div class="absolute left-0 top-14 z-20 overflow-hidden transition-all duration-500 invisible max-h-0"><div class="bg-gray-900 px-4 py-3"><div class="p-1 text-sm text-gray-100">Chat History is off for this browser.</div><div class="p-1 text-xs text-gray-500">When history is turned off, new chats on this browser won't appear in your history on any of your devices, be used to train our models, or stored for longer than 30 days. <strong>This setting does not sync across browsers or devices.</strong> <a href="https://help.openai.com/en/articles/7730893" target="_blank" class="underline" rel="noreferrer">Learn more</a></div><button class="btn relative btn-primary mt-4 w-full"><div class="flex w-full gap-2 items-center justify-center"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M18.36 6.64a9 9 0 1 1-12.73 0"></path><line x1="12" y1="2" x2="12" y2="12"></line></svg>Enable chat history</div></button></div><div class="h-24 bg-gradient-to-t from-gray-900/0 to-gray-900"></div></div><div class="flex-col flex-1 transition-opacity duration-500 overflow-y-auto"><div class="flex flex-col gap-2 pb-2 text-gray-100 text-sm"><div><span><div class="relative" style="height: auto; opacity: 1; transform: none; transform-origin: 50% 50%;" data-projection-id="48"><ol></ol></div></span><span></span><span></span></div></div></div><div class="border-t border-white/20 pt-2 empty:hidden"><div class="group relative" data-headlessui-state=""><button class="flex w-full items-center gap-2.5 rounded-md px-3 py-3 text-sm transition-colors duration-200 hover:bg-gray-800 group-ui-open:bg-gray-800" type="button" aria-haspopup="true" aria-expanded="false" data-state="closed" id="headlessui-menu-button-:r5m:" data-headlessui-state=""><div class="flex-shrink-0"><div class="relative flex"><img alt="User" loading="lazy" width="28" height="28" decoding="async" data-nimg="1" class="rounded-sm" style="color: transparent;" srcset="/_next/image?url=https%3A%2F%2Fs.gravatar.com%2Favatar%2Ff7f089af5d0ec2ab811f0dfdd5a1a934%3Fs%3D480%26r%3Dpg%26d%3Dhttps%253A%252F%252Fcdn.auth0.com%252Favatars%252Fri.png&amp;w=32&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fs.gravatar.com%2Favatar%2Ff7f089af5d0ec2ab811f0dfdd5a1a934%3Fs%3D480%26r%3Dpg%26d%3Dhttps%253A%252F%252Fcdn.auth0.com%252Favatars%252Fri.png&amp;w=64&amp;q=75 2x" src="/_next/image?url=https%3A%2F%2Fs.gravatar.com%2Favatar%2Ff7f089af5d0ec2ab811f0dfdd5a1a934%3Fs%3D480%26r%3Dpg%26d%3Dhttps%253A%252F%252Fcdn.auth0.com%252Favatars%252Fri.png&amp;w=64&amp;q=75"></div></div><div class="grow overflow-hidden text-ellipsis whitespace-nowrap text-left text-white">ripereesufga@mail.com</div><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4 flex-shrink-0 text-gray-500" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><circle cx="12" cy="12" r="1"></circle><circle cx="19" cy="12" r="1"></circle><circle cx="5" cy="12" r="1"></circle></svg></button></div></div></nav>

**Comment by xcanwin** [comment]
我知道了，因为你还不知道"Chat history & training"是chatgpt自带的功能，你找找官网左下角

**Comment by QuantumRoseinAmethystVase** [comment]
> > > > 没有看到清除历史的按钮，v16.4
> > > 
> > > 
> > > 你参考题主发的html源码，也发一下你账号的侧边栏html，我调试一下。
> > 
> > 
> > ```
> > <nav class="flex h-full w-full flex-col p-2 knav" aria-label="Chat history"><div id="kcg" class="kgold flex py-3 px-3 items-center gap-3 rounded-md text-sm mb-1 flex-shrink-0 border border-white/20" style="background: rgb(44, 62, 80); animation: 0s; color: rgb(255, 255, 255); margin-right: inherit;"><img src="data:image/svg+xml;utf8,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; height=&quot;24&quot; width=&quot;24&quot; stroke-width=&quot;2&quot; fill=&quot;none&quot; stroke=&quot;currentColor&quot;><path d=&quot;M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22&quot;></path></svg>">KeepChatGPT by xcanwin</div><div class="mb-1 flex flex-row gap-2"><a class="flex p-3 items-center gap-3 transition-colors duration-200 text-white cursor-pointer text-sm rounded-md border border-white/20 hover:bg-gray-500/10 h-11 flex-shrink-0 flex-grow"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>New chat</a><span class="" data-state="closed"><a class="flex p-3 gap-3 transition-colors duration-200 text-white cursor-pointer text-sm rounded-md border border-white/20 hover:bg-gray-500/10 h-11 w-11 flex-shrink-0 items-center justify-center"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="9" y1="3" x2="9" y2="21"></line></svg><span style="position: absolute; border: 0px; width: 1px; height: 1px; padding: 0px; margin: -1px; overflow: hidden; clip: rect(0px, 0px, 0px, 0px); white-space: nowrap; overflow-wrap: normal;">Close sidebar</span></a></span></div><div class="absolute left-0 top-14 z-20 overflow-hidden transition-all duration-500 invisible max-h-0"><div class="bg-gray-900 px-4 py-3"><div class="p-1 text-sm text-gray-100">Chat History is off for this browser.</div><div class="p-1 text-xs text-gray-500">When history is turned off, new chats on this browser won't appear in your history on any of your devices, be used to train our models, or stored for longer than 30 days. <strong>This setting does not sync across browsers or devices.</strong> <a href="https://help.openai.com/en/articles/7730893" target="_blank" class="underline" rel="noreferrer">Learn more</a></div><button class="btn relative btn-primary mt-4 w-full"><div class="flex w-full gap-2 items-center justify-center"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M18.36 6.64a9 9 0 1 1-12.73 0"></path><line x1="12" y1="2" x2="12" y2="12"></line></svg>Enable chat history</div></button></div><div class="h-24 bg-gradient-to-t from-gray-900/0 to-gray-900"></div></div><div class="flex-col flex-1 transition-opacity duration-500 overflow-y-auto"><div class="flex flex-col gap-2 pb-2 text-gray-100 text-sm"><div><span><div class="relative" style="height: auto; opacity: 1; transform: none; transform-origin: 50% 50%;" data-projection-id="48"><ol></ol></div></span><span></span><span></span></div></div></div><div class="border-t border-white/20 pt-2 empty:hidden"><div class="group relative" data-headlessui-state=""><button class="flex w-full items-center gap-2.5 rounded-md px-3 py-3 text-sm transition-colors duration-200 hover:bg-gray-800 group-ui-open:bg-gray-800" type="button" aria-haspopup="true" aria-expanded="false" data-state="closed" id="headlessui-menu-button-:r5m:" data-headlessui-state=""><div class="flex-shrink-0"><div class="relative flex"><img alt="User" loading="lazy" width="28" height="28" decoding="async" data-nimg="1" class="rounded-sm" style="color: transparent;" srcset="/_next/image?url=https%3A%2F%2Fs.gravatar.com%2Favatar%2Ff7f089af5d0ec2ab811f0dfdd5a1a934%3Fs%3D480%26r%3Dpg%26d%3Dhttps%253A%252F%252Fcdn.auth0.com%252Favatars%252Fri.png&amp;w=32&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fs.gravatar.com%2Favatar%2Ff7f089af5d0ec2ab811f0dfdd5a1a934%3Fs%3D480%26r%3Dpg%26d%3Dhttps%253A%252F%252Fcdn.auth0.com%252Favatars%252Fri.png&amp;w=64&amp;q=75 2x" src="/_next/image?url=https%3A%2F%2Fs.gravatar.com%2Favatar%2Ff7f089af5d0ec2ab811f0dfdd5a1a934%3Fs%3D480%26r%3Dpg%26d%3Dhttps%253A%252F%252Fcdn.auth0.com%252Favatars%252Fri.png&amp;w=64&amp;q=75"></div></div><div class="grow overflow-hidden text-ellipsis whitespace-nowrap text-left text-white">email</div><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4 flex-shrink-0 text-gray-500" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><circle cx="12" cy="12" r="1"></circle><circle cx="19" cy="12" r="1"></circle><circle cx="5" cy="12" r="1"></circle></svg></button></div></div></nav>
> > ```
> 
> 我知道了，因为你还不知道"Chat history & training"是chatgpt自带的功能，你找找官网左下角

已解决～感谢
