### ISSUE TITLE
Gold button not appearing in Safari MacOS

### ISSUE THREAD

**Issue by ErPiotta** [xcanwin/KeepChatGPT#284]
Safari version: 16.5.2
MacOS version: 13.4.1(c)
KeepChatGPT version: 16.2

Using Userscripts: https://github.com/quoid/userscripts

The extension seems to work as usual, yet there's no golden button on top of the chats hence I cannot change any settings. Is it the same for everyone? Typical issue in Safari?

<img width="1069" alt="Screenshot 2023-07-17 at 2 16 58 PM" src="https://github.com/xcanwin/KeepChatGPT/assets/21013752/5452a6e4-92d5-4b26-93f8-2f05056110e2">

**Comment by xcanwin** [comment]
tampermonkey的功能更强大更好用

**Comment by ErPiotta** [comment]
I used the Stay extension you recommended and it's working perfectly fine now! Hence it seems it won't work with Userscript.
