### ISSUE TITLE
插件如何卸载？

### ISSUE THREAD

**Issue by Vie-Any** [xcanwin/KeepChatGPT#286]
我是用的油猴脚本的方式安装的插件，因为用了一段时间后经常无法发送请求，但是又能刷新页面，所以想把插件移除试试。现在已经从油猴中把插件删除了，但是GPT页面的插件依然在，为此我还特意删除cookie和浏览器缓存，插件依然在。现来求助。

**Comment by xcanwin** [comment]
油猴插件是最容易删除的。你可以问chatgpt怎么删除油猴插件。

**Comment by Vie-Any** [comment]
我已经找到我的问题在哪了，不是油猴的问题，是因为早期的时候跟着多个教程安装KeepChatGPT，导致我在油猴和OrangeMonkey中都有KeepChatGPT，我只删除了油猴里的，另一个OrangeMoney中的完全不记得也安装过插件，所以从油猴删除完之后是另一个在生效。

**Comment by Vie-Any** [comment]
> 油猴插件是最容易删除的。你可以问chatgpt怎么删除油猴插件。

我已经找到我的问题在哪了，不是油猴的问题，是因为早期的时候跟着多个教程安装KeepChatGPT，导致我在油猴和OrangeMonkey中都有KeepChatGPT，我只删除了油猴里的，另一个OrangeMoney中的完全不记得也安装过插件，所以从油猴删除完之后是另一个在生效。
