### ISSUE TITLE
选择不保存聊天记录时，KeepChat左上角的标志会遮挡住"Clear chat"的按钮

### ISSUE THREAD

**Issue by TeigenZhang** [xcanwin/KeepChatGPT#287]
开启KeepChat，被遮挡的截图如下：

<img width="298" alt="image" src="https://github.com/xcanwin/KeepChatGPT/assets/38639187/c0e5b21e-b57f-4900-8f4a-ac58543f58bb">

不开启KeepChat，原始部位的截图如下
<img width="290" alt="image" src="https://github.com/xcanwin/KeepChatGPT/assets/38639187/e8d12874-3fa5-4e2f-8401-19dbb3c7a7dc">

被遮挡后无法在不保存聊天记录的模式下通过"Clear chat"按钮清空聊天记录，希望作者能抽空解决该问题！谢谢！

**Comment by xcanwin** [comment]
调试这个需要我清理我的历史。
你完整复制一下侧边栏的html代码给我看看

**Comment by xcanwin** [comment]
谢谢反馈，经过分析发现这居然是openai官方的bug，是官方的Enable chat history遮挡了官方的Clear chat。
我已经在最新版v16.4帮openai修复了这个问题

**Comment by TeigenZhang** [comment]
更新后已确认修复！谢谢您的支持！
