### ISSUE TITLE
取消审计打开了也会出现违规警告

### ISSUE THREAD

**Issue by Gally-Youko** [xcanwin/KeepChatGPT#289]
如图，用户输入的内容全部消失替换成违规警告，以前不会这样的，AI输出目前没有变红也没消失。
![屏幕截图 2023-07-22 161859](https://github.com/xcanwin/KeepChatGPT/assets/138993330/bb77926e-6518-4bca-b283-e6643730c63d)
![屏幕截图 2023-07-22 161816](https://github.com/xcanwin/KeepChatGPT/assets/138993330/c32ad1b2-d99a-4fc1-8f7d-461a68e25629)

**Comment by FruityMaxine** [comment]
问题是普遍的。

**Comment by knightofsantiago** [comment]
我也出现了这个问题。

**Comment by cmradix** [comment]
参考issues #285

**Comment by Gally-Youko** [comment]
> 参考issues #285

看完了，所以说目前是没有解决方法了吗

**Comment by cmradix** [comment]
> > 参考issues #285
> 
> 看完了，所以说目前是没有解决方法了吗

没有，以后估计也没有了，他们现在把审计接入挪到了服务端，审计AI没有上下文还有点笨，也没法依靠上下文欺骗。

**Comment by Gally-Youko** [comment]
> > > 参考issues #285
> > 
> > 
> > 看完了，所以说目前是没有解决方法了吗
> 
> 没有，以后估计也没有了，他们现在把审计接入挪到了服务端，审计AI没有上下文还有点笨，也没法依靠上下文欺骗。

有没有一些提示词可以骗过这个审计AI的，如果以后输出被消失（像newbing那样）就难受了

**Comment by cmradix** [comment]
> > > > 参考issues #285
> > > 
> > > 
> > > 看完了，所以说目前是没有解决方法了吗
> > 
> > 
> > 没有，以后估计也没有了，他们现在把审计接入挪到了服务端，审计AI没有上下文还有点笨，也没法依靠上下文欺骗。
> 
> 有没有一些提示词可以骗过这个审计AI的，如果以后输出被消失（像newbing那样）就难受了

参考下面这个链接自己琢磨，另外屏蔽是在本地发生的，因此可以保留内容但是依然会被审计，别的项目在研究，还得等等。
https://openai.com/policies/usage-policies

**Comment by Gally-Youko** [comment]
> > > > > 参考issues #285
> > > > 
> > > > 
> > > > 看完了，所以说目前是没有解决方法了吗
> > > 
> > > 
> > > 没有，以后估计也没有了，他们现在把审计接入挪到了服务端，审计AI没有上下文还有点笨，也没法依靠上下文欺骗。
> > 
> > 
> > 有没有一些提示词可以骗过这个审计AI的，如果以后输出被消失（像newbing那样）就难受了
> 
> 参考下面这个链接自己琢磨，另外屏蔽是在本地发生的，因此可以保留内容但是依然会被审计，别的项目在研究，还得等等。 https://openai.com/policies/usage-policies

好吧，也就只能这样了，感谢告知
