### ISSUE TITLE
重复执行脚本的bug

### ISSUE THREAD

**Issue by kongsa-0721** [xcanwin/KeepChatGPT#29]
当我点击另外的chatgpt对话的时候，脚本会重新加载，导致插件里面油猴插件数量显示不正确。
例如我进入网站的时候显示1，我点击对话，插件数就显示2。事实上我只开启了一个插件
<img width="1449" alt="image" src="https://user-images.githubusercontent.com/81756106/233050528-cacfd4e6-bb61-4a0a-920c-398f2d56747e.png">

**Comment by xcanwin** [comment]
这是课外题了。
这个数字是油猴的功能之一，显示当前选项卡里执行的插件总数，重复执行的也算，iframe里执行的也算。
