### ISSUE TITLE
在更大的展示的模式下图片显示问题

### ISSUE THREAD

**Issue by ISKAAI** [xcanwin/KeepChatGPT#291]
在wide display mode和code interpreter的模式下chatgpt生成的图片显示也会被拉大，导致体验的下降。能不能只拉伸文字和程序，不要拉伸图片。

**Comment by xcanwin** [comment]
你在chatgpt新建一个新的聊天，弄出你描述的情况
然后F12的控制台里执行：console.log($('.largescreen').outerHTML)
然后把生成的所有内容发出来

**Comment by ISKAAI** [comment]
<img width="1280" alt="image" src="https://github.com/xcanwin/KeepChatGPT/assets/103238376/90c10b5f-8058-4e35-8f2e-ff953314a34b">
<img width="1280" alt="image" src="https://github.com/xcanwin/KeepChatGPT/assets/103238376/93224fee-d31f-4021-a4c7-35d22a41f631">

**Comment by ISKAAI** [comment]
<img width="1085" alt="image" src="https://github.com/xcanwin/KeepChatGPT/assets/103238376/33700368-386f-4f47-813d-87e78972a0b8">
<img width="1087" alt="image" src="https://github.com/xcanwin/KeepChatGPT/assets/103238376/bb3350a5-791c-478e-91b1-f6e7401a3219">
就是图片会随着文字一起拉大，能不能只拉伸文字，图片保持原本的大小

**Comment by xcanwin** [comment]
原来是因为你发源代码时没有用<>代码块
谢谢反馈，已修复。

**Comment by ISKAAI** [comment]
没事，挺喜欢大大的插件的。

**Comment by ISKAAI** [comment]
没事，挺喜欢大大的插件的。如果是居中的就刚好了！
<img width="1074" alt="image" src="https://github.com/xcanwin/KeepChatGPT/assets/103238376/9c9043bc-4186-4aa0-b17b-c757f3ca080c">

**Comment by xcanwin** [comment]
![图片](https://github.com/xcanwin/KeepChatGPT/assets/14187349/deb9b8ac-42af-4549-9039-6b32cdaa2711)
![图片](https://github.com/xcanwin/KeepChatGPT/assets/14187349/857ff115-5b65-4292-9bcc-d8adfebbe1de)
感觉还是靠左好看一点。
如果图片居中了，那图片和你上面那个下拉框就分离了。也就是两个控件分离，会不美观。

**Comment by ISKAAI** [comment]
好的好的 <3
