### ISSUE TITLE
关于chatGPT推荐问题排版的问题

### ISSUE THREAD

**Issue by zengshuaishuai** [xcanwin/KeepChatGPT#295]
最近chatGPT网页版 增加了推荐问题的功能 当查询完问题后 在输入框上方会弹出几个推荐问题。使用KeepChatGPT插件后 会出现排版样式错乱的情况
![WX20230803-231928@2x](https://github.com/xcanwin/KeepChatGPT/assets/47208027/070a604b-54d4-4089-878a-d42d71dcb226)

**Comment by xcanwin** [comment]
我好像还没见到这个推荐问题，你怎么触发这个的，普通账户？发了什么提示词？提供详细信息给我
