### ISSUE TITLE
官方8月3日更新后,违规会话的回复要刷新页面才能看到

### ISSUE THREAD

**Issue by OrochiZ** [xcanwin/KeepChatGPT#296]
感觉最早就这样,后来被脚本解除了,现在脚本不对应版本了吧

**Comment by Arta5500** [comment]
現在取消稽核的功能已經失效，詳細內容去看看相關功能的問題回報，建議不要再要求chatgpt生成違規內容，不然次數過多你的帳號會被限制

**Comment by OrochiZ** [comment]
唉,那样ChatGPT就没有使用的必要了

**Comment by jok606** [comment]
8月8前，還可以透過指令產生限制內容，不過一些比較過激的內容還是會導致紅標，此時會出現ai顯示正在回覆但直到回覆結束都沒有任何內容的情況，這種情況下刷新畫面可以看到你輸入的內容被紅標(警告並刪除)，但ai還是會根據你被刪除的內容回覆、延續文本。可以透過ai已經生成的回覆繼續搞劇情接龍或者問答，不過在這種情況下還是建議重新編輯上一條甚至上上一條內容，因為持續紅標會導致郵箱收到警告信，然後封號。
不過這是8月8日前的情況了，現在的情況是稽核已經再次發揮作用，黃標也開始出現了(原本黃標內容會正常顯示，出現空回覆代表你的內容實際上已經紅標了)

**Comment by OrochiZ** [comment]
8月10日发现又变成只有黄色警告不妨碍输入输出的状态了,这个问题暂时结束了
