### ISSUE TITLE
关于净化页面没有净化搜索建议的问题

### ISSUE THREAD

**Issue by yige-yigeren** [xcanwin/KeepChatGPT#298]
在这一块里面
[1.txt](https://github.com/xcanwin/KeepChatGPT/files/12314151/1.txt)
具体的class
[2.txt](https://github.com/xcanwin/KeepChatGPT/files/12314152/2.txt)

**Comment by xcanwin** [comment]
好奇怪，我一直没弹出提示词建议。你是gpt4？你创建哪类聊天，发送哪些提示词以后出现搜索建议的？

**Comment by yige-yigeren** [comment]
> 好奇怪，我一直没弹出提示词建议。你是gpt4？你创建哪类聊天，发送哪些提示词以后出现搜索建议的？

gpt4，plus，但我也是随机出现的，不太确定这个规律

**Comment by yige-yigeren** [comment]
> 好奇怪，我一直没弹出提示词建议。你是gpt4？你创建哪类聊天，发送哪些提示词以后出现搜索建议的？

很神奇，我这段时间都没弹出来，不知道是不是我清理数据比较频繁的原因（我前段时间没咋用，其他人没清理数据的习惯）

**Comment by yige-yigeren** [comment]
> 好奇怪，我一直没弹出提示词建议。你是gpt4？你创建哪类聊天，发送哪些提示词以后出现搜索建议的？

![image](https://github.com/xcanwin/KeepChatGPT/assets/53390868/11d20fb6-8e1b-43cc-bc17-4a88feb4de21)

在至少3~5个已有聊天后会出现
![image](https://github.com/xcanwin/KeepChatGPT/assets/53390868/f1c4bdbe-0680-4ed5-96e9-515cf7ff7604)
