### ISSUE TITLE
使用插件后出现的问题

### ISSUE THREAD

**Issue by QuietWorker** [xcanwin/KeepChatGPT#3]
偶发1小时频繁提示，解决方式未知

**Comment by xcanwin** [comment]
> 偶发1小时频繁提示，解决方式未知

我也偶尔会出现这个提示，我觉得可能是因为有了这个插件以后，对话太顺畅，效率高了，以致于发送的指令比以前多了，所以就出现这个提示。
同时我也留意一下，说不定官方真的希望我们一小时内频繁刷新的情况下才能多发几个指令。
