### ISSUE TITLE
输入问题之后一回车就报错

### ISSUE THREAD

**Issue by tdbyc** [xcanwin/KeepChatGPT#304]
输入问题之后一回车就报错提示：Application error: a client-side exception has occurred (see the browser console for more information)
![微信截图_20230821092251](https://github.com/xcanwin/KeepChatGPT/assets/95057865/886864be-7a4c-42fe-9a23-345e4621e2e4)

**Comment by xcanwin** [comment]
确实存在这个问题，稍等

**Comment by xcanwin** [comment]
> 输入问题之后一回车就报错提示：Application error: a client-side exception has occurred (see the browser console for more information) ![微信截图_20230821092251](https://user-images.githubusercontent.com/95057865/261889767-886864be-7a4c-42fe-9a23-345e4621e2e4.png)

谢谢反馈，已修复bug。

**Comment by zktzktzkt** [comment]
控制台打印疯狂报错，直接卡死了

**Comment by xcanwin** [comment]
> 控制台打印疯狂报错，直接卡死了，我更新了最新版17.6也不行

有控制台截图吗

**Comment by zktzktzkt** [comment]
> > 控制台打印疯狂报错，直接卡死了，我更新了最新版17.6也不行
> 
> 有控制台截图吗

我不敢打开了，一秒上百条报错，我怕号封了，但是我记得之前我把新增的那个敏感信息正则的都删了，然后又设置了时间是99999999，然后就出现这个问题了
