### ISSUE TITLE
展示大屏和展示全屏有问题

### ISSUE THREAD

**Issue by SDMsuper** [xcanwin/KeepChatGPT#305]
今天早上打开的时候发现界面排版回到了原来的风格，展示大屏的按钮也无法切换

**Comment by tdbyc** [comment]
![微信截图_20230825091857](https://github.com/xcanwin/KeepChatGPT/assets/95057865/fd4137a8-d044-4e90-8405-2c08f5487f85)
是的，我也发现了

**Comment by tdbyc** [comment]
最近这几天好像变得没以前稳定了

**Comment by energyc99** [comment]
我也是，今天新出现的问题。

**Comment by QR-0W** [comment]
我也出现了这个问题

**Comment by wxdespair** [comment]
同样问题+1，又像原本一样挤在中间了

**Comment by 666dechaoge** [comment]
一样的问题

**Comment by wanzhiyu** [comment]
同样的问题

**Comment by Zheap** [comment]
一样，感觉大屏功能还是很重要的

**Comment by hunmeng** [comment]
![image](https://github.com/xcanwin/KeepChatGPT/assets/50135837/7c5144b8-5e8c-46f6-b9de-45c6fcf49181)
临时解决方法，把max-width改一下就好了，

**Comment by xcanwin** [comment]
展示大屏和展示全屏功能的bug已修复，谢谢大家反馈
