### ISSUE TITLE
插件失效了

### ISSUE THREAD

**Issue by wwq0702** [xcanwin/KeepChatGPT#307]

**Comment by domenicalter** [comment]
是的，宽屏显示失效了，而且，防止打断和防止跟踪也用不了了

**Comment by CyshallChan** [comment]
+1

**Comment by COPELONG** [comment]
展示全屏功能失效

**Comment by daytime001** [comment]
展示全屏挂了！！！

**Comment by xcanwin** [comment]
展示大屏和展示全屏功能的bug已修复，谢谢大家反馈

**Comment by kelomina** [comment]
> 展示大屏和展示全屏功能的bug已修复，谢谢大家反馈

但是防打断仍然没被修复

**Comment by CyshallChan** [comment]
> > 展示大屏和展示全屏功能的bug已修复，谢谢大家反馈
> 
> 但是防打断仍然没被修复

+1，刚刚才发现

**Comment by xcanwin** [comment]
> > 展示大屏和展示全屏功能的bug已修复，谢谢大家反馈
> 
> 
> 
> 但是防打断仍然没被修复

初步看了是从服务端层面强行打断，而且gpt4回复的时长比gpt3还短，居然没优待plus用户。
