### ISSUE TITLE
KeepChatGPT.user.js安装在哪

### ISSUE THREAD

**Issue by WAYSC** [xcanwin/KeepChatGPT#31]

**Comment by wengchaoxi** [comment]
1. 先去安装 [油猴插件](https://www.tampermonkey.net/)
2. 然后点击 [安装 KeepChatGPT](https://raw.githubusercontent.com/xcanwin/KeepChatGPT/main/KeepChatGPT.user.js)

**Comment by WAYSC** [comment]
好的👌🏻
