### ISSUE TITLE
出现Cloudflare 真人验证

### ISSUE THREAD

**Issue by ccbond** [xcanwin/KeepChatGPT#314]
3.5不会出现 但是4就会出现。而且每次必现！
<img width="563" alt="image" src="https://github.com/xcanwin/KeepChatGPT/assets/49605145/fabdc794-37ed-4d75-91cf-a8ef44aa0b20">

**Comment by xcanwin** [comment]
你的魔法存在被cf认为有必要验证真人。换个魔法。

**Comment by Shinkai007** [comment]
我在国外.....现在一直也出现....有救么....前几天还没事,不知道怎么了.

**Comment by xcanwin** [comment]
> 我在国外.....现在一直也出现....有救么....前几天还没事,不知道怎么了.

你国外所用的网络的同c段可能有黑产之类的，经常触发cf的风控规则。最好的解决方式是用贵的运营商，门槛高了，以网络攻击为主业的同c段的网上邻居就比较少。

**Comment by yige-yigeren** [comment]
> 我在国外.....现在一直也出现....有救么....前几天还没事,不知道怎么了.

直接开cf自家梯子，或者安装浏览器privacypass插件 https://github.com/privacypass/challenge-bypass-extension

**Comment by JoeCao** [comment]
我也是这个问题，昨天刚出现，安装了privacypass插件不管用。 @yige-yigeren 有什么解决办法么？

**Comment by yige-yigeren** [comment]
> 我也是这个问题，昨天刚出现，安装了privacypass插件不管用。 @yige-yigeren 有什么解决办法么？

那我就不清楚了，我平时开1.1.1.1或者直连，有privacypass，基本不会跳验证

**Comment by MILKMILKKING** [comment]
我从昨天开始也同样出现了这个，每个提问都会出现，而且还是每次需要答10个题，这个验证环节非常繁琐。

**Comment by MILKMILKKING** [comment]
> 我在国外.....现在一直也出现....有救么....前几天还没事,不知道怎么了.

请问你现在解决了这个问题了吗？如果解决了的话，你是如何操作的呢？

**Comment by raincoast** [comment]
> > 我在国外.....现在一直也出现....有救么....前几天还没事,不知道怎么了.
> 
> 请问你现在解决了这个问题了吗？如果解决了的话，你是如何操作的呢？

我前几天也是，发一个问题弹一次验证码，后来换了一个梯子就好了，再换回去就还是这样，应该是ip黑了。

**Comment by HeXis-YS** [comment]
> > > 我在国外.....现在一直也出现....有救么....前几天还没事,不知道怎么了.
> > 
> > 
> > 请问你现在解决了这个问题了吗？如果解决了的话，你是如何操作的呢？
> 
> 我前几天也是，发一个问题弹一次验证码，后来换了一个梯子就好了，再换回去就还是这样，应该是ip黑了。

可以试一下把浏览器或者系统的时区改成梯子服务器所在地的时区。
