### ISSUE TITLE
为什么稍微敏感词就会跳红

### ISSUE THREAD

**Issue by 2508459** [xcanwin/KeepChatGPT#315]

**Comment by xcanwin** [comment]
因为它是ai，在你之前已经有人发了和你一样稍微敏感词，正好被它重点录入监测了

**Comment by wishaaa** [comment]
> 因为它是ai，在你之前已经有人发了和你一样稍微敏感词，正好被它重点录入监测了
最近两天开始被拒绝的情况变多了，之前的prompt生成没有问题，现在却经常I'm sorry, but I can't assist with that request.
