### ISSUE TITLE
Unable to load history

### ISSUE THREAD

**Issue by maoqiaosu** [xcanwin/KeepChatGPT#320]
这个问题安装了，还是没法解决，请问是什么原因呢？

**Comment by xcanwin** [comment]
使用本插件之前就出现的问题？
换个浏览器，或者看看左下角的官方设置是不是设置了不记录历史

**Comment by maoqiaosu** [comment]
您好，您的邮件向前已经收到，我会尽快查看回复，感谢您的来信。

**Comment by yanik2333** [comment]
我也是这个问题，在安装之后将全部一起选上然后重新加载，就会出现这种错误。。。
如果你直接在关闭功能前删除插件的话，后果...可能就那样的，根本用不成CHATGPT的那种...

**Comment by yanik2333** [comment]
![Uploading image.png…]()

**Comment by yanik2333** [comment]
如果有我隐私方面的问题，请维护大大尽快指出让我删除上条message，也得感谢

**Comment by xcanwin** [comment]
> 如果有我隐私方面的问题，请维护大大尽快指出让我删除上条message，也得感谢

看起来像是你浏览器有其他的拓展，比如广告拦截插件，然后那个插件不允许openai.com读取自身iframe内容，导致请求 https://chat.openai.com/api/auth/session 过于频繁。解决办法是关闭其他拓展、或者换个没怎么安装拓展的浏览器试试。
