### ISSUE TITLE
在开启若干选项后，my plan按钮消失

### ISSUE THREAD

**Issue by RSCTQ** [xcanwin/KeepChatGPT#323]
![屏幕截图 2023-10-22 232206](https://github.com/xcanwin/KeepChatGPT/assets/148704942/b179c3d9-86b1-4664-980a-b4d7458d7301)
![屏幕截图 2023-10-22 231112](https://github.com/xcanwin/KeepChatGPT/assets/148704942/a96b3acf-a05b-4a40-be55-b2b8a48cdd4e)

**Comment by RSCTQ** [comment]
更正一下，应该是点击左下角用户，my plan快速出现，然后又快速消失。

**Comment by xcanwin** [comment]
是的，净化页面会净化多余元素，像my plan这类每个月使用次数小于等于1次的功能，也会进行净化
