### ISSUE TITLE
显示调试显示不出来

### ISSUE THREAD

**Issue by A6083450** [xcanwin/KeepChatGPT#326]
<img width="655" alt="image" src="https://github.com/xcanwin/KeepChatGPT/assets/34879801/7a51699c-2a54-436d-8aeb-f732d242c999">
清除了缓存也是这样没显示出调试

**Comment by xcanwin** [comment]
不影响保持活跃的功能。
这与 https://chat.openai.com/ 页面的内容安全策略CSP有关，它设置了：frame-src tcr9i.chat.openai.com challenges.cloudflare.com js.stripe.com
