### ISSUE TITLE
中国手机无法注册OPENAI，我该如何解决该问题？能给我一些提示吗？

### ISSUE THREAD

**Issue by guhuan769** [xcanwin/KeepChatGPT#327]
![image](https://github.com/xcanwin/KeepChatGPT/assets/46043439/0ad29c30-c89c-4fac-86ed-29882cdb2c7d)

**Comment by johngao01** [comment]
中国大陆手机都不行，可以使用sms active平台注册，具体搜索

**Comment by mycurjerry** [comment]
如果就用3.5购买一个成品号差不多也就1元

**Comment by guhuan769** [comment]
> 据说已经不需要手机号了

![Screenshot_2023-11-27-19-15-43-40_df198e732186825c8df26e3c5a10d7cd.jpg](https://github.com/xcanwin/KeepChatGPT/assets/46043439/6da23e97-7d16-4c04-995c-a497584d6651)

**Comment by donkeyyu** [comment]
你这是注册google账号吧，用接码平台sms-activate
