### ISSUE TITLE
插件失效了？

### ISSUE THREAD

**Issue by AliceNEET** [xcanwin/KeepChatGPT#330]
今天晚上登录chatgpt，想复制会话，发现不能用了，然后我以为是插件没开，发现是开的。然后发现插件的图标都没有了（金色的那个），重新安装也没有用。

我用的是
浏览器:Microsoft Edge 版本 119.0.2151.44 (正式版本) (64 位)
篡改猴  4.19.0

另外，之前chatgpt冒出来了一个alpha测试计划，我选择了加入，不知道跟这个有没有关系。

**Comment by xxyz45** [comment]
一样的问题，我也遇到了

**Comment by yunchenran** [comment]
Chrome 最新版本 119.0.6045.106，同样失效

**Comment by songxff** [comment]
我也出现了相同的问题

**Comment by vnsnclo** [comment]
把
const symbol1_selector = 'nav.flex .transition-colors';
改为
const symbol1_selector = 'nav.flex .mb-1';

**Comment by liuguangchuang** [comment]
Edge、Chrome 都不行了

**Comment by liuguangchuang** [comment]
> 把 const symbol1_selector = 'nav.flex .transition-colors'; 改为 const symbol1_selector = 'nav.flex .mb-1';

改了之后，可以了

**Comment by P0larls** [comment]
> 把 const symbol1_selector = 'nav.flex .transition-colors'; 改为 const symbol1_selector = 'nav.flex .mb-1';

感谢分享.

**Comment by xeason11** [comment]
> 把 const symbol1_selector = 'nav.flex .transition-colors'; 改为 const symbol1_selector = 'nav.flex .mb-1';

牛犇

**Comment by Javanbe** [comment]
> 把
> const symbol1_selector = 'nav.flex .transition-colors';
> 改为
> const symbol1_selector = 'nav.flex .mb-1';

牛逼解决了

**Comment by xcanwin** [comment]
谢谢各位反馈，已在版本18.4上修复
