### ISSUE TITLE
失效

### ISSUE THREAD

**Issue by afterexam** [xcanwin/KeepChatGPT#332]
开了插件和没开一样 , 左上角没有标了
浏览器: edge
win11

**Comment by qqqqtrident** [comment]
同失效
浏览器: edge 118.0.2088.76 
win11

**Comment by lienzzzz** [comment]
chrome更新到最新版(118.0.5993.120)后也失效了

**Comment by hhuzzz** [comment]
https://github.com/xcanwin/KeepChatGPT/issues/330#issuecomment-1793473450

**Comment by rongrongrong233** [comment]
今天作者已经做了更新
油猴的话重新更新脚本，重新刷新页面就行了

**Comment by xcanwin** [comment]
最新版已修复
