### ISSUE TITLE
页面更新了 gpt4 plus 用户的  插件 现在用不了了 

### ISSUE THREAD

**Issue by mflxiaocainiao** [xcanwin/KeepChatGPT#334]

**Comment by Magnificentcxx** [comment]
有谁和我一样吗？：通过CloudFlare的机器人验证进去GPT后，不显示历史提问、Plus用户无法正常显示？

**Comment by mmeng01** [comment]
+1

**Comment by mmeng01** [comment]
我和楼上问题一样

**Comment by xzf1234** [comment]
+10086

**Comment by xzf1234** [comment]
球更新！！！ @xcanwin

**Comment by chenxuhl** [comment]
+1

**Comment by guanzhujiaran** [comment]
报错429 too many requests ，502 Bad Gateway  ，503 Service Unavailable

**Comment by ecust-bes2022** [comment]
昨天chatgpt大更新，崩了一天，现在更新后原来的keepchatgpt不能使用了，现在来催更啦

**Comment by mflxiaocainiao** [comment]
现在的问题是 网页端 调试工具打开后 调成手机端网页 可以使用 但是网页端的还是不行 是不是css需要变化

**Comment by xcanwin** [comment]
gpt4用户据说页面变化很大，需要共享一下页面给我调试一下css。
对着最顶部的```<html>```标签也就是第二行，右键，复制，复制outerHTML
![图片](https://github.com/xcanwin/KeepChatGPT/assets/14187349/fcac4f2a-473f-4d50-878a-3ecef23f7c22)

**Comment by xiaobaozi233** [comment]
> gpt4用户据说页面变化很大，需要共享一下页面给我调试一下css。 对着最顶部的`<html>`标签也就是第二行，右键，复制，复制outerHTML

[inde.txt](https://github.com/xcanwin/KeepChatGPT/files/13314193/inde.txt)

**Comment by Shangcai-Meng** [comment]
[Uploading gpt4.txt…]()

**Comment by khywjt** [comment]
现在有什么办法可以通过调整恢复吗，关了插件清空了cookie后还是不行。

**Comment by khywjt** [comment]
> 现在有什么办法可以通过调整恢复吗，关了插件清空了cookie后还是不行。

好像是需要等一段时间就好了

**Comment by lingmingyu** [comment]
感觉现在这个插件没有什么用了，更新之后感觉也不断流了

**Comment by yuewander** [comment]
> gpt4用户据说页面变化很大，需要共享一下页面给我调试一下css。 对着最顶部的`<html>`标签也就是第二行，右键，复制，复制outerHTML ![图片](https://user-images.githubusercontent.com/14187349/281595959-fcac4f2a-473f-4d50-878a-3ecef23f7c22.png)

[debug.zip](https://github.com/xcanwin/KeepChatGPT/files/13318477/debug.zip)

**Comment by 99665** [comment]
+1

**Comment by xcanwin** [comment]
周末花了些时间调试了大家反馈的需求，大家试试版本v19.1
