### ISSUE TITLE
今天KeepChatGPT还能用吗？

### ISSUE THREAD

**Issue by STJKWSSY** [xcanwin/KeepChatGPT#335]
今天KeepChatGPT突然开始报错了，然后从油猴上关掉之后，纯chatgpt也不行了 一直Something went wrong. If this issue persists please contact us through our help center at help.openai.com. ，有没有解决的兄弟们

**Comment by Young0ne018** [comment]
我也遇到了这个问题，但是跟我用同一个账号的朋友就是正常的。

**Comment by YYYYYYase** [comment]
我是plus用户，也在今天下午遇到了相同的问题，不是KeepChatGPT的锅，纯净ChatGPT也用不了

**Comment by arroe99** [comment]
'Something went wrong. If this issue persists please contact us through our help center at help.openai.com'

same problem  咋搞

**Comment by YYYYYYase** [comment]
Only wait :(

**Comment by beiju2813837083** [comment]
使用chatgpt持续报错，Something went wrong. If this issue persists please contact us through our help center at help.openai.com.，通过抓取请日志请求发现，发送请求时
**请求网址:
https://chat.openai.com/backend-api/conversation
请求方法:
POST
状态代码:
403 Forbidden**
服务器拒绝了请求，通过更换浏览器不使用keepgpt可以正常使用

**Comment by qqbnb889** [comment]
昨天就开始不好用，今天上午能用，下午开始报错“Something went wrong. If this issue persists please contact us through our help center at help.openai.com.”使用safari浏览器正常使用，chrome报错，不知道为什么

**Comment by shuttworth** [comment]
今天纯净GPT也用不了

**Comment by svnkxmza** [comment]
https://status.openai.com/ 还没恢复前,应该减少报告这些"Something went wrong"的错误

**Comment by LichiTI** [comment]
火狐浏览器没问题，现在禁止chrome内核的

**Comment by lingmingyu** [comment]
更新改版了，可能需要他来解决这个问题

**Comment by 97wow** [comment]
清空cookie 可以解决
Clear Cookie will work

**Comment by onebull** [comment]
11月9号很多人用不了。凌晨才好。好像是下午被攻击了。
不过keepchatgpt好像失效了。
用惯全屏一下不习惯了。

**Comment by xcanwin** [comment]
大家试试版本v19.1

**Comment by onebull** [comment]
作者真是太好了。可以用了。又可以全屏了。真棒。
