### ISSUE TITLE
不知道为什么我总会遇到429错误，然后就是始终无法load history

### ISSUE THREAD

**Issue by khywjt** [xcanwin/KeepChatGPT#338]
![image](https://github.com/xcanwin/KeepChatGPT/assets/126787577/5dd55c09-e6d7-4418-8374-6d7d0e0120db)

**Comment by khywjt** [comment]
偶尔清空cookies重新登陆会好，但经常又不行了，我不清楚是我的浏览器问题还是账号问题

**Comment by xcanwin** [comment]
429有非常多的原因，openai官网也有提到，可以在Readme搜429

**Comment by xcanwin** [comment]
如果你的网络比较靠谱，间隔可以调整为900秒

**Comment by khywjt** [comment]
> 如果你的网络比较靠谱，间隔可以调整为900秒
请教一下这个操作怎么处理呢

**Comment by xcanwin** [comment]
keepchatgpt的菜单栏里的调整间隔，数字改为900
