### ISSUE TITLE
桌面版添加

### ISSUE THREAD

**Issue by one-plusone** [xcanwin/KeepChatGPT#34]
请问该插件可以在windowsChatGPT 桌面应用中使用吗，可以的话要怎么操作呀

**Comment by xcanwin** [comment]
我看到两个issue：
https://github.com/lencx/ChatGPT/issues/761
https://github.com/lencx/ChatGPT/issues/838
梯子问题。
我觉得桌面版能实现的东西会比浏览器插件更多，还能实现系统级的指令，你可以等lencx大佬的更新。
