### ISSUE TITLE
多账户管理问题

### ISSUE THREAD

**Issue by Wind010321** [xcanwin/KeepChatGPT#340]
你好，请问有管理同一账号不同人使用的方法吗？ 我是通过microsoft账号登陆的chatgpt，之前有两个人在合用，现在我想删除另外一方的使用权限，请问有方法吗？

**Comment by xcanwin** [comment]
你通过一款AI搜索引擎找到本项目，其实应该把AI搜索引擎用起来
![图片](https://github.com/xcanwin/KeepChatGPT/assets/14187349/caa06087-1dd1-4b92-8d06-ebb57864fbe6)
本issue超纲了

**Comment by mflxiaocainiao** [comment]
改密码呗
