### ISSUE TITLE
[Bug] 克隆对话You字样被错误克隆

### ISSUE THREAD

**Issue by yige-yigeren** [xcanwin/KeepChatGPT#342]

**Comment by yige-yigeren** [comment]
![image](https://github.com/xcanwin/KeepChatGPT/assets/53390868/c484c843-12bb-450e-8ce3-e18742b94f0a)
点击后You 和 Chatgpt也会被复制

**Comment by AliceNEET** [comment]
如果有多个对话，页码也会被复制。

类似如：
2 / 2

如果复制chatgpt的内容，chatgpt也会被复制。

类似如：
ChatGPT

**Comment by xcanwin** [comment]
最新版已修复

**Comment by yige-yigeren** [comment]
> 最新版已修复

感谢，确认已经修复
