### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'addEventListener')

### ISSUE THREAD

**Issue by kycool** [xcanwin/KeepChatGPT#344]
![截屏2023-11-14 下午1 54 16](https://github.com/xcanwin/KeepChatGPT/assets/2993403/5662466d-42a7-4192-872a-d13074842d38)
点击跳转的源码位置如下
![截屏2023-11-14 下午1 53 55](https://github.com/xcanwin/KeepChatGPT/assets/2993403/fc738b76-5fce-4bf3-bec4-2348451f92e5)

这种错误已经出现了多次

**Comment by xcanwin** [comment]
这个一般是因为那个页面的聊天框消失了，比如网络突然断了、发送敏感关键词等
