### ISSUE TITLE
“KeepChatGPT”的图标能否下移，现在有点顶到最上端了

### ISSUE THREAD

**Issue by majiajin2043** [xcanwin/KeepChatGPT#346]
<img width="374" alt="屏幕截图 2023-11-15 140005" src="https://github.com/xcanwin/KeepChatGPT/assets/73528988/bdcc13b7-29eb-466f-a05f-f927626598f5">‘’
如图，有点顶到最上方了，下移几格观感会更好

**Comment by majiajin2043** [comment]
<img width="1280" alt="屏幕截图 2023-11-15 140420" src="https://github.com/xcanwin/KeepChatGPT/assets/73528988/327b07ae-b983-4cfd-a476-7fbd002eb5b6">
全屏的图

**Comment by cboss6** [comment]
同意，感觉有点不太协调

**Comment by xcanwin** [comment]
其实左上角那个chatgpt按钮是new chat，你们可以暗色主题
