### ISSUE TITLE
debug mode not work

### ISSUE THREAD

**Issue by yxmnjxzx** [xcanwin/KeepChatGPT#349]
打开show debuging，工作失效
![image](https://github.com/xcanwin/KeepChatGPT/assets/95153568/8ee97f0f-d3ae-46d3-a49c-1ce0b2c7f0ed)

**Comment by xcanwin** [comment]
是因为浏览器的csp。不影响使用的

**Comment by xcanwin** [comment]
是因为浏览器的csp。不影响使用的
