### ISSUE TITLE
为什么还是会出现这个

### ISSUE THREAD

**Issue by CatZui** [xcanwin/KeepChatGPT#35]
![image](https://user-images.githubusercontent.com/106656694/233248023-c86b50c0-fbf3-4c3b-ba1d-d89ed03f4236.png)

**Comment by bababababamu** [comment]
为什么还是会出现这个
为什么还是会出现这个
为什么还是会出现这个
为什么还是会出现这个
为什么还是会出现这个

**Comment by bitqiang** [comment]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/13163400/233252473-2cbce648-cada-4ed3-b29f-ce6368e3a830.png">

**Comment by bitqiang** [comment]
能加个自动点击的功能？随机100-300ms点击

**Comment by swainsk** [comment]
+1 还是有这个问题。

**Comment by Kobe-respect** [comment]
+1

**Comment by zyoung1212** [comment]
+1

**Comment by xcanwin** [comment]
我已经有办法了，我会在今晚更新。

**Comment by Kobe-respect** [comment]
> 我已经有办法了，我会在今晚更新。

其实，我感觉挺好用的，我挂了半小时都不会掉

**Comment by xcanwin** [comment]
> > 我已经有办法了，我会在今晚更新。
> 
> 其实，我感觉挺好用的，我挂了半小时都不会掉

谢谢反馈。
我内测了半个月没掉线过，公测发布了快一个月也没掉线过。
但是有不少用户的网络掉得严重，估计和他们使用的机房ip被cf重点关注有关。我已经想到办法尝试解决他们的问题了。

**Comment by CatZui** [comment]
> 
好的 期待你的更新

**Comment by CatZui** [comment]
> 我已经有办法了，我会在今晚更新。

更新了能滴滴我一下嘛，谢谢

**Comment by kongsa-0721** [comment]
> 我已经有办法了，我会在今晚更新。

https://github.com/xcanwin/KeepChatGPT/issues/29 大佬也关注下这个，心里有蚂蚁在爬。

**Comment by xcanwin** [comment]
> > 我已经有办法了，我会在今晚更新。
> 
> 更新了能滴滴我一下嘛，谢谢

@CatZui 调节频率试试

**Comment by Kevin-free** [comment]
> > > 我已经有办法了，我会在今晚更新。
> > 
> > 
> > 更新了能滴滴我一下嘛，谢谢
> 
> @CatZui 调节频率试试

请问频率调多少好？ 我使用默认的30，今天老是 Error，不知道是不是tz出问题了

**Comment by xcanwin** [comment]
> > > > 我已经有办法了，我会在今晚更新。
> 
> > > 
> 
> > > 
> 
> > > 更新了能滴滴我一下嘛，谢谢
> 
> > 
> 
> > @CatZui 调节频率试试
> 
> 
> 
> 请问频率调多少好？ 我使用默认的30，今天老是 Error，不知道是不是tz出问题了

参考readme底部的说明
