### ISSUE TITLE
下载插件没反应

### ISSUE THREAD

**Issue by vaefei** [xcanwin/KeepChatGPT#350]
下载了插件用不了是什么情况，油猴插件已启用，但是就是不显示这个KeepChatGPT插件

**Comment by BFNOC** [comment]
估计是因为官方升级的界面，我刚进去发现整个界面跟以前都不一样了

**Comment by vaefei** [comment]
好的，期待升级插件，我还没用呢就被和谐了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月16日(星期四) 下午3:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xcanwin/KeepChatGPT] 下载插件没反应 (Issue #350)





 
估计是因为官方升级的界面，我刚进去发现整个界面跟以前都不一样了

**Comment by xcanwin** [comment]
已更新

**Comment by vaefei** [comment]
好的好的，谢谢大佬，膜拜大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月17日(星期五) 凌晨0:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xcanwin/KeepChatGPT] 下载插件没反应 (Issue #350)





 
已更新

**Comment by vaefei** [comment]
大佬，在吗？帮忙看一眼，插件开关不显示是因为什么原因了，谢谢您。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xcanwin/KeepChatGPT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月17日(星期五) 凌晨0:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xcanwin/KeepChatGPT] 下载插件没反应 (Issue #350)





 
已更新

**Comment by xcanwin** [comment]
点右上角的油猴图标，管理面板，删除keepchatgpt，回到本github项目首页重新安装keepchatgpt
