### ISSUE TITLE
展示大屏功能失效

### ISSUE THREAD

**Issue by wanzhiyu** [xcanwin/KeepChatGPT#354]
只能看到输入框变宽，但是对话区域还是没有变宽，和以前的效果不一样了

**Comment by Shangcai-Meng** [comment]
是的

**Comment by xcanwin** [comment]
谢谢反馈，已在21.5更新修复

**Comment by Mr54233** [comment]
21.6版本好像又失效了？

**Comment by wanzhiyu** [comment]
> 21.6版本好像又失效了？

可以用，2023年11月28日16点53分，更新后刷新页面，甚至重启浏览器。

**Comment by Mr54233** [comment]
> > 21.6版本好像又失效了？
> 
> 可以用，2023年11月28日16点53分，更新后刷新页面，甚至重启浏览器。 当然不排除A/B测试的可能，之前遇到过。

重启浏览器可以了
