### ISSUE TITLE
Confused whether the plugin is working or not.

### ISSUE THREAD

**Issue by xenstar** [xcanwin/KeepChatGPT#355]
Before the plugin was active it used to show a logo of the plugin.

![image](https://github.com/xcanwin/KeepChatGPT/assets/55502651/47d386e2-ae63-43eb-9365-89ba143ecbca)

**But in my chatgpt, there's no logo, but the plugin is active:**

![image](https://github.com/xcanwin/KeepChatGPT/assets/55502651/d17b1005-11e6-4947-b071-7d68f52cb6a7)

I am confused, about whether the plugin is working or not. Since I didn't use chatgpt for last 2 months and more using claude, not sure what changed.

**Comment by xcanwin** [comment]
升级
