### ISSUE TITLE
更新插件后pc端上下滑动鼠标变得非常卡顿

### ISSUE THREAD

**Issue by SakuBorder** [xcanwin/KeepChatGPT#359]
更新插件后pc端上下滑动鼠标变得非常卡顿，关闭插件后卡顿消失

**Comment by JasonSanYe** [comment]
确实最近 卡的很不知道为什么

**Comment by MavisTok** [comment]
是的 要卡蛮久，整个页面无法滑动

**Comment by xcanwin** [comment]
上周开启插件和取消插件都卡。
这两天openai看起来修复了，开启插件和取消插件都正常。

**Comment by MavisTok** [comment]
我尝试过新开一个对话 发送同样的内容，新对话很流畅，在一个旧对话当中会卡顿，怀疑是由于旧对话的缓存过大导致的
