### ISSUE TITLE
拦截红色违反政策错误

### ISSUE THREAD

**Issue by Airtale-96** [xcanwin/KeepChatGPT#361]
使用chatgpt过程中，有时会遇到能够作出回答，但是回答结束后内容立即消失，被替换为红色的违反政策警告。不知道有没有可能通过脚本拦截这种内容替换的动作，从而保留回答内容。

**Comment by xcanwin** [comment]
思路不错，欢迎大家提交PR

**Comment by Airtale-96** [comment]
> 思路不错，欢迎大家提交PR

不知道有没有什么关键词，对网页相关技术了解还是少，如果能提供一个大致方向我也可以进行尝试

**Comment by xcanwin** [comment]
有兴趣的话可以试试。
拿目前版本v21.6讲，hookFetch函数用于篡改请求和篡改返回值。
921行开始，```fetchRsp = target.apply(thisArg, argumentsList);```之前，进行一系列IF判断和处理，是篡改请求的URL，或者不请求直接伪造返回值。
947行开始，```fetchRsp = target.apply(thisArg, argumentsList);```之后，进行一系列IF判断和处理，是篡改返回值，或者拿到返回值第一时间做一些动作。

**Comment by jojo351515** [comment]
期待，回复一个师姐也会被拦截，英语好像没有师姐的概念
