### ISSUE TITLE
打开暗色主题聊天界面仍然是白色

### ISSUE THREAD

**Issue by wang135531** [xcanwin/KeepChatGPT#363]
![b6f999b546a31af5933b400bd201d18](https://github.com/xcanwin/KeepChatGPT/assets/155045419/7a0f0212-867e-4288-8e01-4bd8d293b152)

**Comment by ICLiuLi** [comment]
使用官方暗色主题

**Comment by Gally-Youko** [comment]
我也遇上了:Issue #379
但我更喜欢以前的UI
