### ISSUE TITLE
24年起Can't log in openai.com

### ISSUE THREAD

**Issue by RamonaCY** [xcanwin/KeepChatGPT#364]
已启用篡改猴，keepchatgpt最新版本23/11/09，元旦回公司后，登陆显示OpenAI's services are not available in your country.
已清除Chrome中的缓存记录，没用；重启Wi-Fi和电脑均没用……
啊有人有同样问题吗

**Comment by LaciaType** [comment]
这是网络问题，更改代理节点（美国之类的）大概可以解决。
![image](https://github.com/xcanwin/KeepChatGPT/assets/91367638/7495abeb-95a1-4b1a-aaf8-e9bb08641c88)
