### ISSUE TITLE
为撒我用了插件后没什么变化

### ISSUE THREAD

**Issue by AkatoshSword** [xcanwin/KeepChatGPT#37]
用的微软的edge浏览器，依然会有Something went wrong. If this issue persists please contact us through our help center at help.openai.com.这种报错，还是得不停刷新页面

**Comment by 7nami** [comment]
Same.

**Comment by AkatoshSword** [comment]
今天好像有用了，换了下VPN节点，偶尔还有报错，不过等几秒再问又好了
