### ISSUE TITLE
不知作者是否考虑支持一下userscript呢？

### ISSUE THREAD

**Issue by JimmyXoda** [xcanwin/KeepChatGPT#370]
现在是貌似在safari里面没有办法唤出keepchatgpt的界面，我是用userscript的，不知道是否有技术难度，感谢！

**Comment by SweeTisG00D** [comment]
> 现在是貌似在safari里面没有办法唤出keepchatgpt的界面，我是用userscript的，不知道是否有技术难度，感谢！

你用stay就能解决这个问题，我在safari中用stay完美解决了这个问题

**Comment by xcanwin** [comment]
userscripts 的用户体验和它的作者对油猴脚本的支持评价参考：https://github.com/xcanwin/KeepChatGPT/issues/121
