### ISSUE TITLE
keepchatgpt bug

### ISSUE THREAD

**Issue by gfy6666** [xcanwin/KeepChatGPT#371]
打开插件会导致历史会话无法正常打开，并且无法逐字跳出，等待一段时间后一起跳出答案。并且无法删除会话。这些情况是从今天下午开始的，之前没有，不知道是为什么，关闭插件一切正常。

**Comment by gfy6666** [comment]
补充：主要是不会逐字显现这个问题（等待一段时间一起跳出来），其他问题有时候会出现，有时候就没有，不知道是我浏览器的问题还是该插件的问题

**Comment by xcanwin** [comment]
谢谢反馈，已在v22.2中修复
