### ISSUE TITLE
代码块在页面滚动时显示异常

### ISSUE THREAD

**Issue by KuiznLove** [xcanwin/KeepChatGPT#372]
![image](https://github.com/xcanwin/KeepChatGPT/assets/55416875/e0bd593d-6422-43cb-803a-b0270f0e5030)
用鼠标滚轮或拖动右侧滚动条均会触发，
切换标签页或切换浏览器窗口大小会恢复正常。

**Comment by xcanwin** [comment]
没复现成功，试试v22.2有无改善。
