### ISSUE TITLE
keepchatgpt bug BUG

### ISSUE THREAD

**Issue by boz14676** [xcanwin/KeepChatGPT#374]
https://github.com/xcanwin/KeepChatGPT/issues/371
打开插件会导致历史会话无法正常打开，并且无法逐字跳出，等待一段时间后一起跳出答案。并且无法删除会话。这些情况是从今天下午开始的，之前没有，不知道是为什么，关闭插件一切正常。
----------------------------------------------------------------------------------------------------------------------------------

这是之前的问题，但是现在升级到22.2还是有问题的，就是可能刚开始出来几个文字，然后就卡住了，最后所有文字一起跳出来，今天上午复现该问题有三次了，网络没问题，是稳定的

**Comment by nacl10h2o** [comment]
我的是一直不逐字跳出，必须刷新网页才能看到已经生成好的回答
