### ISSUE TITLE
【体验优化】取消检查更新弹窗

### ISSUE THREAD

**Issue by anyshift** [xcanwin/KeepChatGPT#375]
春节愉快~

正文：如标题所示，普通使用者不太关心当前是xx版本，反而非常影响 Chat 的体验。感觉每次打开 ChatGPT，都会有 “当前是 xxx 版本，已是最新版本” 的弹窗，不胜其扰了...

**Comment by Cp0204** [comment]
除了让我多点一下，没有任何作用。

**Comment by xcanwin** [comment]
已更正，可以更新到24.3体验
