### ISSUE TITLE
请作者大大添加个选择以前UI的开关选项

### ISSUE THREAD

**Issue by Gally-Youko** [xcanwin/KeepChatGPT#379]
因为习惯以前的接近原生的UI界面了，自动更新后不习惯新UI界面，本人有点小强迫症想重新回到以前接近原生的UI界面，希望作者可以添加个开关让用户自己选择是否以新UI显示，谢谢！
![image](https://github.com/xcanwin/KeepChatGPT/assets/138993330/c1a4b59f-d291-4c21-8a7a-63c7b1cbb0d3)
PS：本人用的浏览器（星愿浏览器）打开了暗色主题开关失效，但切换到Edge浏览器则没有问题。

**Comment by Gally-Youko** [comment]
一个个版本回退，22.2是我想要保持的旧UI
![屏幕截图 2024-02-22 002844](https://github.com/xcanwin/KeepChatGPT/assets/138993330/4b67cbbb-cf7f-4c4a-a113-251bd770b1b9)

**Comment by xcanwin** [comment]
已更正，可以更新到24.2体验
