### ISSUE TITLE
希望能提供恢复原版纯色侧边栏的选项

### ISSUE THREAD

**Issue by merrkry** [xcanwin/KeepChatGPT#381]
23.0 之后增加了非常多的样式更改，遗憾的是这些更改并不是可选的，希望能够和脚本中其他功能一样，以可选功能的方式提供。

---

这个插件真的极大改善了 ChatGPT 网页的体验，感谢作者！

**Comment by xcanwin** [comment]
已更正，可以更新到24.2体验
