### ISSUE TITLE
[严重bug]今天发现使用KeepChatGTP 插件 已经发不出信息

### ISSUE THREAD

**Issue by godaizhan** [xcanwin/KeepChatGPT#390]
今天发现使用KeepChatGTP 插件 已经发不出信息，在浏览器无痕模式 就可以正常使用openai ，请问下是那里问题？是否可以更新？
![image](https://github.com/xcanwin/KeepChatGPT/assets/103105164/5e3eb38c-fa6e-44d3-8983-4d9775c81e97)

发信息后没有任何显示，
![image](https://github.com/xcanwin/KeepChatGPT/assets/103105164/d741c07c-eedd-4170-96ad-3de32a18a2d2)
![image](https://github.com/xcanwin/KeepChatGPT/assets/103105164/31ac5f38-3d9f-4f60-aae7-855d61c74927)

能麻烦作者排除下问题吗？

**Comment by xcanwin** [comment]
一直在用，无异常。你清理一下openai.com域名的所有缓存内容

**Comment by godaizhan** [comment]
我已经清理了，并且 重新登陆了，并且重新安装了 依然无法解决
并且我特意尝试过，我在无痕浏览器模式下是可以正常沟通对话，然后我也将 插件启用了无痕模式下启用插件，启用后马上也不能发信息，与正常对话，
我是正常使用你们插件的，并且使用了好久，就今天突然这样的问题，
并我手机安装了openai 客户端，在客户端中也依然可以发信息，但就是安装 `KeepChatGPT` 我们插件后就不能正常对话，

![image](https://github.com/xcanwin/KeepChatGPT/assets/103105164/4055e6e1-f5ca-43a4-8703-7debb3a36fbd)
![image](https://github.com/xcanwin/KeepChatGPT/assets/103105164/f33aecae-c9b4-4d77-9251-1745571dabbd)

**Comment by godaizhan** [comment]
像安装你们插件后，触发`
![image](https://github.com/xcanwin/KeepChatGPT/assets/103105164/959162c8-1708-44a5-a686-12e0a3beb303)
`

这是什么问题？

**Comment by godaizhan** [comment]
![image](https://github.com/xcanwin/KeepChatGPT/assets/103105164/7fc18f15-0264-449d-8421-818fdb7c08cd)
这是我看到一些论坛上，和我遇到的问题，也是一样的

**Comment by lfy5047** [comment]
我的也是发不出消息, 关掉插件, 清除浏览器缓存后, 重新登录, 可以正常使用, 如果再打开插件就不能发送消息了

**Comment by TomIsFat** [comment]
同样的问题，关掉插件就正常

**Comment by Kukuair** [comment]
+1

**Comment by RyougiShang** [comment]
+1

**Comment by zyqhziee1** [comment]
+1

**Comment by H-Bole** [comment]
+1

**Comment by chadshao** [comment]
+1

**Comment by xcanwin** [comment]
666，其实取消了插件也存在这个问题，这是openai官方的bug，排查了半天是Alpha语言环境的问题，我先帮官方也帮大家临时修复一下，大家更新到最新版v24.1即可

**Comment by xcanwin** [comment]
把他抓起来：
![图片](https://github.com/xcanwin/KeepChatGPT/assets/14187349/2fb685c1-891c-4923-a61c-693463040514)

**Comment by junlongzzz** [comment]
> 666，其实取消了插件也存在这个问题，这是openai官方的bug，排查了半天是Alpha语言环境的问题，我先帮官方也帮大家临时修复一下，大家更新到最新版v24.1即可

Damnnnnn

**Comment by SunGod0508** [comment]
把语言设置成英语就行了

**Comment by NijineChakiri** [comment]
不是插件的问题，是官方的bug，目前清除缓存可以解决
方法：在chatgpt页面按F12->应用->存储->勾选【包括第三方cookies】->清除网站数据
