### ISSUE TITLE
每回答一个问题，下一个问题就需要刷新界面1

### ISSUE THREAD

**Issue by Chumumu** [xcanwin/KeepChatGPT#393]
![WeChatf9bc39d10733fa2fab5f5075c191625f](https://github.com/xcanwin/KeepChatGPT/assets/72724846/fc38b24e-d257-415b-9e02-5afc83ac389a)
如图，不知道怎么回事，只要是问第二个问题就一直停留在等待回答的界面，需要刷新才能看到问题答案

**Comment by Chumumu** [comment]
![Snipaste_2024-03-11_10-27-08](https://github.com/xcanwin/KeepChatGPT/assets/72724846/a396695d-6282-463b-9eeb-7a8167467e49)

**Comment by adolfheir** [comment]
我也遇到了 关了插件 清了缓存 还把历史prompt清了下 好像是可以了
