### ISSUE TITLE
默认的回车键无法发送消息

### ISSUE THREAD

**Issue by liuduo2019** [xcanwin/KeepChatGPT#396]
在使用一段时间后，默认回车键无法发送消息，只能点击发送按钮发送消息，请问这是为什么

**Comment by Zhuxiaohuo** [comment]
你可能是网页小于屏幕的一半，所以会出现这种情况，你试试全屏时候这样吗

**Comment by liuduo2019** [comment]
您好，全屏也无法使用enter发送，我这个现象很奇怪，之前都可以用enter发送，过了一段时间enter失效了

**Comment by CkBcDD** [comment]
> 您好，全屏也无法使用enter发送，我这个现象很奇怪，之前都可以用enter发送，过了一段时间enter失效了

**请提供更加详细的信息**
- “显示调试”有无相关报错信息？
- 其他设备上能否复现？
