### ISSUE TITLE
[Feature Request] 支持更快捷地切换使用的模型

### ISSUE THREAD

**Issue by CkBcDD** [xcanwin/KeepChatGPT#397]
# 背景
OpenAI 对 ChatGPT Plus用户依然有限制，在GPT4的使用频次上（40对话每三小时），所以日常功能用GPT3.5就够了。但是目前要切换模型还需要使用鼠标移动左上角，显得有些麻烦。

# 使用场景
用户在切换模型的时候可以通过快捷键（或者图标移动到下面）来切换模型。

# 预期效果
用户切换模型更加方便，更加快捷。

**Comment by xcanwin** [comment]
开源社区有很多类似的
