### ISSUE TITLE
还是会出现监管

### ISSUE THREAD

**Issue by siyue666** [xcanwin/KeepChatGPT#4]
![Screenshot_2023-04-13-08-53-17-246_com kiwibrowser browser](https://user-images.githubusercontent.com/87256859/231617945-c20d6dd0-273e-442d-986d-92cd4f1e3fd7.jpg)

**Comment by siyue666** [comment]
手机取消审计无效，切换桌面版网站就正常了

**Comment by Laoevil** [comment]
你好变态啊

**Comment by xcanwin** [comment]
其实bug前几天就修复了，只是不好评论。
