### ISSUE TITLE
取消审计的作用？

### ISSUE THREAD

**Issue by hhuzzz** [xcanwin/KeepChatGPT#40]
这个按钮有什么作用呢

**Comment by xcanwin** [comment]
发太多违规的问题给chatgpt，你的账号会被封，因为每次提问都会被审计，通过我插件里"取消审计"的功能，可以免受影响。

**Comment by mqhe2007** [comment]
作者可否简单说下原理，为什么通过前端修改就可取消审计？

**Comment by xcanwin** [comment]
> 作者可否简单说下原理，为什么通过前端修改就可取消审计？

在每次聊天请求里

**Comment by mqhe2007** [comment]
> > 作者可否简单说下原理，为什么通过前端修改就可取消审计？
> 
> 在每次聊天请求里

明白了，刚看了源码，开启后屏蔽了“/moderations”请求，看来openAI设计的接口正好有机可乘啊。

**Comment by BanLuSAMA** [comment]
屏蔽“/moderations”请求的方法已经失效了，怎么办？
