### ISSUE TITLE
ui bug，发送的消息垂直显示

### ISSUE THREAD

**Issue by df13954** [xcanwin/KeepChatGPT#422]
净化开关，开和关都是垂直显示。看截图。
![Xnip2024-05-14_09-20-30](https://github.com/xcanwin/KeepChatGPT/assets/18607031/5707effe-c9ed-4916-b690-c472eaf27b56)

今天安装的最新版。

**Comment by Polaris-F** [comment]
同样遇到了 今天GPT更新了  新加入了 GPT4-o  应该是网页设计有变化了 还没来得及适配

**Comment by rrf100** [comment]
![1](https://github.com/xcanwin/KeepChatGPT/assets/18746573/95f80f9d-8133-441f-8ee9-4ccbe2dcd3c6)
注释掉这行css代码就好了

**Comment by xcanwin** [comment]
谢谢反馈，在v27.7中已修复
