### ISSUE TITLE
报错：Unable to load conversation xxxxxxx-xxxxx

### ISSUE THREAD

**Issue by AllForLandlord** [xcanwin/KeepChatGPT#426]
开启最新脚本后，访问chatgpt网页版任意一个对话历史，都会报错“Unable to load conversation xxxxxxx-xxxxx”。试了用日本节点、美国节点、新加坡节点都一样，请确认此问题，非常感谢您！
![image](https://github.com/xcanwin/KeepChatGPT/assets/68906347/b77f6f51-09d2-4597-ad4f-281504eb4cdf)

**Comment by AllForLandlord** [comment]
抱歉，刚才检查了下，脚本没更新到最新版，更新后正常了。汗颜

**Comment by kiss10101** [comment]
我也发现此问题，触发场景与你相同

**Comment by WelsKinG** [comment]
日新月异功能导致的关闭就行,等作者修复

**Comment by kiss10101** [comment]
> 日新月异功能导致的关闭就行,等作者修复

暂时解决问题，感谢！

**Comment by AllForLandlord** [comment]
> 日新月异功能导致的关闭就行,等作者修复

感谢提供思路

**Comment by tanghululalala** [comment]
我也发现是日新月异引起的, 关闭就正常了

**Comment by xcanwin** [comment]
谢谢反馈，在v27.7中已修复

**Comment by AllForLandlord** [comment]
刚才测试下来，如果打开浏览器后第一次打开chatgpt网页，还是会报错，但是刷新下网页又好了

**Comment by AllForLandlord** [comment]
最新版测试下来问题消失了，谢谢作者！
