### ISSUE TITLE
UI 在更在promp完全错位了

### ISSUE THREAD

**Issue by hong-tm** [xcanwin/KeepChatGPT#431]
## 只要我一打字/删除就不是在该在的位置（更改已写的promp）

---

![GIF 2024-5-19 1-14-43](https://github.com/xcanwin/KeepChatGPT/assets/51999870/528babf4-f5c7-4283-b604-0dc069a61c07)

**Comment by hong-tm** [comment]
要把我自己弄到上头了，有点头痛🫡

**Comment by xcanwin** [comment]
openai官方的bug，与插件无关。
另外，你用“克隆对话”功能，在最底下的对话框里编辑prompt，反而可以解决问题。

**Comment by hong-tm** [comment]
> openai官方的bug，与插件无关。 另外，你用“克隆对话”功能，在最底下的对话框里编辑prompt，反而可以解决问题。

ok,等openai官方修复了
