### ISSUE TITLE
What is the point of the anti-feature? 反特性（或反功能）的意义是什么？

### ISSUE THREAD

**Issue by zkisaboss** [xcanwin/KeepChatGPT#432]
> // @antifeature       ads
I'm just curious what this does and why it's relevant to the script?
这有什么作用，为什么它是必要的？

**Comment by xcanwin** [comment]
大陆用户经常无法访问github，所以为了照顾大陆用户，我把代码共享在[greasyfork](https://greasyfork.org/)，他们对二维码图片有[要求](https://greasyfork.org/zh-CN/help/antifeatures)。
