### ISSUE TITLE
KeepChatGPT与webchatgpt冲突

### ISSUE THREAD

**Issue by iwillcodeu** [xcanwin/KeepChatGPT#44]
Hi 
之前装了webchatgpt（chrome插件，地址： https://chrome.google.com/webstore/detail/webchatgpt-chatgpt-with-i/lpfemeioodjbpieminkklglpmhlngfcn），安装Keepchatgpt后，webaccess 功能在new chat里问了第一句后消失。应该是2个插件冲突了，大概率是你这个厉害的插件把人家屏蔽了

**Comment by masonfocus** [comment]
+1, 按道理在搜索栏出现的，结果直接没了，请教怎么解决

**Comment by AllForLandlord** [comment]
> +1, 按道理在搜索栏出现的，结果直接没了，请教怎么解决

https://discord.com/channels/1060110102188797992/1060526685281329182/1098591978662408364
插件的discord群组里有解释这个问题

**Comment by lyyQwQ** [comment]
> > +1, 按道理在搜索栏出现的，结果直接没了，请教怎么解决
> 
> https://discord.com/channels/1060110102188797992/1060526685281329182/1098591978662408364 插件的discord群组里有解释这个问题


我点开，它提示无文字频道

**Comment by AllForLandlord** [comment]
> > > +1, 按道理在搜索栏出现的，结果直接没了，请教怎么解决
> > 
> > 
> > https://discord.com/channels/1060110102188797992/1060526685281329182/1098591978662408364 插件的discord群组里有解释这个问题
> 
> 我点开，它提示无文字频道

这个就是webchatgpt这个浏览器扩展的discord群，你加进去就可以看到了

**Comment by RebelYoung** [comment]
> > > +1, 按道理在搜索栏出现的，结果直接没了，请教怎么解决
> > 
> > 
> > https://discord.com/channels/1060110102188797992/1060526685281329182/1098591978662408364 插件的discord群组里有解释这个问题
> 
> 我点开，它提示无文字频道
![image](https://user-images.githubusercontent.com/59256512/233885480-4526c978-68de-4991-a8a3-0ae4d3b988ae.png)
先从这个链接加入它的group，再点上面的，才能看到。。。但是我没看懂解释了啥

**Comment by Yohann0617** [comment]
点一下New chat再点回原来的会话就好了
