### ISSUE TITLE
29.1 "展示大屏"功能失效，报错啦

### ISSUE THREAD

**Issue by sqy-0425** [xcanwin/KeepChatGPT#455]
普通用户，谷歌浏览器。
![image](https://github.com/user-attachments/assets/51a9b02a-d9a3-4f62-93c4-7053c196a29b)
![image](https://github.com/user-attachments/assets/ae83495a-b71e-491b-a186-dde6731871b8)

**Comment by xcanwin** [comment]
![图片](https://github.com/user-attachments/assets/f8c40980-45d4-4322-ad6b-96487430b97e)
F12->元素选项卡->对着html元素->右键->复制->复制元素->以下面格式发给我，这样html代码不会错乱：
````
```
<html data-build=xxxxxxxxxxxxxxxxxxxxxxxx
```
````

**Comment by sqy-0425** [comment]
太长啦，发不出去
![image](https://github.com/user-attachments/assets/f4ae4165-1bdd-477d-a02d-7c39b6bf03a6)

**Comment by xcanwin** [comment]
保存到文件1.txt，这里可以直接粘贴

**Comment by sqy-0425** [comment]
[html.txt](https://github.com/user-attachments/files/16796049/html.txt)
文件来啦

**Comment by sqy-0425** [comment]
> 展示大屏bug已在v29.2修复

大佬牛逼，成啦，美滋滋
