### ISSUE TITLE
为什么我安装好了插件仍然每个几秒~10几秒仍然报错？

### ISSUE THREAD

**Issue by parcool** [xcanwin/KeepChatGPT#46]
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/12092478/233521972-79cc982b-c8eb-4e71-bac6-221a39b102ad.png">
我这个现在在不用这个插件的时候已经达到了每问一个问题都需要刷新的地步了。不过安装了这个插件后也感觉差不多？哪里的问题？

**Comment by parcool** [comment]
Chrome 已是最新版本
版本 112.0.5615.137（正式版本） (arm64)

**Comment by tsaijamey** [comment]
setInterval(function() {
    if ($(symbol1_class) || $(symbol2_class)) {
        keepChat();
    }
}, 1000 * 30);

源码中请求间隔是30秒。对于大部分使用VPN的用户来说，如果VPN本身有定时自动选择节点的能力，可能会导致在30秒间隔内切换了节点，导致ip变化，这时你在webui发送消息时可能会被Cloudflare拒绝。

你可以先看一下你的VPN是不是设置了自动切换节点，如果是的话，先选定节点试试。

如果与上述无关，那么在Tamper Monkey的脚本里把时间间隔调小一些。

**Comment by parcool** [comment]
> Reference

感谢，我改时间为5秒后就好了。再次谢谢！
