### ISSUE TITLE
有封号的风险吗

### ISSUE THREAD

**Issue by Quios** [xcanwin/KeepChatGPT#47]
毕竟是辛辛苦苦注册的号，所以想要请问一下使用这个插件会导致chatgpt的账号被封吗？存在风险？

**Comment by tsaijamey** [comment]
我看了源码，它本质上就是个前端注入js，OpenAI的页面本身也是用next框架渲染的，也是js，这种并不影响，所以只要代码是干净的，基本上没什么风险。

**Comment by xcanwin** [comment]
油猴插件比浏览器拓展更具备的优势是代码随时能接受大家的阅读和审计，本项目安全、干净，请求的都是官网接口。无需担心安全问题。

**Comment by wangyue-gagua** [comment]
> 油猴插件比浏览器拓展更具备的优势是代码随时能接受大家的阅读和审计，本项目安全、干净，请求的都是官网接口。无需担心安全问题。

除了安全问题就是这种方式保持连接是否会被openai认为是异常流量从而导致封号？

**Comment by xcanwin** [comment]
> > 油猴插件比浏览器拓展更具备的优势是代码随时能接受大家的阅读和审计，本项目安全、干净，请求的都是官网接口。无需担心安全问题。
> 
> 
> 
> 除了安全问题就是这种方式保持连接是否会被openai认为是异常流量从而导致封号？

新增调节频率的功能，值越大越安全

**Comment by kylezhang** [comment]
> > > 油猴插件比浏览器拓展更具备的优势是代码随时能接受大家的阅读和审计，本项目安全、干净，请求的都是官网接口。无需担心安全问题。
> > 
> > 
> > 除了安全问题就是这种方式保持连接是否会被openai认为是异常流量从而导致封号？
> 
> 新增调节频率的功能，值越大越安全

感谢作者的无私奉献。

经常也刷新不出来，我把刷新频率调到30、10都一样。最后还是要手动刷新了。

**Comment by YzGLab** [comment]
不知道是不是这个原因，，，我已经被封号。。。。。。。用了很久的号。。

**Comment by xcanwin** [comment]
我从2月底挂到现在每天在线，你可以看我的更新版本频率。至今账号无异常。
