### ISSUE TITLE
sir，how to handle it

### ISSUE THREAD

**Issue by chenyu-001** [xcanwin/KeepChatGPT#49]
![image](https://user-images.githubusercontent.com/74084960/233533339-f6fbae89-8e27-4185-b16f-0c6fc8c9e5ad.png)

**Comment by chenyu-001** [comment]
![image](https://user-images.githubusercontent.com/74084960/233534549-e92100de-6b83-4306-9ae9-035ec2f4adaa.png)
last error has handled，the new one is can`t effect

**Comment by chenyu-001** [comment]
follw the other issue,make it successful!

**Comment by chenyu-001** [comment]
![image](https://user-images.githubusercontent.com/74084960/233535087-2a56b7df-e44f-4f0b-9275-66766b3f3e8e.png)
but,my gpt get a new block

**Comment by xcanwin** [comment]
我的readme和源代码里的首选语言都是中文

**Comment by chenyu-001** [comment]
> 我的readme和源代码里的首选语言都是中文

所以我得改哪块，能让它布局变得正常，下边多出来一个iframe标签

**Comment by xcanwin** [comment]
其他移到左上角的金标，关闭第一个选项"显示调试"

**Comment by chenyu-001** [comment]
> 其他移到左上角的金标，关闭第一个选项"显示调试"

odk，解决了，超级感谢
