### ISSUE TITLE
移动端无法识别悬停操作，下拉菜单无法弹出

### ISSUE THREAD

**Issue by anyunshen** [xcanwin/KeepChatGPT#5]
移动端无法识别悬停操作，下拉菜单无法弹出，建议考虑使用点击事件来代替悬停操作。

**Comment by xcanwin** [comment]
> 移动端无法识别悬停操作，下拉菜单无法弹出，建议考虑使用点击事件来代替悬停操作。

已增加对移动端呼唤菜单的支持

**Comment by anyunshen** [comment]
已重新安装脚本，好像还是不行，麻烦大佬再看一下

**Comment by xcanwin** [comment]
你反馈一下使用的手机型号、系统版本、浏览器、浏览器版本、运行插件的工具

**Comment by anyunshen** [comment]
iPhone12 
iOS16.3.1 
Safari 
userscripts
已自行将onclick更换为ontouchstart，仍无效😭

**Comment by xcanwin** [comment]
我和你差异比较大的地方在于我移动端使用的是Stay，安装本插件成功后嵌入方式选择Content

**Comment by anyunshen** [comment]
使用stay后下拉菜单已可用，感谢🙏
但是取消审计按钮点击后没反应😂

**Comment by xcanwin** [comment]
最新版已修复
