### ISSUE TITLE
Still need refresh

### ISSUE THREAD

**Issue by DancinPuppet** [xcanwin/KeepChatGPT#51]
I using my openai accout in Chrome browser,but i can not caht with it smoothly.Once l not response chat contents in a few seconds. I would have to refresh my page.After i using this plugins,the problem still exist.

**Comment by chenwusheng7746** [comment]
You can try using the private browsing mode of Firefox browser, it has been tested and proven effective.

**Comment by xcanwin** [comment]
新增自定义频率功能，适度缩短维持在线的间隔

**Comment by DancinPuppet** [comment]
> You can try using the private browsing mode of Firefox browser, it has been tested and proven effective.
guys,I have tried your methords,it's very useful! Thank you again for  your advice, it means a lot.
