### ISSUE TITLE
是否会自动刷新导致的这个问题呢

### ISSUE THREAD

**Issue by Anandonzy** [xcanwin/KeepChatGPT#55]
{"detail":"Too many requests in 1 hour. Try again later."}
今天访问的时候发现有这个问题,以致于访问不了.

**Comment by LagPixelLOL** [comment]
同问, 电脑上出现这个问题, 手机上也不能访问了, 更换了IP才恢复.

**Comment by xcanwin** [comment]
新增自定义频率功能，尝试一下增大keep的时间间隔
