### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ww0128** [xcanwin/KeepChatGPT#59]
我发现pc端就是如果用了这个插件，然后chatgpt对话提示错误了，如果点页面刷新，会一直进不去了，关掉这个插件就可以进去

**Comment by ww0128** [comment]
![image](https://user-images.githubusercontent.com/110089244/233664801-9b57d5f2-fd2f-4af6-b323-647572ebef8e.png)

**Comment by CRMLF** [comment]
+1，打开调试功能之后，下面提示：{"detail":"Too many requests in 1 hour. Try again later."}

**Comment by LagPixelLOL** [comment]
我也出现了这个问题, 但是我电脑上出现了无法加载, 删除了插件也不能访问, 手机上也不能访问, 更换IP才恢复.
而且如果出现了这个情况, 用无痕模式登录另一个账号也无法加载, 怀疑可能是刷新太多导致IP被限制.

**Comment by xcanwin** [comment]
已新增自定义频率功能，我个人使用的是150s

**Comment by ww0128** [comment]
是这个插件在不停刷新嘛

**Comment by MengXinxin1** [comment]
> 

我也出现了相同问题，请问怎么更换IP呢，是直接更换节点吗

**Comment by ww0128** [comment]
我咋感觉就是用这个插件才出现的这种问题

**Comment by CRMLF** [comment]
> 我咋感觉就是用这个插件才出现的这种问题

不是，我没用的时候也出现

**Comment by heman0101** [comment]
我也出现了同样的问题，现在关闭插件也刷新不进去了，怎么样解决呢

**Comment by liuxilai** [comment]
我这里使用插件也有报错，too many request in 1 hour, try again later.

**Comment by heman0101** [comment]
> 已新增自定义频率功能，我个人使用的是150s
我试了这个还是不行

**Comment by xcanwin** [comment]
https://github.com/xcanwin/KeepChatGPT/issues/62

**Comment by xcanwin** [comment]
readme已提到Too many requests in 1 hour等新遇到的错误的原因和解决方案：https://github.com/xcanwin/KeepChatGPT#%E5%85%B6%E4%BB%96%E8%AF%B4%E6%98%8E
