### ISSUE TITLE
好难过,还是出现了something went wrong，设置的频率是100

### ISSUE THREAD

**Issue by UserZhitao** [xcanwin/KeepChatGPT#60]
<img width="638" alt="屏幕截图 2023-04-22 012747" src="https://user-images.githubusercontent.com/34535478/233698755-ae6ae3e4-e292-477a-928d-627e42b24cbe.png">

**Comment by chenwusheng7746** [comment]
我设置的20,其他的都会出现错误

**Comment by kylezhang** [comment]
> 我设置的20,其他的都会出现错误

我是10、20、30 都有设置，还是会出现
<img width="1280" alt="截屏2023-04-22 10 39 59" src="https://user-images.githubusercontent.com/3679798/233757724-4cc94768-dcd7-40ba-ba05-a09cce50e4ec.png">

**Comment by chenwusheng7746** [comment]
> > 我设置的20,其他的都会出现错误
> 
> 我是10、20、30 都有设置，还是会出现 <img alt="截屏2023-04-22 10 39 59" width="1280" src="https://user-images.githubusercontent.com/3679798/233757724-4cc94768-dcd7-40ba-ba05-a09cce50e4ec.png">

可能是梯子的问题.我昨晚换了日本的梯子,好了很多

**Comment by Kevin-free** [comment]
我也是，有解决方案吗？

**Comment by xcanwin** [comment]
参考readme底部的说明
