### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by meesii** [xcanwin/KeepChatGPT#62]
作者其实没必要去刷session的接口，因为插件的目的是保活，cf层面的保活。
gpt本身的session有效期是24小时的。
我的建议是去刷新别的接口，比如backend-api/models。
虽然没有header的token，但是没关系啊，它已经过了cf的验证了。
我用了很长时间了，backend-api/models接口随便刷都不会有频繁限制。

下面是我用作者代码改的Requestly规则
![image](https://user-images.githubusercontent.com/1815046/233719589-f62d5c9c-3073-4897-b8c4-725d647dbab5.png)

**Comment by xcanwin** [comment]
其实session接口，我内测了半个月一直没掉线以后才发布公测的，公测了一个月我依旧一直没掉线。
而收到很多反馈说"还是不行"的大概原因是他们的梯子所在区域、机房、c段网络等经常对cf保护的各类网站进行爬虫被cf加入了统一的黑名单里，简单地说就是：有风控。

**Comment by xcanwin** [comment]
后面如果我使用session失效了，我会采纳你的意见
