### ISSUE TITLE
我的gpt页面用了这个插件变成这个样子了，排版直接错乱了，删了插件也回不去了，请问怎么办呀

### ISSUE THREAD

**Issue by jwh12333** [xcanwin/KeepChatGPT#64]
![图片1](https://user-images.githubusercontent.com/109291929/233755047-d51f2dcf-d59c-470a-b4f8-36d3bef163ab.png)

**Comment by xcanwin** [comment]
插件只有在存在并且启动的时候，才可以影响网页。
插件不存在的时候，网页有异常的话说明你浏览器其他插件或者拓展存在bug。
