### ISSUE TITLE
顶部logo走光闪烁，很干扰看内容

### ISSUE THREAD

**Issue by goto911** [xcanwin/KeepChatGPT#65]
每次都手动注释闪烁的样式，但是脚本升级，代码就覆盖了，闪烁真的很扰民，能否取消掉

**Comment by jingyaogong** [comment]
再新建个油猴脚本呗，里面定义你想要的样式
比如想去掉闪烁，用这段脚本
```
// ==UserScript==
// @name         KeepChatGPT 去掉闪烁
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  KeepChatGPT 去掉闪烁
// @author       myself
// @match        https://chat.openai.com/*
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    var style = document.createElement('style');

    style.textContent = '#kcg::before { display:none;content: ""; position: absolute; top: -50%; left: -50%; width: 200%; height: 200%; background: linear-gradient(to bottom right, rgba(255, 255, 255, 0.3), rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0)); transform: rotate(-45deg); animation: shine 2.8s linear infinite; }';

    document.head.appendChild(style);

    // Your code here...
})();
```
以后keepchatgpt更新就不影响你自定义的东西了

**Comment by KevinZhangt** [comment]
顺便改一下背景色:
```javascript
// ==UserScript==
// @name         KeepChatGPT 去掉闪烁
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  KeepChatGPT 去掉闪烁
// @author       myself
// @match        https://chat.openai.com/*
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    var style = document.createElement('style');

    style.textContent = '#kcg::before { display:none;content: ""; position: absolute; top: -50%; left: -50%; width: 200%; height: 200%; background: linear-gradient(to bottom right, rgba(255, 255, 255, 0.3), rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0)); transform: rotate(-45deg); animation: shine 2.8s linear infinite; } #kcg {background-color: rgb(32, 33, 35) !important;}';

    document.head.appendChild(style);

    // Your code here...
})();
```

**Comment by LingYu66** [comment]
`// ==UserScript==
// @name         KeepChatGPT 去掉闪烁
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  KeepChatGPT 去掉闪烁
// @author       myself
// @match        https://chat.openai.com/*
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    var style = document.createElement('style');

    style.textContent = '#kcg::before { display:none;content: ""; position: absolute; top: -50%; left: -50%; width: 200%; height: 200%; background: linear-gradient(to bottom right, rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.15), rgba(0, 0, 0, 0))!important; transform: rotate(-45deg); animation: shine 2.8s linear infinite; } #kcg {background: rgb(35, 35, 35) !important;font-weight:normal !important;color:#FFFFFF !important}';

    document.head.appendChild(style);

    // Your code here...
})();`

**Comment by LingYu66** [comment]
// ==UserScript==
// @name         KeepChatGPT 去掉闪烁
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  KeepChatGPT 去掉闪烁
// @author       myself
// @match        https://chat.openai.com/*
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    var style = document.createElement('style');

    style.textContent = '#kcg::before { display:none;content: ""; position: absolute; top: -50%; left: -50%; width: 200%; height: 200%; background: linear-gradient(to bottom right, rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.15), rgba(0, 0, 0, 0))!important; transform: rotate(-45deg); animation: shine 2.8s linear infinite; } #kcg {background: rgb(35, 35, 35) !important;font-weight:normal !important;color:#FFFFFF !important}';

    document.head.appendChild(style);

    // Your code here...
})();

**Comment by LingYu66** [comment]
修改logo背景颜色、字体颜色、取消粗体
````javascript
// ==UserScript==
// @name         KeepChatGPT 去掉闪烁
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  KeepChatGPT 去掉闪烁
// @author       myself
// @match        https://chat.openai.com/*
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    var style = document.createElement('style');

    style.textContent = '#kcg::before { display:none;content: ""; position: absolute; top: -50%; left: -50%; width: 200%; height: 200%; background: linear-gradient(to bottom right, rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.15), rgba(0, 0, 0, 0))!important; transform: rotate(-45deg); animation: shine 2.8s linear infinite; } #kcg {background: rgb(35, 35, 35) !important;font-weight:normal !important;color:#FFFFFF !important}';

    document.head.appendChild(style);
})();
````

**Comment by Patrick-Ze** [comment]
站在巨人的肩膀上，于是有了这个stylus样式
```css
#kcg::before {
    display: none;
    content: "";
    position: absolute;
    top: -50%;
    left: -50%;
    width: 200%;
    height: 200%;
    background: linear-gradient(to bottom right, rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.15), rgba(0, 0, 0, 0))!important;
    transform: rotate(-45deg);
    animation: shine 2.8s linear infinite;
}
#kcg {
    background: rgb(35, 35, 35) !important;
    font-weight: normal !important;
    color: #FFFFFF !important
}
```

**Comment by LingYu66** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wanzhiyu** [comment]
确实，希望给出直接的开关，真的受不了这个闪烁，logo静态的就没问题

**Comment by Ezra-Chan** [comment]
> 确实，希望给出直接的开关，真的受不了这个闪烁，logo静态的就没问题

我已提交了动画开关的PR，等作者审核中😊

**Comment by Ezra-Chan** [comment]
> > 确实，希望给出直接的开关，真的受不了这个闪烁，logo静态的就没问题
> 
> 我已提交了动画开关的PR，等作者审核中😊

已合并，更新脚本即可

**Comment by xcanwin** [comment]
> > 确实，希望给出直接的开关，真的受不了这个闪烁，logo静态的就没问题
> 
> 
> 
> 我已提交了动画开关的PR，等作者审核中😊

谢谢提交PR，已添加取消动画功能

**Comment by 14790897** [comment]
> > > 确实，希望给出直接的开关，真的受不了这个闪烁，logo静态的就没问题
> > 
> > 
> > 我已提交了动画开关的PR，等作者审核中😊
> 
> 谢谢提交PR，已添加取消动画功能

干得好
