### ISSUE TITLE
重启后再次连接openai需要重新安装插件

### ISSUE THREAD

**Issue by fw0037** [xcanwin/KeepChatGPT#7]
本人服务器操作系统 是windows10
重启后再次连接openai时，不显示[KeepChatGPT]图标，再次使用时报networkerror，需要重新安装插件才能正常显示图标。
请问如何可以在重启服务器后，自动连接 openai时，能自动加载成功KeepChatGPT

**Comment by xcanwin** [comment]
如果使用了最新版keepchatgpt还出现同样的问题，就提供多点信息给我，比如截图、浏览器、浏览器版本、Tampermonkey版本、每次重启后keepchatgpt在Tampermonkey里消失的截图、控制台截图等，我帮你分析下
