### ISSUE TITLE
用了，但感觉没有用。

### ISSUE THREAD

**Issue by hifi5793** [xcanwin/KeepChatGPT#74]
能做的都做了，换了间隔，点了选项，不停的换节点，最后跟之前没有任何不同，不知道还有没有什么办法。

**Comment by 2ndMessiah** [comment]
All is good here, working like a charm. I've never seen any error notification since then.

**Comment by hifi5793** [comment]
maybe i should modify operator instead of network node.

**Comment by ledoen** [comment]
我也是这个情况，用了以后还是频繁弹验证，难道是使用方法不对，图标显示出来了，确认脚本运行了

**Comment by hifi5793** [comment]
换个贵点的vpn会好些，大概年费300左右的就不错，我的年费200，感觉是差了点意思。但也不能避免出错，不知道其他人怎么做到完全不报红的。

**Comment by ledoen** [comment]
我的解决了，我之前没有选那个审计，把审计英文看成adult”成人“了就没选，现在选了感觉好了。

**Comment by 1141943639** [comment]
我还是一样, 感觉完全没有帮助的样子

**Comment by xcanwin** [comment]
原因其实很复杂，readme已提到了相关的原因和解决方案：https://github.com/xcanwin/KeepChatGPT#%E5%85%B6%E4%BB%96%E8%AF%B4%E6%98%8E
