### ISSUE TITLE
作者你好, 能不能时间间隔能设置为范围随机值!

### ISSUE THREAD

**Issue by chenzhihao1040728129** [xcanwin/KeepChatGPT#75]
定时定秒的刷新, 个人觉得很容易被风控识别,  如果是某个间隔范围内的随机值可能比较好!

**Comment by 2ndMessiah** [comment]
Support this but u ought to change the tone of your speech to express thankfulness to the dev before making a request lol..

Auto refresh extensions in the Chrome market adopt random refresh intervals as well. This makes sense.

TY to the dev for the devotion.

**Comment by xcanwin** [comment]
可以，晚些时候

**Comment by chenzhihao1040728129** [comment]
> 可以，晚些时候

作者大佬你好,  那个时间我自定义实现,  但是我现在发现, 和别的Chrome插件样式冲突........,    不能一起使用,   用了之后别的插入样式缺少, 例如:  Superpower ChatGPT插件

**Comment by xcanwin** [comment]
附上截图看看啥情况

**Comment by chenzhihao1040728129** [comment]
> 附上截图看看啥情况

![image](https://user-images.githubusercontent.com/49114216/233889915-d3a033e0-3d0b-42c2-bae1-dc3cb7bffeff.png)

**Comment by xcanwin** [comment]
它改变太多样式了，而且后面还会持续改变，我不太愿意经常跟进它的样式变化。

**Comment by chenzhihao1040728129** [comment]
> 它改变太多样式了，而且后面还会持续改变，我不太愿意经常跟进它的样式变化。

那是否多提供一个无样式的版本?  个人觉得会有同时用几个插件的需求
