### ISSUE TITLE
成功避免了断连问题，但是出现了too many requests in 1 hour

### ISSUE THREAD

**Issue by HoBeedzc** [xcanwin/KeepChatGPT#76]
作者您好，我使用之后成功避免了断连问题。但是在一段时间后出现了too many requests in 1 hour的问题，因为之前从来没有遇到过，所以想问一下是否是因为使用了这个插件导致的。

**Comment by frosthobbit** [comment]
在有这插件之前我就遇到过这个问题，刚玩的时候聊太狠了T-T

**Comment by PandyYang** [comment]
调整频率。或者开会员。
