### ISSUE TITLE
能否提供一个随机值范围选择，这样子会更像真人一些。

### ISSUE THREAD

**Issue by Yang9322** [xcanwin/KeepChatGPT#77]
毕竟现在自己的GPT账号比较宝贵，而且很难再注册了。非常感谢~

**Comment by zzrice** [comment]
感觉这个想法很好，不知道作者能不能考虑一下

**Comment by xcanwin** [comment]
可以，晚些时间发布

**Comment by Ezra-Chan** [comment]
> 可以，晚些时间发布

默认在设置的间隔时间向上浮动10秒，在该范围内随机，这样可以吗？

**Comment by Yang9322** [comment]
可能只向上浮动10s的话，范围有点小，上下浮动10秒ok吗？

**Comment by xcanwin** [comment]
> > 可以，晚些时间发布
> 
> 默认在设置的间隔时间向上浮动10秒，在该范围内随机，这样可以吗？

其实我有两个新功能打算研发，第一个是探索间隔，第二个是随机间隔。
探索间隔：自动化探索最大的间隔值，好比我适合150秒的间隔，然后这还不是我的上限，这个需要先开发出来。
随机间隔：本issue提到的，有了最大间隔值以后，就可以按比例得出大概的浮动值。像有的人5分钟才需要刷新一次，那他的浮动值会比20秒刷新一次的人大很多。

**Comment by Ezra-Chan** [comment]
> 其实我有两个新功能打算研发，第一个是探索间隔，第二个是随机间隔。 探索间隔：自动化探索最大的间隔值，好比我适合150秒的间隔，然后这还不是我的上限，这个需要先开发出来。 随机间隔：本issue提到的，有了最大间隔值以后，就可以按比例得出大概的浮动值。像有的人5分钟才需要刷新一次，那他的浮动值会比20秒刷新一次的人大很多。

那就等作者更新了👍

**Comment by xcanwin** [comment]
> > 其实我有两个新功能打算研发，第一个是探索间隔，第二个是随机间隔。 探索间隔：自动化探索最大的间隔值，好比我适合150秒的间隔，然后这还不是我的上限，这个需要先开发出来。 随机间隔：本issue提到的，有了最大间隔值以后，就可以按比例得出大概的浮动值。像有的人5分钟才需要刷新一次，那他的浮动值会比20秒刷新一次的人大很多。
> 
> 那就等作者更新了👍

你写的代码我非常喜欢，我发现你会认真阅读并尊重作者的编码习惯去创作，就像我开发的一样哈哈哈哈，是一个非常细心的人。
