### ISSUE TITLE
大佬更新插件了

### ISSUE THREAD

**Issue by Rennen0929** [xcanwin/KeepChatGPT#8]
![image](https://user-images.githubusercontent.com/89285206/231925955-743312ff-6836-4a9f-b1d8-464e5802f196.png)
![image](https://user-images.githubusercontent.com/89285206/231925761-2b268432-6509-412a-bc67-8c811cffcea7.png)
如图，好像 chatGPT 更新了，得修改下 @match 才能用了
❤❤❤

**Comment by Rennen0929** [comment]
不好意思，是我自己没有更新插件

**Comment by xcanwin** [comment]
只要更新的速度比催更的快，就没人能催更得了我。
