### ISSUE TITLE
刷新频率最低是多少呢?

### ISSUE THREAD

**Issue by xxjldh** [xcanwin/KeepChatGPT#82]
安装完插件,然后现在遇到的问题是,如果一直停留在chatGPT页面,最后被问到的问题会按照设置的刷新频率在后台一直刷新,因为现在安装了plus,使用了gpt4模型,3个小时以内最多只能回答25个问题.我担心一会就给刷没了.所以想设置一个最低频率保持在线的数值.

**Comment by chenwusheng7746** [comment]
可能对这个有误解,插件提供的刷新相当于你手动刷新页面或者手动切换会话的频率,并不是问问题的频率,你没有发送问题不会调用openai的接口

**Comment by xxjldh** [comment]
那我可能遇到了一个比较严重的问题，我今天安装了2个keep chatpgt插件，现在的问题是无法禁用脚本，把脚本从油猴那里禁用，删除以后，重新刷新浏览器，脚本依旧执行，请问这个是什么问题呀，我把另外一个脚本很早就删掉了，现在还是会自动发送请求，就感到很奇怪。

**Comment by Laoevil** [comment]
ctrl+f5 ; 可能有缓存

**Comment by xcanwin** [comment]
那个功能已改成刷新间隔时间，刷新使用的接口不会影响你提问的次数，是独立的。间隔越长越好，我用150秒间隔就很稳定。

**Comment by xxjldh** [comment]
嗯,谢谢啦,我把油猴卸载重新装了一遍,然后重新安装了本插件,现在正常了.
