### ISSUE TITLE
Chrome无痕模式下无法启用

### ISSUE THREAD

**Issue by TonyYanOnFire** [xcanwin/KeepChatGPT#83]
Chrome无痕模式下没有图标出现, 也没有keep效果. 而普通模式正常. 

已确认: Tampermonkey插件开启了"在无痕模式下启用"

**Comment by Ezra-Chan** [comment]
我试了无痕模式是可以的🤔️

**Comment by TonyYanOnFire** [comment]
应该是我安装后没有重启无痕浏览器的原因
