### ISSUE TITLE
"关于"链接在新页面打开

### ISSUE THREAD

**Issue by TonyYanOnFire** [xcanwin/KeepChatGPT#84]
建议将"关于"链接设置为在新页面打开(target="_blank")

**Comment by Ezra-Chan** [comment]
> 建议将"关于"链接设置为在新页面打开(target="_blank")

最新版已更改了，请更新脚本

**Comment by xcanwin** [comment]
> > 建议将"关于"链接设置为在新页面打开(target="_blank")
> 
> 
> 
> 最新版已更改了，请更新脚本

👍🏻
