### ISSUE TITLE
安装插件后原本能用免费版chatGPT变得完全不可用，关闭插件后也完全不可用，求帮助

### ISSUE THREAD

**Issue by numb89757** [xcanwin/KeepChatGPT#86]
<img width="960" alt="dbf79355252b08624a9fd3bc38dd107" src="https://user-images.githubusercontent.com/90945732/233823611-44d2cac3-da9e-44e0-bd24-8ed5aee8a877.png">
如图所示，之前还能用的，装了插件就变成这样，删除插件后还是这样，目前能正常登录，但是登陆后未经过cloudflare的人机审核界面直接进入如上图的界面，然后无账号信息，无历史提问，无法提问...，而且刷新页面查看HTTP请求有很多429错误...
目前排除是账号的问题，因为登录其他人的账号也是这种情况。理论上也不该是梯子的问题，似乎就是和使用该插件有关？
不知道有没有朋友遇到过？感谢帮助。

**Comment by numb89757** [comment]
看到之前有人提过这个问题，似乎没有解决方案？#59

**Comment by xcanwin** [comment]
清理cookie，重新登陆openai就好了。

**Comment by numb89757** [comment]
感谢回复。我已经尝试过清理cookie，重新登录还是这个情况。换了edge浏览器试了试竟然也是这样。

**Comment by xcanwin** [comment]
看看控制台报错和网络请求返回值截图

**Comment by numb89757** [comment]
{"detail":"Too many requests in 1 hour. Try again later."}
也是这个问题

**Comment by numb89757** [comment]
已经解决，晾着不动等几个小时就好
