### ISSUE TITLE
我调的是50s啊

### ISSUE THREAD

**Issue by xiaoxiaoliuzzZ** [xcanwin/KeepChatGPT#87]
detail":"Too many requests in 1 hour. Try again later.

**Comment by fjiabinc** [comment]
我的也是.插件有问题

**Comment by xcanwin** [comment]
如果网络请求频率都是正常的，那还有很多原因导致。
可能是你有一些调用chatgpt的搜索引擎插件。
可能是因为插件太顺畅，导致你和chatgpt聊天频率提高了，普通账号的聊天次数有限制的。
可能你的位移魔法是共享的但是你不知道。

**Comment by fjiabinc** [comment]
> 如果网络请求频率都是正常的，那还有很多原因导致。 可能是你有一些调用chatgpt的搜索引擎插件。 可能是因为插件太顺畅，导致你和chatgpt聊天频率提高了，普通账号的聊天次数有限制的。 可能你的位移魔法是共享的但是你不知道。

很抱歉,是我这边的问题.  之前用的节点不干净,session接口返回错误. 换了个干净的代理就好了

**Comment by Niuanan** [comment]
哪个代理干净啊

**Comment by Mingtha** [comment]
这个是你的代理使用的人太多了

**Comment by xcanwin** [comment]
readme已提到Too many requests in 1 hour的原因和解决方案：https://github.com/xcanwin/KeepChatGPT#%E5%85%B6%E4%BB%96%E8%AF%B4%E6%98%8E
