### ISSUE TITLE
etail":"Too many requests in 1 hour. Try again later."}

### ISSUE THREAD

**Issue by yanjin1234** [xcanwin/KeepChatGPT#89]
顶部一直转圈，没使用keepchatgpt之前，这种情况最多半个小时就自动解除了，现在5，6个小时都还是这样，是被封号了吗？

**Comment by xcanwin** [comment]
不会封号，readme已有说明：https://github.com/xcanwin/KeepChatGPT#%E5%85%B6%E4%BB%96%E8%AF%B4%E6%98%8E
