### ISSUE TITLE
Too many requests in 1 hour. Try again later

### ISSUE THREAD

**Issue by yanjin1234** [xcanwin/KeepChatGPT#92]
![image](https://user-images.githubusercontent.com/131598281/233876682-7088a7cb-6e00-4c16-a9fc-d97cec1a788b.png)
一直转圈登不上，10几个小时了。这种情况用
KeepChatGPT之前都最多半个小时就恢复了，怎么解决？

**Comment by relic-yuexi** [comment]
换个梯子就能进了,不过好像这个梯子ip像是永久封了一样,我也是之前就过一段时间就好,现在过了一天都没有用,只能换梯子.

**Comment by Mankvis** [comment]
我现在也是这个情况，过1天就好了

**Comment by hwb96** [comment]
我是在对话框里报错，你这个咋在外边报错了？

**Comment by xcanwin** [comment]
参考readme，已有说明原因和解决方案：https://github.com/xcanwin/KeepChatGPT#%E5%85%B6%E4%BB%96%E8%AF%B4%E6%98%8E
