### ISSUE TITLE
关于Script Cat插件无法运行KeepChatGPT

### ISSUE THREAD

**Issue by SakMura** [xcanwin/KeepChatGPT#94]
换了暴力猴，可以运行这个脚本。Script Cat插件却不行了，是不是不兼容吗？
<img width="1046" alt="Snipaste_2023-04-24_10-10-25" src="https://user-images.githubusercontent.com/26195171/233884373-0a2d2cb5-311c-49cc-96e7-cb94e015e12e.png">
<img width="1046" alt="Snipaste_2023-04-24_10-06-31" src="https://user-images.githubusercontent.com/26195171/233884376-b1993b49-cd5c-4522-a451-5f2ab74dde5a.png">

**Comment by xcanwin** [comment]
我会优先兼容主流的油猴拓展，ScriptCat还在兼容主流油猴的语法，期待他成熟的那天。
