### ISSUE TITLE
gpt官方服务器挂掉了吗，有没有什么便捷的方法知道是不是服务器出故障了

### ISSUE THREAD

**Issue by songyu-wang98** [xcanwin/KeepChatGPT#95]
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/57697266/233894330-1e59eaa2-6c2f-4fcb-879a-99e151d7202c.png">

如图，gpt突然显示这样的情况，一直刷新也没有，出现这个图片的10分钟前还可以正常使用。。

**Comment by songyu-wang98** [comment]
刷新了浏览器缓存，可以正常登录，但是没有历史记录，也没有 new chat 字样，有类似的情况吗

**Comment by Ghost818** [comment]
我这几天一直是这样，换节点偶尔能进去，但是很快又这样了。

**Comment by songyu-wang98** [comment]
> 我这几天一直是这样，换节点偶尔能进去，但是很快又这样了。

我过了一会发现又可以用了，很玄学，用的是新加坡的节点
