### ISSUE TITLE
使用了这个插件一直转圈

### ISSUE THREAD

**Issue by itzpm** [xcanwin/KeepChatGPT#97]
![image](https://user-images.githubusercontent.com/56014350/233910842-b4572bac-8334-44a7-a76f-0ae0f5874304.png)

**Comment by zhupeimeng** [comment]
我关了重新进浏览器就可以

**Comment by zqprince** [comment]
> 

我也是这个问题，但是我关闭后重进浏览器还是转圈

**Comment by iknow2333** [comment]
网站挂了，自己看https://status.openai.com/

**Comment by itzpm** [comment]
> 网站挂了，自己看https://status.openai.com/

好像没有

**Comment by zqprince** [comment]
@itzpm 确实没有 不知道目前是因为什么问题，关闭了之后也是这样

**Comment by zqprince** [comment]
@iknow2333 而且我同样的魔法，另外一台设备就可以正常对话，这台设备就无法进行对话，就一直有转圈

**Comment by itzpm** [comment]
> @itzpm 确实没有 不知道目前是因为什么问题，关闭了之后也是这样

是的,我关闭了要等一下才可以用

**Comment by itzpm** [comment]
> 转圈一般是 429 问题，可以打开控制台看下接口返回~

Too many requests in 1 hour. Try again later.这个问题,

**Comment by itzpm** [comment]
> 转圈一般是 429 问题，可以打开控制台看下接口返回~

我用其它电脑或者浏览器打开不会,但是用了这个插件会
