### ISSUE TITLE
使用了这个插件之后一直转圈

### ISSUE THREAD

**Issue by zqprince** [xcanwin/KeepChatGPT#99]
使用了插件之后一直在转圈，换了好多个节点以及魔法都无法解决，而且插件目前已经被我关闭了，还是依旧在转圈；清空Cookie，无痕浏览都试过了，以及另外一台设备同样的魔法和节点就可以正常进行对话（无转圈的情况发生）

**Comment by zqprince** [comment]
#97

**Comment by xcanwin** [comment]
更换浏览器，例如用火狐浏览器
